#!/usr/bin/env python3
"""Estimate a competitive Liberty for a custom cell by scaling/composing FOUNDRY liberty tables.

REPLACES the open-source characterization (CharLib) step with pure data manipulation of the foundry's
own trustworthy tables. CharLib inflates input capacitance ~5.4x and costs ~16 h/cell, which blocks the
end-to-end workflow and poisons the optimizer's cost model. Until a commercial characterizer is wired
in, model each custom cell's timing from real foundry tables instead of measuring it:

  enhance  a transistor-optimized cell (e.g. rise-skewed NOR3_PU2) = the base foundry cell's liberty
           with the target edge(s) scaled by a derate. `--edge both` (5% assumption: --derate 0.95)
           scales cell_rise+cell_fall+transitions; `--edge rise|fall` scales one edge.

  merge    a fused cell = the through-path arcs composed from the two constituents' foundry arcs
           (2-stage NLDM: stage1 delay loaded by cell2's input cap + stage2 delay loaded by the output
           load, via bilinear interpolation on the real tables), times a gain (<1) that credits the
           eliminated inter-cell wire/buffer. `--gain 0.95` = the 5% reduction assumption. Inputs that
           drive cell2 directly keep cell2's arc x gain. Every number is a real foundry table value.

The cell's PHYSICAL data (LEF, area, DRC, LVS) stays REAL -- only timing is modeled.

*** MODELED TIMING, NOT MEASURED. Any PPA from a cell using this lib is a WORKFLOW DEMONSTRATION. ***
The output lib carries a banner comment saying so; do not report its numbers as a measured result.
"""
import argparse
import json
import re
import sys


def brace_body(text, open_pos):
    """Given index of a '{', return index of its matching '}'."""
    depth, j = 0, open_pos
    while j < len(text):
        if text[j] == '{':
            depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0:
                return j
        j += 1
    raise ValueError('unbalanced braces')


def library_header(text):
    """Everything up to (not including) the first `cell (` -- units, thresholds, voltage_map,
    operating_conditions, and ALL lu_table_templates. Reusing it verbatim means the custom cell's
    tables reference the same templates and the lib is valid for free."""
    m = re.search(r'\n\s*cell\s*\(', text)
    return text[:m.start()]


def extract_cell(text, cell_name):
    m = re.search(r'\n\s*cell\s*\(\s*"?%s"?\s*\)\s*\{' % re.escape(cell_name), text)
    if not m:
        sys.exit('cell not found: %s' % cell_name)
    ob = text.index('{', m.start())
    return text[m.start():brace_body(text, ob) + 1]


def transform_groups(text, names, fn):
    """Apply fn to the full text of each `name (...) { ... }` group whose name is in names."""
    pat = re.compile(r'\b(' + '|'.join(names) + r')\s*\([^)]*\)\s*\{')
    out, i = [], 0
    while True:
        m = pat.search(text, i)
        if not m:
            out.append(text[i:])
            break
        out.append(text[i:m.start()])
        end = brace_body(text, m.end() - 1)
        out.append(fn(text[m.start():end + 1]))
        i = end + 1
    return ''.join(out)


def scale_values(group, factor):
    """Scale every number inside this group's values(...) block by factor; leave index_1/index_2
    (the slew/load axes) untouched -- only the delay/transition surface changes."""
    def sv(m):
        return re.sub(r'\d+\.\d+(?:[eE][+-]?\d+)?',
                      lambda n: '%.6f' % (float(n.group()) * factor), m.group())
    return re.sub(r'values\s*\(.*?\)\s*;', sv, group, flags=re.S)


BANNER = ('/* ================================================================================\n'
          ' * MODELED TIMING -- NOT MEASURED. Generated by scripts/estimate_lib.py as a temporary\n'
          ' * stand-in for full SPICE characterization. Delays are foundry tables %s.\n'
          ' * PPA from this lib is a WORKFLOW DEMONSTRATION, not a characterized result.\n'
          ' * ============================================================================== */\n')


def emit(header, cell_block, banner_note):
    header = re.sub(r'(library\s*\(\s*)"?[A-Za-z0-9_]+"?(\s*\))', r'\1celluzi_est\2', header, count=1)
    return header + BANNER % banner_note + cell_block + '\n}\n'


def enhance(args):
    text = open(args.base).read()
    block = extract_cell(text, args.base_cell)
    block = re.sub(r'(cell\s*\(\s*)"?%s"?(\s*\))' % re.escape(args.base_cell),
                   r'\g<1>%s\g<2>' % args.name, block, count=1)
    if args.area is not None:
        block = re.sub(r'(\barea\s*:\s*)[0-9.]+', r'\g<1>%g' % args.area, block, count=1)
    edges = {'rise': ['cell_rise', 'rise_transition'],
             'fall': ['cell_fall', 'fall_transition'],
             'both': ['cell_rise', 'rise_transition', 'cell_fall', 'fall_transition']}[args.edge]
    block = transform_groups(block, edges, lambda g: scale_values(g, args.derate))
    note = ('with the %s edge scaled x%g (models the %s enhancement); cap kept from %s (optimistic)'
            % (args.edge, args.derate, args.name, args.base_cell))
    open(args.out, 'w').write(emit(library_header(text), block, note))
    print('enhance: %s = %s with %s x%g -> %s' % (args.name, args.base_cell, args.edge, args.derate, args.out))


# --------------------------------------------------------------------------------------------------
# merge mode -- 2-stage NLDM composition of a fused cell from its two foundry constituents.
# --------------------------------------------------------------------------------------------------
NUMRE = re.compile(r'-?\d+\.?\d*(?:[eE][+-]?\d+)?')


def _cell_block(lib_text, name):
    return extract_cell(lib_text, name)


def _groups(cell_block, keyword):
    """Brace-balanced `keyword (...) { ... }` groups inside cell_block."""
    out, i = [], 0
    pat = re.compile(r'\n(\s*)%s\s*\(' % re.escape(keyword))
    while True:
        m = pat.search(cell_block, i)
        if not m:
            break
        ob = cell_block.index('{', m.end())
        end = brace_body(cell_block, ob)
        out.append(cell_block[m.start():end + 1])
        i = end + 1
    return out


def _pin_block(cell_block, pin):
    for pb in _groups(cell_block, 'pin'):
        nm = re.match(r'\s*pin\s*\(\s*"?(\w+)"?', pb)
        if nm and nm.group(1) == pin:
            return pb
    sys.exit('merge: pin %s not found' % pin)


def _cap(cell_block, pin):
    m = re.search(r'\bcapacitance\s*:\s*([0-9.]+)', _pin_block(cell_block, pin))
    return float(m.group(1)) if m else 0.004


def _nums(s):
    return [float(x) for x in NUMRE.findall(s)]


def _lut(group_text):
    """(idx1, idx2, grid) from a lu_table group's index_1/index_2/values."""
    i1 = re.search(r'index_1\s*\(\s*"([^"]+)"', group_text)
    i2 = re.search(r'index_2\s*\(\s*"([^"]+)"', group_text)
    vm = re.search(r'values\s*\((.*?)\)\s*;', group_text, re.S)
    idx1 = _nums(i1.group(1)) if i1 else [0.0]
    idx2 = _nums(i2.group(1)) if i2 else [0.0]
    grid = [_nums(r) for r in re.findall(r'"([^"]*)"', vm.group(1))] if vm else []
    return idx1, idx2, grid


def _arc(cell_block, output_pin, related_pin):
    """The 4 delay/transition tables of the timing arc related_pin -> output_pin."""
    for grp in _groups(_pin_block(cell_block, output_pin), 'timing'):
        rp = re.search(r'related_pin\s*:\s*"?(\w+)"?', grp)
        if rp and rp.group(1) == related_pin:
            out = {}
            for tbl in ('cell_rise', 'cell_fall', 'rise_transition', 'fall_transition'):
                for g in _groups(grp, tbl):
                    out[tbl] = _lut(g)
                    break
            return out
    sys.exit('merge: arc %s->%s not found' % (related_pin, output_pin))


def _bilerp(idx1, idx2, grid, x, y):
    """Bilinear interp on a slew(idx1) x load(idx2) table; clamp + linear-extrapolate at edges."""
    def seg(ax, v):
        if len(ax) == 1:
            return 0, 0.0, 0
        if v <= ax[0]:
            return 0, (v - ax[0]) / (ax[1] - ax[0]), 1
        if v >= ax[-1]:
            return len(ax) - 2, (v - ax[-2]) / (ax[-1] - ax[-2]), len(ax) - 1
        for k in range(len(ax) - 1):
            if ax[k] <= v <= ax[k + 1]:
                return k, (v - ax[k]) / (ax[k + 1] - ax[k]), k + 1
        return len(ax) - 2, 1.0, len(ax) - 1
    i0, fi, i1 = seg(idx1, x)
    j0, fj, j1 = seg(idx2, y)
    v00, v01, v10, v11 = grid[i0][j0], grid[i0][j1], grid[i1][j0], grid[i1][j1]
    return (v00 * (1 - fi) * (1 - fj) + v01 * (1 - fi) * fj +
            v10 * fi * (1 - fj) + v11 * fi * fj)


def _compose(stage1, stage2, cint, gain):
    """Fused arc = stage1 (loaded by cint) then stage2 (loaded by the output load); delays x gain.
    Same-edge composition (rise->rise, fall->fall): a modeling simplification. Delay MAGNITUDES are
    faithful (real foundry table values); exact polarity through the internal node is not tracked."""
    slew = stage1['cell_rise'][0]          # input-slew axis (standard foundry index_1)
    load = stage2['cell_rise'][1]          # output-load axis (standard foundry index_2)
    out = {}
    for edge in ('rise', 'fall'):
        cell, trans = 'cell_' + edge, edge + '_transition'
        dgrid, tgrid = [], []
        for s in slew:
            d1 = _bilerp(*stage1[cell], s, cint)         # stage1 delay at (slew, Cint)
            t1 = _bilerp(*stage1[trans], s, cint)        # stage1 output slew
            drow, trow = [], []
            for l in load:
                d2 = _bilerp(*stage2[cell], t1, l)       # stage2 delay at (stage1 slew, load)
                t2 = _bilerp(*stage2[trans], t1, l)      # stage2 output slew
                drow.append(gain * (d1 + d2))
                trow.append(t2)
            dgrid.append(drow)
            tgrid.append(trow)
        out[cell] = (slew, load, dgrid)
        out[trans] = (slew, load, tgrid)
    return out


def _scale_delay(arc, gain):
    """Direct (single-stage) arc: scale delays x gain, keep transitions."""
    return {k: (i1, i2, [[v * gain for v in row] for row in g]) if k.startswith('cell_')
            else (i1, i2, g) for k, (i1, i2, g) in arc.items()}


def _tmpl_name(cell_block, default='del_1_7_7'):
    """The lu_table_template the BASE cell's delay tables actually use."""
    m = re.search(r'(?:cell_rise|cell_fall)\s*\(\s*"?([A-Za-z0-9_]+)"?\s*\)', cell_block)
    return m.group(1) if m else default


def _emit_table(tbl, idx1, idx2, grid, tmpl='del_1_7_7'):
    rows = (', \\\n' + ' ' * 24).join('"%s"' % ', '.join('%.6f' % v for v in r) for r in grid)
    return ('                %s (%s) {\n'
            '                    index_1("%s");\n'
            '                    index_2("%s");\n'
            '                    values(%s);\n'
            '                }\n'
            % (tbl, tmpl, ', '.join('%.6f' % x for x in idx1),
               ', '.join('%.6f' % x for x in idx2), rows))


def _emit_timing(related_pin, arc, tmpl='del_1_7_7'):
    body = ''.join(_emit_table(t, *arc[t], tmpl=tmpl) for t in
                   ('cell_fall', 'cell_rise', 'fall_transition', 'rise_transition') if t in arc)
    return ('            timing () {\n'
            '                related_pin : "%s";\n'
            '                timing_type : "combinational";\n%s'
            '            }\n' % (related_pin, body))


def merge(args):
    spec = json.load(open(args.spec))
    lib = open(args.base).read()
    c1 = _cell_block(lib, spec['cell1'])
    c2 = _cell_block(lib, spec['cell2'])
    cint = _cap(c2, spec['c2_in'])                       # internal-net load = cell2's input cap
    pg = '\n'.join(_groups(c1, 'pg_pin'))

    inputs, timings = [], []
    for fp, (src, sub) in spec['pins'].items():
        if src == 'cell1':
            arc = _compose(_arc(c1, spec['c1_out'], sub),
                           _arc(c2, spec['output'], spec['c2_in']), cint, args.gain)
            cap = _cap(c1, sub)
        else:
            arc = _scale_delay(_arc(c2, spec['output'], sub), args.gain)
            cap = _cap(c2, sub)
        inputs.append((fp, cap))
        timings.append(_emit_timing(fp, arc))

    pins = ''.join('        pin ("%s") {\n'
                   '            capacitance : %.7f;\n'
                   '            direction : "input";\n'
                   '            max_transition : 1.5000000000;\n'
                   '            related_ground_pin : "VGND";\n'
                   '            related_power_pin : "VPWR";\n'
                   '        }\n' % (fp, cap) for fp, cap in inputs)

    block = ('    cell ("%s") {\n'
             '        area : %g;\n'
             '        cell_leakage_power : 0.0050000000;\n'
             '%s\n'
             '%s'
             '        pin ("%s") {\n'
             '            direction : "output";\n'
             '            function : "%s";\n'
             '            power_down_function : "(!VPWR) + (VGND)";\n'
             '            related_ground_pin : "VGND";\n'
             '            related_power_pin : "VPWR";\n'
             '            max_capacitance : 0.1000000000;\n'
             '%s'
             '        }\n'
             '    }\n'
             % (spec['name'], args.area, pg, pins, spec['output'], spec['function'], ''.join(timings)))

    note = ('composed from %s + %s (2-stage NLDM of real foundry tables) x gain %g'
            % (spec['cell1'], spec['cell2'], args.gain))
    open(args.out, 'w').write(emit(library_header(lib), block, note))
    print('merge: %s = %s -> %s (gain %g, %d inputs) -> %s'
          % (spec['name'], spec['cell1'], spec['cell2'], args.gain, len(inputs), args.out))



def synth(args):
    """Liberty for a SYNTHESISED cell: real pins + real function, base cell only for table shapes."""
    lib = open(args.base).read()
    c = _cell_block(lib, args.base_cell)
    if c is None:
        sys.exit('base cell %s not found in %s' % (args.base_cell, args.base))
    ins = [p.strip() for p in args.input_pins.split(',') if p.strip()]
    if not ins:
        sys.exit('--input-pins is empty')

    # A representative arc from the base cell, replicated per input pin. The base cell may have
    # fewer inputs than this cell, so cycle through whatever arcs it has.
    _out = _base_output(c) or args.output_pin
    base_ins = [m for m in re.findall(r'(?<!pg_)pin\s*\(\s*"?(\w+)"?\s*\)', c)
                if m != _out and m not in ('VDD', 'VSS', 'VPWR', 'VGND', 'VPB', 'VNB')]
    arcs = []
    for bp in base_ins:
        try:
            a = _arc(c, _out, bp)
        except SystemExit:
            continue
        if a:
            arcs.append((bp, a))
    if not arcs:
        sys.exit('no timing arcs found in base cell %s' % args.base_cell)

    pins, timings = '', []
    for i, p in enumerate(ins):
        bp, a = arcs[i % len(arcs)]
        cap = _cap(c, bp)
        pins += ('        pin ("%s") {\n'
                 '            capacitance : %.7f;\n'
                 '            direction : "input";\n'
                 '            max_transition : 1.5000000000;\n'
                 '            related_ground_pin : "%s";\n'
                 '            related_power_pin : "%s";\n'
                 '        }\n' % (p, cap, args.ground_pin, args.power_pin))
        timings.append(_emit_timing(p, _scale_delay(a, args.derate), _tmpl_name(c)))

    pg = '\n'.join(_groups(c, 'pg_pin'))
    block = ('    cell ("%s") {\n'
             '        area : %g;\n'
             '        cell_leakage_power : 0.0050000000;\n'
             '%s\n'
             '%s'
             '        pin ("%s") {\n'
             '            direction : "output";\n'
             '            function : "%s";\n'
             '            power_down_function : "(!%s) + (%s)";\n'
             '            related_ground_pin : "%s";\n'
             '            related_power_pin : "%s";\n'
             '            max_capacitance : 0.1000000000;\n'
             '%s'
             '        }\n'
             '    }\n'
             % (args.name, args.area or 1.0, pg, pins, args.output_pin, args.function,
                args.power_pin, args.ground_pin, args.ground_pin, args.power_pin, ''.join(timings)))
    note = ('SYNTHESISED cell %s: pins/function are the cell\'s OWN; delay tables are %s scaled x%g '
            '(MOCK -- not this cell\'s measured behaviour)' % (args.name, args.base_cell, args.derate))
    open(args.out, 'w').write(emit(library_header(lib), block, note))
    print('synth: %s = %s (%d inputs) from %s x%g -> %s'
          % (args.name, args.function, len(ins), args.base_cell, args.derate, args.out))


def _base_output(cell_block):
    m = re.search(r'pin\s*\(\s*"?(\w+)"?\s*\)\s*\{[^}]*?direction\s*:\s*"?output"?', cell_block, re.S)
    return m.group(1) if m else None

def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest='mode', required=True)

    e = sub.add_parser('enhance')
    e.add_argument('--base', required=True, help='foundry .lib containing the base cell')
    e.add_argument('--base-cell', required=True, help='foundry cell name to start from')
    e.add_argument('--name', required=True, help='output custom cell name')
    e.add_argument('--edge', choices=['rise', 'fall', 'both'], default='both',
                   help='which edge(s) to speed up (default both = a flat delay reduction)')
    e.add_argument('--derate', type=float, default=0.95,
                   help='<1 speeds the edge (default 0.95 = 5%% faster). OPTIMISTIC KNOB -- label loudly.')
    e.add_argument('--area', type=float, help='real cell area from the LEF (um^2)')
    e.add_argument('-o', '--out', required=True)
    e.set_defaults(func=enhance)

    s = sub.add_parser('synth', help='Liberty for a synthesised cell (real pins + real function)')
    s.add_argument('--base', required=True, help='foundry .lib supplying the NLDM table shapes')
    s.add_argument('--base-cell', required=True, help='foundry cell whose arcs are the template')
    s.add_argument('--name', required=True)
    s.add_argument('--function', required=True, help="Liberty function, e.g. '!((A B)+C)'")
    s.add_argument('--input-pins', required=True, help='comma-separated input pin names')
    s.add_argument('--output-pin', default='ZN')
    s.add_argument('--power-pin', default='VPWR', help='VPWR for sky130, VDD for tsmc28')
    s.add_argument('--ground-pin', default='VGND', help='VGND for sky130, VSS for tsmc28')
    s.add_argument('--derate', type=float, default=1.0,
                   help='<1 speeds the arcs. OPTIMISTIC KNOB -- label loudly.')
    s.add_argument('--area', type=float, help='real cell area from the LEF (um^2)')
    s.add_argument('-o', '--out', required=True)
    s.set_defaults(func=synth)

    m = sub.add_parser('merge')
    m.add_argument('--spec', required=True, help='generate/model_specs/*.json fusion spec')
    m.add_argument('--base', required=True, help='foundry .lib containing BOTH constituent cells')
    m.add_argument('--area', type=float, required=True, help='real fused-cell area from the LEF (um^2)')
    m.add_argument('--gain', type=float, default=0.95,
                   help='<1 credits the eliminated inter-cell wire (default 0.95 = 5%% reduction)')
    m.add_argument('-o', '--out', required=True)
    m.set_defaults(func=merge)

    a = ap.parse_args()
    a.func(a)


if __name__ == '__main__':
    main()
