"""Unit tests for the pure-Python parts of the cell factory
(packs/custom-cell-fmax-sky130-demo/flow/toolbox/factory/factory.py).

Run with `python3 -m unittest test/contract/support/cellfmax_factory_test.py`. No EDA tool is needed:
the bool2cmos netlists below are verbatim outputs captured on the linglong server (2026-10-04), and
the expected values are worked out by hand from the Boolean functions and device lists.
"""
import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
FACTORY = REPO / "packs" / "custom-cell-fmax-sky130-demo" / "flow" / "toolbox" / "factory"
spec = importlib.util.spec_from_file_location("cellfactory", FACTORY / "factory.py")
fac = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fac)
_pa_spec = importlib.util.spec_from_file_location("pinaccess_check", FACTORY.parent / "pinaccess" / "check.py")
pa = importlib.util.module_from_spec(_pa_spec)
_pa_spec.loader.exec_module(pa)

NOR3_B2C = """* Generated by bool2cmos (BDD -> series-parallel CMOS, bridge-free)
* function : Y = !(A|B|C)
.subckt NOR3_PU2 A B C Y VGND VNB VPB VPWR
* --- stage Y -> Y ---
X0 Y A n1_i0 VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X1 n1_i0 B n1_i1 VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X2 n1_i1 C VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X3 Y A VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
X4 Y B VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
X5 Y C VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
.ends NOR3_PU2
"""

HA_B2C = """.subckt HA A B S CO VGND VNB VPB VPWR
* --- stage n2 -> n2 ---
X0 n2 A VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X1 n2 B VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X2 n2 A n2_i0 VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
X3 n2_i0 B VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
* --- inverter -> CO ---
X4 CO n2 VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X5 CO n2 VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
* --- stage n4 -> n4 ---
X6 n4 A n4_i1 VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X7 n4_i1 B VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X8 n4 n2 VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X9 n4 A n4_i0 VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
X10 n4 B n4_i0 VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
X11 n4_i0 n2 VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
* --- inverter -> S ---
X12 S n4 VPWR VPB sky130_fd_pr__pfet_01v8_hvt w=1.0 l=0.15
X13 S n4 VGND VNB sky130_fd_pr__nfet_01v8 w=0.65 l=0.15
.ends HA
"""


def cell(name, outputs, inputs=None, variant=None):
    raw = {"name": name, "outputs": outputs}
    if inputs is not None:
        raw["inputs"] = inputs
    if variant is not None:
        raw["variant"] = variant
    return fac.parse_cell(raw)


class ExpressionTest(unittest.TestCase):
    def test_precedence_matches_bool2cmos(self):
        # or < xor < and < not: A^B&C is A^(B&C); A|B^C is A|(B^C)
        t = fac.truth_table(fac.parse_expr("A^B&C"), ["A", "B", "C"])
        self.assertEqual(t, [0, 0, 0, 1, 1, 1, 1, 0])
        t = fac.truth_table(fac.parse_expr("A|B^C"), ["A", "B", "C"])
        self.assertEqual(t, [0, 1, 1, 0, 1, 1, 1, 1])

    def test_juxtaposition_postfix_and_tilde(self):
        self.assertEqual(fac.truth_table(fac.parse_expr("(A1 A2)'"), ["A1", "A2"]), [1, 1, 1, 0])
        self.assertEqual(fac.truth_table(fac.parse_expr("~A+B"), ["A", "B"]), [1, 1, 0, 1])

    def test_parse_errors(self):
        for bad in ("", "A&", "(A|B", "A $ B"):
            with self.assertRaises(fac.SpecError):
                fac.parse_expr(bad)

    def test_symmetric_groups(self):
        self.assertEqual(fac.symmetric_groups(["!(A|B|C)"], ["A", "B", "C"]), [["A", "B", "C"]])
        self.assertEqual(fac.symmetric_groups(["!((A1&A2)|B1)"], ["A1", "A2", "B1"]), [["A1", "A2"]])
        self.assertEqual(fac.symmetric_groups(["!((A0&!S)|(A1&S))"], ["A0", "A1", "S"]), [])
        # multi-output: symmetric only if symmetric in every output
        self.assertEqual(fac.symmetric_groups(["A^B", "A&B"], ["A", "B"]), [["A", "B"]])
        self.assertEqual(fac.symmetric_groups(["A^B", "A&!B"], ["A", "B"]), [])


class SpecTest(unittest.TestCase):
    def test_defaults_and_hash(self):
        c = cell("NOR2_PU2", {"Y": "!(A|B)"}, variant="PU2")
        self.assertEqual(c["inputs"], ["A", "B"])
        self.assertEqual(c["truth"]["Y"], [1, 0, 0, 0])
        self.assertEqual(c["variant"], {"pullup": {"all": 2.0}, "pulldown": {}})
        self.assertEqual(c["specHash"], cell("NOR2_PU2", {"Y": "!(A|B)"}, variant={"pullup": 2})["specHash"])
        self.assertNotEqual(c["specHash"], cell("NOR2_PU2", {"Y": "!(A|B)"}, variant="ND2")["specHash"])

    def test_variant_forms(self):
        self.assertEqual(fac.parse_variant("PU2ND1.5"), {"pullup": {"all": 2.0}, "pulldown": {"all": 1.5}})
        self.assertEqual(fac.parse_variant({"pullup": {"A": 2}}), {"pullup": {"A": 2.0}, "pulldown": {}})
        for bad in ("XX2", "PU", {"pullup": {"A": 20}}, {"pull": 2}, {"pullup": "2"}):
            with self.assertRaises(fac.SpecError):
                fac.parse_variant(bad)

    def test_cell_errors(self):
        cases = [
            {"name": "1BAD", "outputs": {"Y": "!A"}},
            {"name": "C", "outputs": {"Y": "!(A|B)"}, "inputs": ["A"]},          # undeclared B
            {"name": "C", "outputs": {"Y": "!A"}, "inputs": ["A", "B"]},         # unused B
            {"name": "C", "outputs": {"VPWR": "!A"}},                            # reserved pin
            {"name": "C", "outputs": {"A": "!A"}, "inputs": ["A"]},              # pin both ways
            {"name": "C", "outputs": {}},
        ]
        for raw in cases:
            with self.assertRaises(fac.SpecError, msg=json.dumps(raw)):
                fac.parse_cell(raw)

    def test_parse_spec_collects_errors_and_duplicates(self):
        cells, errors, jobs = fac.parse_spec({"jobs": 3, "cells": [
            {"name": "A1", "outputs": {"Y": "!A"}},
            {"name": "A1", "outputs": {"Y": "!A"}},
            {"name": "B1", "outputs": {"Y": "!(A|"}},
        ]})
        self.assertEqual([c["name"] for c in cells], ["A1"])
        self.assertEqual(len(errors), 2)
        self.assertEqual(jobs, 3)

    def test_example_specs_are_valid(self):
        for f in ("nor3_pu2.json", "batch24.json"):
            cells, errors, _ = fac.parse_spec(json.loads((FACTORY / "examples" / f).read_text()))
            self.assertEqual(errors, [], f)
            self.assertTrue(cells)


class SizingTest(unittest.TestCase):
    def setUp(self):
        self.nor3 = fac.parse_b2c_spice(NOR3_B2C)
        self.ha = fac.parse_b2c_spice(HA_B2C)

    def widths(self, net, kind):
        return sorted((d["g"], d["w"]) for d in net["devices"] if d["kind"] == kind)

    def test_parse(self):
        self.assertEqual(self.nor3["pins"], ["A", "B", "C", "Y", "VGND", "VNB", "VPB", "VPWR"])
        self.assertEqual(len(self.nor3["devices"]), 6)
        self.assertEqual(self.nor3["devices"][0]["kind"], "p")

    def test_pu2_doubles_every_pmos_as_fingers(self):
        s = fac.apply_sizing(self.nor3, fac.parse_variant("PU2"))
        self.assertEqual(self.widths(s, "p"), [("A", 1.0), ("A", 1.0), ("B", 1.0), ("B", 1.0), ("C", 1.0), ("C", 1.0)])
        self.assertEqual(self.widths(s, "n"), [("A", 0.65), ("B", 0.65), ("C", 0.65)])
        names = [d["name"] for d in s["devices"]]
        self.assertEqual(len(names), len(set(names)))

    def test_per_input_fractional_and_shrink(self):
        s = fac.apply_sizing(self.nor3, fac.parse_variant({"pullup": {"A": 1.5}, "pulldown": {"all": 0.5}}))
        self.assertEqual(self.widths(s, "p"), [("A", 0.75), ("A", 0.75), ("B", 1.0), ("C", 1.0)])
        # 0.65 * 0.5 = 0.325 < lclayout's 0.42 minimum -> one device clamped to 0.42
        self.assertEqual(self.widths(s, "n"), [("A", 0.42), ("B", 0.42), ("C", 0.42)])

    def test_gate_key_beats_all(self):
        s = fac.apply_sizing(self.nor3, fac.parse_variant({"pulldown": {"all": 2, "B": 1}}))
        self.assertEqual(self.widths(s, "n"), [("A", 0.65), ("A", 0.65), ("B", 0.65), ("C", 0.65), ("C", 0.65)])

    def test_out_key_scales_only_that_stage(self):
        s = fac.apply_sizing(self.ha, fac.parse_variant({"pullup": {"out:S": 2}}))
        pm = [(d["d"], d["g"]) for d in s["devices"] if d["kind"] == "p"]
        self.assertEqual(pm.count(("S", "n4")), 2)            # output inverter of S doubled
        self.assertEqual(pm.count(("CO", "n2")), 1)           # CO inverter untouched
        self.assertEqual(len(pm), 8)

    def test_unknown_key_rejected(self):
        with self.assertRaises(fac.SpecError):
            fac.apply_sizing(self.nor3, fac.parse_variant({"pullup": {"Q": 2}}))

    def test_switch_level_check(self):
        c = cell("NOR3_PU2", {"Y": "!(A|B|C)"}, variant="PU2")
        self.assertIsNone(fac.verify_switch_level(fac.apply_sizing(self.nor3, c["variant"]), c))
        h = cell("HA", {"S": "A^B", "CO": "A&B"}, ["A", "B"])
        self.assertIsNone(fac.verify_switch_level(self.ha, h))
        wrong = cell("HA", {"S": "!(A^B)", "CO": "A&B"}, ["A", "B"])
        self.assertIn("output S wrong", fac.verify_switch_level(self.ha, wrong))

    def test_emitters(self):
        c = cell("NOR3_PU2", {"Y": "!(A|B|C)"}, variant="PU2")
        s = fac.apply_sizing(self.nor3, c["variant"])
        src = fac.emit_source(s, c)
        self.assertIn(".subckt NOR3_PU2 A B C Y VGND VNB VPB VPWR", src)
        self.assertEqual(src.count("sky130_fd_pr__pfet_01v8_hvt w=1 l=0.15"), 6)
        lc = fac.emit_lclayout(s, c)
        self.assertIn(".subckt NOR3_PU2 A B C Y vdd gnd", lc)
        self.assertIn("M2 n1_i0 B n1_i1 vdd pmos w=1u l=0.15u", lc)
        self.assertNotIn("VPWR", lc)
        ref = fac.emit_lvs_ref(s, c)
        self.assertIn("n1_i1 C vdd VPB sky130_fd_pr__pfet_01v8_hvt", ref)
        self.assertIn("Y A gnd VNB sky130_fd_pr__nfet_01v8 w=0.65", ref)


class ToolOutputTest(unittest.TestCase):
    def test_lvs_verdicts(self):
        self.assertEqual(fac.parse_lvs_verdict("x\nFinal result: Circuits match uniquely.\n"), "match")
        self.assertEqual(fac.parse_lvs_verdict("Final result: Top level cell failed pin matching.\n"), "pin-mismatch")
        self.assertEqual(fac.parse_lvs_verdict("Final result: Circuits match uniquely with port errors.\n"),
                         "pin-mismatch")
        self.assertEqual(fac.parse_lvs_verdict("Final result: Netlists do not match.\n"), "mismatch")
        self.assertEqual(fac.parse_lvs_verdict("crash\n"), "unknown")

    def test_drc_report(self):
        xml = ("<report-database><items>"
               "<item><category>'li.5'</category><values/></item>"
               "<item><category>'li.5'</category><values/></item>"
               "<item><category>'m1.2'</category><values/></item>"
               "</items></report-database>")
        with tempfile.TemporaryDirectory() as t:
            p = os.path.join(t, "r.xml")
            Path(p).write_text(xml)
            self.assertEqual(fac.parse_drc_report(p), (3, {"li.5": 2, "m1.2": 1}))
            self.assertEqual(fac.parse_drc_report(os.path.join(t, "none.xml")), (None, {}))

    def test_normalize_extracted(self):
        c = cell("NOR2X", {"Y": "!(A|B)"})
        ext = (".subckt NOR2X GND VDD Y B A\n"
               "X0 Y A a_1_2# w_n15_256# sky130_fd_pr__pfet_01v8_hvt w=1 l=0.15\n"
               "X1 Y A GND VSUBS sky130_fd_pr__nfet_01v8 w=0.65 l=0.15\n"
               "C0 Y VSUBS 0.2f **FLOATING\n.ends\n")
        out, info = fac.normalize_extracted(ext, c)
        self.assertIn(".subckt NOR2X A B Y VGND VNB VPB VPWR", out)
        self.assertIn("X0 Y A a_1_2# VPB sky130_fd_pr__pfet_01v8_hvt", out)
        self.assertIn("X1 Y A VGND VNB", out)
        self.assertIn("C0 Y VNB 0.2f\n", out)
        self.assertEqual(info["nwellNodes"], ["w_n15_256#"])
        self.assertEqual(info["substrateNodes"], ["VSUBS"])
        self.assertEqual(info["missingPorts"], [])
        _, info = fac.normalize_extracted(ext.replace(" B A\n", " A\n"), c)
        self.assertEqual(info["missingPorts"], ["B"])

    def test_failure_classes(self):
        self.assertEqual(fac.classify_failure("drc", json.dumps({"m1.2": 2, "li.5": 1})), "drc:li.5+m1.2")
        self.assertEqual(fac.classify_failure("layout", "timeout rc=..."), "layout:timeout")
        self.assertEqual(fac.classify_failure("lvs", "pin-mismatch: Final result: x"), "lvs:pin-mismatch")
        self.assertEqual(fac.classify_failure("netlist", "bool2cmos rc=2: infeasible"), "netlist:bool2cmos")

    def test_attempt_rank_prefers_clean_then_lvs_then_fewer_drc(self):
        ok = {"ok": True}
        clean = {k: ok for k in ("layout", "postprocess", "extract", "lvs", "lef")}
        clean["drc"] = {"ok": True, "count": 0}
        lvs_ok = dict(clean, drc={"ok": False, "count": 5})
        lvs_bad = dict(clean, lvs={"ok": False}, drc={"ok": True, "count": 0})
        ranks = sorted([fac.attempt_rank(lvs_bad), fac.attempt_rank(clean), fac.attempt_rank(lvs_ok)])
        self.assertEqual(ranks[0], fac.attempt_rank(clean))
        self.assertEqual(ranks[1], fac.attempt_rank(lvs_ok))


class PlanAndDeckTest(unittest.TestCase):
    def test_attempt_plan_interleaves_profiles(self):
        from types import SimpleNamespace
        plan = fac.Env.attempt_plan(SimpleNamespace(attempts=5, profiles=["strict", "relaxed"]))
        self.assertEqual(plan, [("strict", 0), ("relaxed", 0), ("strict", 1), ("relaxed", 1), ("strict", 2)])

    def test_merge_drc_takes_max_per_rule(self):
        count, by = fac.merge_drc({"mr": {"m1.2": 2, "li.5": 1}, "lydrc-feol": {"m1.2": 3, "licon.14": 4}})
        self.assertEqual(by, {"licon.14": 4, "m1.2": 3, "li.5": 1})
        self.assertEqual(count, 8)
        self.assertEqual(fac.merge_drc({"mr": {}, "lydrc-feol": {}}), (0, {}))


class ManifestTest(unittest.TestCase):
    def test_summary_yield(self):
        sts = [
            {"name": "A", "state": "clean", "failureClasses": [],
             "stages": {s: {"ok": True} for s in fac.STAGES}},
            {"name": "B", "state": "layout-not-clean", "failureClasses": ["drc:m1.2"],
             "stages": dict({s: {"ok": True} for s in fac.STAGES}, drc={"ok": False})},
            {"name": "C", "state": "failed", "failureClasses": ["layout:routing"],
             "stages": {"netlist": {"ok": True}, "layout": {"ok": False}}},
        ]
        s = fac.summarize(sts)
        self.assertEqual(s["clean"], 1)
        self.assertEqual(s["cleanYield"], 0.333)
        self.assertEqual(s["stageYield"]["netlist"], {"passed": 3, "of": 3})
        self.assertEqual(s["stageYield"]["layout"], {"passed": 2, "of": 3})
        self.assertEqual(s["stageYield"]["drc"], {"passed": 1, "of": 3})
        self.assertEqual(s["failureClasses"], {"drc:m1.2": ["B"], "layout:routing": ["C"]})
        self.assertEqual(s["states"], {"clean": 1, "layout-not-clean": 1, "failed": 1})


RAW_LEF = """VERSION 5.7 ;
MACRO MO_HA
  CLASS CORE ;
  ORIGIN 0 0 ;
  SIZE 3.5 BY 2.72 ;
  SITE unithd ;
  PIN vdd
   DIRECTION INOUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 0.00000000 2.48000000 3.50000000 2.96000000 ;
    END
  END vdd
  PIN gnd
   DIRECTION INOUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 0.00000000 -0.24000000 3.50000000 0.24000000 ;
    END
  END gnd
  PIN A
   DIRECTION INOUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 0.34000000 1.03000000 0.66000000 1.35000000 ;
    END
  END A
  PIN B
   DIRECTION INOUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 0.84000000 1.03000000 1.16000000 1.35000000 ;
    END
  END B
  PIN S
   DIRECTION INOUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 2.34000000 1.03000000 2.66000000 1.35000000 ;
    END
  END S
  PIN CO
   DIRECTION INOUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 2.84000000 1.03000000 3.16000000 1.35000000 ;
    END
  END CO
  OBS
       LAYER met1 ;
        RECT 0.34000000 1.03000000 0.66000000 1.35000000 ;
        RECT 1.50000000 0.60000000 1.80000000 0.90000000 ;
       LAYER poly ;
        RECT 0.40000000 0.10000000 0.55000000 2.60000000 ;
  END
END MO_HA
END LIBRARY
"""


class LefTest(unittest.TestCase):
    def normalize(self):
        with tempfile.TemporaryDirectory() as t:
            src, mid, out = (os.path.join(t, n) for n in ("in.lef", "mid.lef", "obs"))
            Path(src).write_text(RAW_LEF)
            subprocess.run([sys.executable, str(FACTORY / "fix_lef_sky130hd.py"), src, "--inputs", "A,B",
                            "--output", "S,CO", "--vdd", "vdd", "--gnd", "gnd", "-o", mid],
                           check=True, capture_output=True)
            subprocess.run([sys.executable, str(FACTORY / "fix_lef_obs.py"), mid, "-o", out],
                           check=True, capture_output=True)
            return Path(out, "mid.lef").read_text()

    def test_normalization_multi_output(self):
        text = self.normalize()
        import re
        pins = re.findall(r"^\s*PIN\s+(\S+)", text, re.M)
        self.assertEqual(sorted(pins), ["A", "B", "CO", "S", "VGND", "VNB", "VPB", "VPWR"])
        self.assertRegex(text, r"PIN S\s+DIRECTION OUTPUT ;")
        self.assertRegex(text, r"PIN CO\s+DIRECTION OUTPUT ;")
        self.assertRegex(text, r"PIN A\s+DIRECTION INPUT ;")
        self.assertRegex(text, r"PIN VPWR\s+DIRECTION INOUT ;\s+USE POWER ;")
        self.assertNotIn("LAYER poly", text)                     # poly OBS dropped
        self.assertIn("RECT 1.50000000 0.60000000", text)        # internal OBS kept

    def test_snap_and_augment(self):
        text = fac.snap_lef_width(self.normalize(), 180)           # 3.50 -> 3.68 (8 sites)
        self.assertIn("SIZE 3.680 BY 2.72", text)
        self.assertIn("RECT 0.000 -0.240 3.680 0.240", text)
        self.assertIn("RECT 0.340 1.030 0.660 1.350", text)      # signal pin rects untouched
        by = fac.lef_added_rects({"gap_filled": [{"layer": "68/20", "rect_um": [0.66, 1.1, 0.8, 1.2]}],
                                  "min_area_added": [{"layer": "li1", "rect_um": [2.0, 2.0, 2.2, 2.3]}]})
        self.assertEqual(by, {"met1": [[0.66, 1.1, 0.8, 1.2]], "li1": [[2.0, 2.0, 2.2, 2.3]]})
        out = fac.augment_lef(text, by)
        pin_a = out[out.index("PIN A"):out.index("END A")]
        self.assertIn("RECT 0.660 1.100 0.800 1.200", pin_a)     # touches pin A -> joins pin A
        obs = out[out.index("OBS"):]
        self.assertIn("LAYER li1", obs)
        self.assertIn("RECT 2.000 2.000 2.200 2.300", obs)      # free-standing -> obstruction
        self.assertNotIn("0.660 1.100", obs)

    def test_trim_lef_rects(self):
        lef = ("  PIN Y\n    PORT\n       LAYER met1 ;\n        RECT 0.605 0.365 0.895 0.655 ;\n"
               "       LAYER li1 ;\n        RECT 0.605 0.365 0.895 0.655 ;\n    END\n  END Y\n")
        out = fac.trim_lef_rects(lef, {"met1": [[0.605, 0.36, 0.895, 0.395]]})
        self.assertIn("LAYER met1 ;\n        RECT 0.605 0.395 0.895 0.655 ;", out)
        self.assertIn("LAYER li1 ;\n        RECT 0.605 0.365 0.895 0.655 ;", out)   # other layer untouched
        # a strip that does not span the rect is ignored
        self.assertEqual(fac.trim_lef_rects(lef, {"met1": [[0.7, 0.36, 0.8, 0.395]]}), lef)


# C_NOR2_NDB2 of the 2026-10-04 library (ws-f): pin Y with two met1 rects that the LEF left in OBS
# although they touch Y's port (DRT-0073 on Y), a free-standing met1 OBS rect, and an li1 rect.
NOR2_LEF = """MACRO C_NOR2_NDB2
 CLASS CORE ;
 SIZE 2.300 BY 2.72 ;
 SITE unithd ;
  PIN VPWR
   DIRECTION INOUT ;
   USE POWER ;
    PORT
       LAYER met1 ;
        RECT 0.000 2.480 2.300 2.960 ;
    END
  END VPWR
  PIN Y
   DIRECTION OUTPUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 0.105 0.395 0.395 0.655 ;
        RECT 0.180 0.710 1.320 0.850 ;
    END
  END Y
  PIN A
   DIRECTION INPUT ;
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT 0.355 1.045 0.645 1.335 ;
    END
  END A
 OBS
    LAYER li1 ;
     RECT 0.335 1.025 0.665 1.355 ;
    LAYER met1 ;
     RECT 0.320 0.655 0.395 0.710 ;
     RECT 0.250 0.600 0.320 0.700 ;
     RECT 1.105 2.405 1.395 2.480 ;
 END
END C_NOR2_NDB2
"""


class PinAccessLefTest(unittest.TestCase):
    def test_absorb_pin_obs(self):
        out, moved = fac.absorb_pin_obs(NOR2_LEF)
        self.assertEqual(moved, {"Y": 2})
        pin_y = out[out.index("PIN Y"):out.index("END Y")]
        self.assertIn("RECT 0.320 0.655 0.395 0.710", pin_y)       # touches Y's port edge
        self.assertIn("RECT 0.250 0.600 0.320 0.700", pin_y)       # overlaps Y
        obs = out[out.index(" OBS"):]
        self.assertIn("RECT 1.105 2.405 1.395 2.480", obs)        # touches only the VPWR rail: stays
        self.assertIn("LAYER li1", obs)                             # other layer: stays
        self.assertNotIn("0.320 0.655", obs)
        self.assertEqual(fac.absorb_pin_obs(out), (out, {}))       # idempotent
        self.assertEqual(sorted(pa.parse_lef_macros(out)["C_NOR2_NDB2"]["pins"]), ["A", "VPWR", "Y"])

    def test_absorb_leaves_rect_touching_two_pins(self):
        lef = NOR2_LEF.replace("RECT 0.250 0.600 0.320 0.700", "RECT 0.300 0.850 0.400 1.045")
        out, moved = fac.absorb_pin_obs(lef)
        self.assertEqual(moved, {"Y": 1})
        self.assertIn("RECT 0.300 0.850 0.400 1.045", out[out.index(" OBS"):])

    def test_profiles_and_rank(self):
        self.assertIn("tech_m1_overrides.py", fac.PROFILES["strict-m1"])
        self.assertEqual(fac.DEFAULT_PROFILES.split(",")[:2], ["strict-m1", "relaxed-m1"])
        ok = {k: {"ok": True} for k in fac.STAGES}
        bad_pa = dict(ok, pinaccess={"ok": False, "noAccess": ["A2"]}, drc={"ok": True, "count": 0})
        dirty = dict(ok, drc={"ok": False, "count": 3}, pinaccess={"ok": True})
        self.assertEqual(fac.attempt_rank(ok)[0], 0)
        self.assertEqual(fac.attempt_rank(bad_pa)[0], 1)              # pin access gates clean
        self.assertLess(fac.attempt_rank(bad_pa), fac.attempt_rank(dirty))
        self.assertEqual(fac.classify_failure("pinaccess", "no access point: A2"), "pinaccess:no-access-point")


class PinAccessCheckTest(unittest.TestCase):
    MACROS = {"C": {"size": (1.84, 2.72), "pins": {"A": {"use": "SIGNAL"}, "Y": {"use": "SIGNAL"},
                                                   "VPWR": {"use": "POWER"}}},
              "nb": {"size": (0.92, 2.72), "pins": {"B": {"use": "SIGNAL"}}}}

    def test_parse_and_site(self):
        m = pa.parse_lef_macros(NOR2_LEF)["C_NOR2_NDB2"]
        self.assertEqual(m["size"], (2.3, 2.72))
        self.assertEqual(pa.signal_pins(m), ["Y", "A"])
        self.assertEqual(pa.parse_site("SITE unithd\n  SIZE 0.46 BY 2.72 ;\nEND unithd\n", "unithd"), (0.46, 2.72))

    def test_def_rows_orients_and_skip(self):
        rows = pa.copy_rows(("N", "FS"), True)
        self.assertEqual(pa.copies(rows), ["N0", "FS0", "N1", "FN2", "N3", "FS1", "S2", "FS3"])
        d = pa.build_def(["C"], self.MACROS, "unithd", (0.46, 2.72), skip={"C": {"A"}}, rows_plan=rows,
                         neighbors=["nb"])
        self.assertIn("- C__N0 C + PLACED ( 1840 5440 ) N ;", d)
        self.assertIn("- C__FS0 C + PLACED ( 1840 8160 ) FS ;", d)
        # abutted: foundry | N | FN | N | foundry, no gaps, FS rows on odd rows
        self.assertIn("- nbr1 nb + PLACED ( 1840 10880 ) N ;", d)
        self.assertIn("- C__N1 C + PLACED ( 2760 10880 ) N ;", d)
        self.assertIn("- C__FN2 C + PLACED ( 4600 10880 ) FN ;", d)
        self.assertIn("- nbr2 nb + PLACED ( 8280 10880 ) FN ;", d)
        self.assertIn("- C__S2 C + PLACED ( 4600 13600 ) S ;", d)
        self.assertIn("ROW ROW_5 unithd 0 13600 FS", d)
        self.assertNotIn("C__N0 A )", d)                              # skipped pin: no net
        self.assertIn("( PIN io0 ) ( C__N0 Y )", d)
        self.assertIn("( nbr1 B )", d)                                # neighbours are connected too
        self.assertIn("PLACED ( 150 340 ) N", d)                      # IO on the met3 track

    def test_verdicts(self):
        rows = pa.copy_rows(("N", "FS"), False)
        log = "[ERROR DRT-0073] No access point for C__N0/A (C).\n[ERROR DRT-0073] No access point for nbr1/B (nb).\n"
        self.assertEqual(pa.no_access_pairs({"noAccess": [["C__FS0", "A"]]}, log),
                         {("C", "A", "N0"), ("C", "A", "FS0")})
        done = {"ok": True, "accessPoints": {"C/Y": 6, "C/A": 4},
                "insts": {"C__N0": {"pinAccessIdx": 0, "pins": {"Y": 1, "A": 1}},
                          "C__FS0": {"pinAccessIdx": 1, "pins": {"Y": 1, "A": 1}}}}
        ok = pa.cell_verdict("C", self.MACROS, done, set(), rows)
        self.assertEqual((ok["ok"], ok["uniqueInstances"], ok["pins"]["Y"]["perInstance"]), (True, 2, 3.0))
        weak = pa.cell_verdict("C", self.MACROS, done, set(), rows, min_ap=3)
        self.assertEqual((weak["ok"], weak["error"]), (False, "fewer than 3 access points per instance: A"))
        v = pa.cell_verdict("C", self.MACROS, done, {("A", "N0")}, rows)
        self.assertEqual((v["ok"], v["error"]), (False, "no access point: A"))
        self.assertEqual(v["pins"]["A"], {"accessPoints": 0, "perInstance": 0.0, "byCopy": {"N0": 0, "FS0": None}})
        self.assertEqual(v["pins"]["Y"]["accessPoints"], 6)


class EdgeMarginTest(unittest.TestCase):
    LEF = """MACRO X
 SIZE 1.840 BY 2.72 ;
  PIN VGND
   USE GROUND ;
    PORT
       LAYER met1 ;
        RECT 0.000 -0.240 1.840 0.240 ;
    END
  END VGND
  PIN Y
   USE SIGNAL ;
    PORT
       LAYER met1 ;
        RECT -0.020 1.725 0.270 2.015 ;
    END
  END Y
 OBS
    LAYER li1 ;
     RECT -0.085 0.535 0.415 0.785 ;
     RECT 0.000 -0.085 1.840 0.085 ;
     RECT 1.500 1.000 1.750 1.300 ;
 END
END X
"""

    def test_factory_edge_gate_and_shift(self):
        ev = fac.lef_edge_violations(self.LEF)
        self.assertEqual([(l, r[0]) for l, r in ev], [("met1", -0.02), ("li1", -0.085)])  # rail exempt
        moved = fac.shift_lef_x(self.LEF, 170)
        self.assertIn("SIZE 2.010 BY 2.72", moved)
        self.assertIn("RECT 0.000 -0.240 2.010 0.240", moved)        # rail re-anchored at 0
        self.assertIn("RECT 0.085 0.535 0.585 0.785", moved)
        self.assertIn("RECT 0.150 1.725 0.440 2.015", moved)
        snapped = fac.snap_lef_width(moved, 290)                       # 2.01 -> 2.30 (5 sites)
        self.assertIn("RECT 0.000 -0.240 2.300 0.240", snapped)
        self.assertEqual(fac.lef_edge_violations(snapped), [])
        self.assertEqual(fac.classify_failure("lef", "edge-margin: 2 rect(s) ..."), "lef:edge-margin")

    def test_check_edge_violations(self):
        m = pa.parse_lef_macros(self.LEF)["X"]
        ev = pa.edge_violations(m, {"li1": 0.17, "met1": 0.14})
        self.assertEqual(sorted(l for l, _ in ev), ["li1", "met1"])
        self.assertEqual(pa.edge_violations(m, {"met2": 0.14}), [])


if __name__ == "__main__":
    unittest.main()
