// Exact shared-consumer seam through normal Host/PG task and legacy revision operations; zero model.
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile,cp,rename} from 'node:fs/promises';
import path from 'node:path';
export async function sharedRevisionProof(options:any) {
 const {host,runtime,dependencies,load,home,workspace,packsDir,sitesDir,require}=options;
 const {stringify}=require('yaml'),{loadPack,checkPack}=await load('packs'),{loadSite}=await load('sites'),{newCampaignProposalId,readExecutionContext}=await load('fabric');
 const dir=path.join(packsDir,'shared-facade');for(const part of ['flow','tools','readers','rules','choosers'])await mkdir(path.join(dir,part),{recursive:true});
 const source={values:[{type:'setup_wns',unit:'ns',mode:'setup',scope:'all',value:0.1},{type:'clock_period',unit:'ns',value:10}]};
 await writeFile(path.join(dir,'flow/source.json'),JSON.stringify(source));await writeFile(path.join(dir,'flow/seed.json'),JSON.stringify(source));
 await writeFile(path.join(dir,'flow/probe.py'),`import pathlib,json,sys\np=pathlib.Path(sys.argv[1]);name=sys.argv[2];period=float(sys.argv[3]);source=None if name=='c' else json.loads(p.joinpath('flow/source.json').read_text())['values'][1]['value']\np.joinpath('shared-calls').open('a').write(json.dumps({'name':name,'period':period,'source':source})+'\\n')\np.joinpath(name+'.json').write_text(json.dumps({'values':[{'type':'setup_wns','unit':'ns','mode':'setup','scope':'all','value':0.1},{'type':'clock_period','unit':'ns','value':period}]}))\n`);
 await writeFile(path.join(dir,'tools/read.py'),`import json,pathlib,sys\npathlib.Path(sys.argv[2]).write_text(json.dumps(json.loads(pathlib.Path(sys.argv[1]).read_text())))\n`);
 await writeFile(path.join(dir,'readers/fixture.yml'),stringify({id:'fixture',version:'1',reportKind:'shared',emits:['setup_wns','clock_period'],file:'tools/read.py',argv:['/usr/bin/python3','${READER}','${REPORT}','${OUT}']}));
 for(const [id,type] of [['constraint','setup_wns'],['goal','clock_period']])await writeFile(path.join(dir,`rules/${id}.yml`),stringify({id,version:'1',title:id,...(id==='goal'?{parameter:{name:'periodNs',unit:'ns'}}:{}),requires:[{type,...(id==='constraint'?{mode:'setup',scope:'all'}:{})}],subject:{type,...(id==='constraint'?{mode:'setup',scope:'all'}:{})},predicate:{op:id==='goal'?'lte':'gte',threshold:id==='goal'?{parameter:'periodNs'}:0,unit:'ns'}}));
 await writeFile(path.join(dir,'choosers/fixture.yml'),stringify({id:'fixture',version:'1',title:'Use measured revised period',parameter:{name:'stepNs',unit:'ns'},reads:{period:{type:'clock_period',unit:'ns'}},decide:[{when:{constraint:'PASS',goal:'PASS'},goalMet:true},{when:{constraint:'PASS',goal:'FAIL'},next:{periodNs:{sum:['period',{neg:'stepNs'}]}}}]}));
 const output=(name:string,at:string)=>({name,path:at,reader:'fixture',description:name});
 await writeFile(path.join(dir,'contract.yml'),stringify({id:'shared-facade',version:'1',title:'Actual shared input and Strategy consumers',inputs:[{name:'workspaceRoot'}],outputs:[output('seed','flow/seed.json'),output('source','flow/source.json'),...['a','b','c'].map(id=>output(id,id+'.json'))],goal:{periodNs:{type:'number',unit:'ns',min:0.1,max:10,default:1}},strategy:{periodNs:{type:'number',unit:'ns',min:0.1,max:10,default:2}},words:{periodNs:{label:'Period',unit:'ns'}},tools:[{id:'probe',file:'flow/probe.py',inputs:['FLOW','WORKSPACE','NAME','PERIOD'],argv:['/usr/bin/python3','${FLOW}/probe.py','${WORKSPACE}','${NAME}','${PERIOD}']}],environment:{wrappers:['/usr/bin/python3']},workspace:{source:'pack',copy:['seed.json','source.json','probe.py']}}));
 const nodes:any[]=[{id:'start',kind:'act',parameters:{observes:'seed'}},{id:'c',kind:'act',parameters:{tool:'probe',arguments:{NAME:'c',PERIOD:1}}}];const edges:any[]=[{from:'start',to:'c'},{from:'c',to:'source-a'}];
 for(const id of ['a','b']){nodes.push({id:`source-${id}`,kind:'act',parameters:{observes:'source'}},{id,kind:'act',parameters:{tool:'probe',arguments:{NAME:id,PERIOD:{from:'strategy',name:'periodNs'}}}},{id:`read-${id}`,kind:'act',parameters:{observes:id}});edges.push({from:`source-${id}`,to:id},{from:id,to:`read-${id}`},{from:`read-${id}`,to:id==='a'?'source-b':'judge'});}
 nodes.push({id:'judge',kind:'judge',parameters:{rules:['constraint','goal'],bind:{periodNs:{from:'goal',name:'periodNs'}}}},{id:'choose',kind:'explore',parameters:{chooser:'fixture',bind:{stepNs:0.25}}});edges.push({from:'judge',to:'choose',outcome:'PASS'},{from:'choose',to:'start',revisit:true});
 await writeFile(path.join(dir,'graph.yml'),stringify({id:'shared-facade',version:'1',entry:'start',nodes,edges}));
 const pack=loadPack(packsDir,'shared-facade'),site=loadSite(sitesDir,'local');assert.equal(checkPack(pack,site).fit,true,JSON.stringify(checkPack(pack,site)));
 const owner=await options.createRootAgent(host.ctx,workspace),actor=String(owner.id),admit=runtime.store.claimEffectDispatch.bind(runtime.store);let blocked=false,signal:any,release:any;const boundary=new Promise(resolve=>signal=resolve),gate=new Promise<void>(resolve=>release=resolve);
 runtime.store.claimEffectDispatch=async(admission:any,permit:any,dispatchId:string,inputSha:string)=>{const effect=await runtime.store.effect(admission.effectId);if(!blocked&&effect?.identity.taskId==='a'){blocked=true;signal(effect.identity);await gate;}return admit(admission,permit,dispatchId,inputSha);};
 const started=await host.ctx.hima.startRun({pack:pack.id,site:'local',goal:{periodNs:1},ownerSessionId:actor,proposalId:newCampaignProposalId(pack,site),generationLimit:2});const selected:any=await Promise.race([boundary,new Promise((_,reject)=>setTimeout(async()=>reject(new Error('Shared actual submit boundary not reached: '+JSON.stringify(await readExecutionContext(dependencies,started.run.id)))),10000))]);
 const before=await readExecutionContext(dependencies,started.run.id);const paused=await host.ctx.hima.executionAction({runId:started.run.id,actor,origin:'human',expectedEpoch:before.run.control.epoch,expectedRevision:before.run.control.revision,requestId:'shared-human-hold',action:'pause'});assert.equal(paused.kind,'accepted');
 const until=Date.now()+5000;let initial:any[]=[];for(;;){initial=await runtime.store.flowInvocations(started.run.id);if(['a','c'].every(id=>initial.some(inv=>inv.identity.taskId===id)))break;if(Date.now()>until)throw new Error('Shared original invocations did not reach the normal fork');await new Promise(resolve=>setTimeout(resolve,25));}
 const control=paused.context.run.control,act=(id:string,revision:any)=>host.ctx.hima.executionAction({runId:started.run.id,actor,expectedEpoch:control.epoch,expectedRevision:control.revision,requestId:id,action:'revise',revision});
 const under={revisionId:'understated-strategy',reason:'Change the shared period',changedNodes:['a'],affectedNodes:['a','read-a','judge','choose'],strategy:{periodNs:3},changes:[]};const refusal=await act('understated-strategy',under);assert.equal(refusal.kind,'refused');assert.match(refusal.reason,/dependency closure.*b/);
 const file=path.join(started.workspace,'flow/source.json'),original=await readFile(file,'utf8'),content=JSON.stringify({...source,values:[source.values[0],{...source.values[1],value:20}]});
 const wrong=await act('false-input-owner',{revisionId:'false-input-owner',reason:'Do not misattribute shared inputs',changedNodes:['judge'],changes:[{nodeId:'judge',scope:'workspace',path:'flow/source.json',content}]});assert.equal(wrong.kind,'refused');assert.match(wrong.reason,/not owned by claimed node judge/);assert.equal(await readFile(file,'utf8'),original);
 const sharedRefusal=await act('understated-input',{revisionId:'understated-input',reason:'Shared dependency check',changedNodes:['source-a'],affectedNodes:['source-a','a','read-a','judge','choose'],changes:[{nodeId:'source-a',scope:'workspace',path:'flow/source.json',content}]});assert.equal(sharedRefusal.kind,'refused');assert.match(sharedRefusal.reason,/dependency closure.*source-b/);assert.equal(await readFile(file,'utf8'),original);
 const updated=await act('actual-shared-strategy',{revisionId:'actual-shared-strategy',reason:'Both declared consumers use reviewed period3',changedNodes:['a'],strategy:{periodNs:3},changes:[]});assert.equal(updated.kind,'accepted',updated.reason);release();
 const changed=await readExecutionContext(dependencies,started.run.id);const continued=await host.ctx.hima.executionAction({runId:started.run.id,actor,origin:'human',expectedEpoch:changed.run.control.epoch,expectedRevision:changed.run.control.revision,requestId:'shared-human-continue',action:'continue'});assert.equal(continued.kind,'accepted');
 const complete=await options.untilComplete(dependencies,started.run.id),facts=await runtime.store.flowFact(started.run.id,'outcome:1');
 const calls=(await readFile(path.join(started.workspace,'shared-calls'),'utf8')).trim().split('\n').map(line=>JSON.parse(line));for(const id of ['a','b']){assert.ok(calls.some(call=>call.name===id&&call.period===3),JSON.stringify(calls));assert.ok(calls.some(call=>call.name===id&&call.period===2.75),'Future carry follows actual revised chooser2.75 '+JSON.stringify(calls));}assert.equal(calls.filter(call=>call.name==='c').length,2,'Unchanged valid task retained; only original + genuine next loop calls');
 assert.equal(facts.committed.choose.value.strategy.periodNs,2.5,'Next actual chooser continues from future2.75 rather than persistent3 override');
 runtime.store.claimEffectDispatch=admit;
 // A second ordinary Run proves shared workspace bytes applied once before every actual consumer.
 const forkDir=path.join(packsDir,'shared-fork');await cp(dir,forkDir,{recursive:true});const forkContract=require('yaml').parse(await readFile(path.join(forkDir,'contract.yml'),'utf8'));forkContract.id='shared-fork';await writeFile(path.join(forkDir,'contract.yml'),stringify(forkContract));
 const forkNodes=[...nodes.filter(node=>node.id!=='choose'),{id:'read-c',kind:'act',parameters:{observes:'c'}}],forkEdges=[{from:'start',to:'c'},{from:'start',to:'source-a'},{from:'start',to:'source-b'},{from:'c',to:'read-c'},{from:'read-c',to:'judge'},...['a','b'].flatMap(id=>[{from:`source-${id}`,to:id},{from:id,to:`read-${id}`},{from:`read-${id}`,to:'judge'}])];await writeFile(path.join(forkDir,'graph.yml'),stringify({id:'shared-fork',version:'1',entry:'start',nodes:forkNodes,edges:forkEdges}));
 let originalWriter:any,originalRelease:any;const originalGate=new Promise<void>(resolve=>originalRelease=resolve),originalBoundary=new Promise(resolve=>{if(options.faultAfterAcceptance){runtime.store.claimEffectDispatch=async(admission:any,permit:any,dispatchId:string,inputSha:string)=>{const effect=await runtime.store.effect(admission.effectId);if(!originalWriter&&effect?.identity.taskId==='a'){originalWriter=effect.identity;resolve(effect.identity);await originalGate;}return admit(admission,permit,dispatchId,inputSha);};}});
 const inputRun=await host.ctx.hima.startRun({pack:'shared-fork',site:'local',goal:{periodNs:1},ownerSessionId:actor,generationLimit:1});if(options.faultAfterAcceptance){await originalBoundary;const beforeFault=Date.now()+10000;for(;;){const tasks=(await runtime.store.flowProjection(inputRun.run.id)).tasks;if(['read-b','read-c'].every(id=>tasks.some((task:any)=>task.identity.taskId===id&&task.result)))break;if(Date.now()>beforeFault)throw new Error('Unaffected actual sibling Reader frontier did not finish before the isolated Site fault');await new Promise(resolve=>setTimeout(resolve,25));}}else await options.untilComplete(dependencies,inputRun.run.id);
 const at=path.join(inputRun.workspace,'flow/source.json'),previousBytes=await readFile(at,'utf8'),view=await readExecutionContext(dependencies,inputRun.run.id);
 let heldWriter=false,writerSignal:any,writerRelease:any;const writerBoundary=new Promise(resolve=>writerSignal=resolve),writerGate=new Promise<void>(resolve=>writerRelease=resolve);const actualWorkspaceAdmission=runtime.store.assertEffectAdmission.bind(runtime.store);
 runtime.store.assertEffectAdmission=async(admission:any,permit:any)=>{const effect=await runtime.store.effect(admission.effectId);if(!heldWriter&&effect?.identity.taskId==='hima.apply-revision-input'){heldWriter=true;writerSignal(effect.identity);await writerGate;}return actualWorkspaceAdmission(admission,permit);};
 let siteHidden=false;const siteFile=path.join(sitesDir,'local.yml'),hiddenSite=siteFile+'.accepted-unavailable',actualCommand=runtime.store.command.bind(runtime.store);if(options.faultAfterAcceptance)runtime.store.command=async(command:any)=>{const receipt=await actualCommand(command);if(command.commandId==='actual-shared-input'&&!siteHidden){siteHidden=true;await rename(siteFile,hiddenSite);originalRelease();}return receipt;};
 const mutation=await host.ctx.hima.executionAction({runId:inputRun.run.id,actor,expectedEpoch:view.run.control.epoch,expectedRevision:view.run.control.revision,requestId:'actual-shared-input',action:'revise',revision:{revisionId:'actual-shared-input',reason:'Every declared consumer reads the reviewed shared input20',changedNodes:['source-a'],changes:[{nodeId:'source-a',scope:'workspace',path:'flow/source.json',content}]}});assert.equal(mutation.kind,'accepted',mutation.reason);if(options.faultAfterAcceptance){const cutoff=Date.now()+7000;for(;;){const stopped=await runtime.store.flowFact(inputRun.run.id,'stopped:'+originalWriter.effectId),invocations=await runtime.store.flowInvocations(inputRun.run.id);if(stopped&&invocations.some((inv:any)=>inv.version===1))break;if(Date.now()>cutoff)throw new Error('Accepted revision did not independently close original work and start waiting replacements while Site was unavailable: '+JSON.stringify({view:await readExecutionContext(dependencies,inputRun.run.id),originalWriter,stopped}));await new Promise(resolve=>setTimeout(resolve,50));}assert.equal(await runtime.store.flowFact(inputRun.run.id,'prepared-revision:actual-shared-input'),null);assert.equal(await readFile(at,'utf8'),previousBytes);
 if(options.crashAfterAcceptance){
   const {DBOS}=require('@dbos-inc/dbos-sdk'),canonical=await runtime.store.flowFact(inputRun.run.id,'facade-command:actual-shared-input'),workflowId=canonical.command.change.evidence.workflowId;
   const persistedBefore=Date.now()+5000;let steps:any[]=[];for(;;){steps=await DBOS.listWorkflowSteps(workflowId)??[];if(steps.some((step:any)=>step.name==='hima.revision.retain-immutable-byte-versions'&&typeof step.output?.reason==='string'))break;if(Date.now()>persistedBefore)throw new Error('Unavailable Site revision did not retain a failed materialization receipt before Host death');await new Promise(resolve=>setTimeout(resolve,25));}
   const current=await runtime.store.run(inputRun.run.id),projection=await runtime.store.flowProjection(inputRun.run.id),c=projection.tasks.find((task:any)=>task.identity.taskId==='c');assert.ok(c?.result);
   await writeFile(path.join(home,'revision-replay.json'),JSON.stringify({runId:inputRun.run.id,workspace:inputRun.workspace,source:at,previousBytes,content,canonical,workflowId,applicationVersion:runtime.applicationVersion,deadlineAt:current.deadlineAt,owner:current.owner,epoch:current.epoch,revision:current.revision,originalWriter,cEffectId:c.identity.effectId,steps}));
   await writeFile(path.join(home,'accepted.json'),JSON.stringify({runId:inputRun.run.id,workspace:inputRun.workspace,owner:current.owner}));
   process.send!({stage:'accepted-revision-unavailable',runId:inputRun.run.id,workflowId,hiddenSite,siteFile,applicationVersion:runtime.applicationVersion});await new Promise(()=>{});
 }
 await rename(hiddenSite,siteFile);runtime.store.command=actualCommand;runtime.store.claimEffectDispatch=admit;}await Promise.race([writerBoundary,new Promise((_,reject)=>setTimeout(async()=>reject(new Error('Single shared writer did not reach actual admitted write boundary: '+JSON.stringify(await readExecutionContext(dependencies,inputRun.run.id)))),10000))]);
 const waiting=await readExecutionContext(dependencies,inputRun.run.id);const beta=(waiting.durable.tasks as any[]).find(task=>task.identity.taskId==='source-b'&&task.version===1);assert.ok(beta,'Replacement parallel consumer B is genuinely recorded before owning write');assert.equal(beta.result,null);assert.equal(waiting.durable.effects.some((effect:any)=>effect.identity.effectId===beta.identity.effectId&&effect.dispatches.some((dispatch:any)=>dispatch.dispatchId==='submit')),false,'B cannot submit before the shared inputs-ready handoff');assert.equal(await readFile(at,'utf8'),previousBytes,'Shared input is still original at the held actual writer boundary');let sourceWrites=0;const {LocalChannel}=await load('channel'),originalExec=LocalChannel.prototype.exec;LocalChannel.prototype.exec=async function(argv:any,execOptions:any){const result=await originalExec.call(this,argv,execOptions);if(argv[0]==='tee'&&argv.at(-1)===at){sourceWrites++;if(sourceWrites===1)throw new Error('Injected missing acknowledgement after actual shared source write');}return result;};writerRelease();await options.untilComplete(dependencies,inputRun.run.id);runtime.store.assertEffectAdmission=actualWorkspaceAdmission;LocalChannel.prototype.exec=originalExec;assert.equal(sourceWrites,1,'Absent write acknowledgement reconciles exact after hash without repeating the source tee');
 const inputCalls=(await readFile(path.join(inputRun.workspace,'shared-calls'),'utf8')).trim().split('\n').map(line=>JSON.parse(line));for(const id of ['a','b'])assert.equal(inputCalls.filter(call=>call.name===id).at(-1).source,20,JSON.stringify({calls:inputCalls,tasks:(await runtime.store.flowProjection(inputRun.run.id)).tasks.map((task:any)=>({taskId:task.identity.taskId,version:task.version,valid:task.valid,state:task.state})),outcome:await runtime.store.flowFact(inputRun.run.id,'outcome:1')}));assert.equal(inputCalls.filter(call=>call.name==='c').length,1,'Shared input patch preserves unrelated actual task');
 const command=await runtime.store.flowFact(inputRun.run.id,'facade-command:actual-shared-input');assert.deepEqual(command.command.change.inputPatches.map((patch:any)=>patch.taskId).sort(),['source-a','a','read-a','source-b','b','read-b','judge'].sort(),'Every exact declared workspace consumer gets the selected-occurrence frontier even before its original invocation exists');assert.ok(command.command.change.inputPatches.every((patch:any)=>Object.keys(patch.fields).length===0),'Workspace recomputation does not change scalar business input');
 const ready=await runtime.store.flowFact(inputRun.run.id,'prepared-revision:actual-shared-input');assert.ok(ready.workspaceApplied?.identity);assert.equal(await readFile(ready.assets[0].beforeVersionPath,'utf8'),previousBytes);assert.equal(await readFile(at,'utf8'),content);
 return {ok:true,sharedStrategyArgs:[3,2.75],chooserNext:2.5,sharedInput:20,unrelatedSiblingPreserved:true};
}

/** Same Home and byte-identical runtime resume the originally receipted revision workflow. */
export async function sharedRevisionReplayProof(options:any){
 const {runtime,dependencies,home,load,require}=options,state=JSON.parse(await readFile(path.join(home,'revision-replay.json'),'utf8'));
 const {jsonDigest}=await load('run-store'),{DBOS}=require('@dbos-inc/dbos-sdk');assert.equal(runtime.applicationVersion,state.applicationVersion);
 const complete=await options.untilComplete(dependencies,state.runId),current=await runtime.store.run(state.runId),canonical=await runtime.store.flowFact(state.runId,'facade-command:actual-shared-input');
 assert.equal(current.revision,state.revision);assert.equal(current.epoch,state.epoch);assert.equal(current.owner,state.owner);assert.equal(current.deadlineAt,state.deadlineAt);assert.equal(jsonDigest(canonical),jsonDigest(state.canonical),'Original accepted command and intent remain byte-identical');
 const prepared=await DBOS.getWorkflowStatus(state.workflowId);assert.equal(prepared?.status,'SUCCESS',JSON.stringify(prepared));
 const ready=await runtime.store.flowFact(state.runId,'prepared-revision:actual-shared-input');assert.equal(ready.revision,state.revision);assert.equal(ready.commandDigest,jsonDigest(state.canonical.command));assert.ok(ready.workspaceApplied?.identity);
 const counts=await runtime.store.transaction(async(client:any)=>({commands:(await client.query('SELECT count(*)::int AS n FROM hima.commands WHERE run_id=$1 AND command_id=$2',[state.runId,'actual-shared-input'])).rows[0].n,ready:(await client.query('SELECT count(*)::int AS n FROM hima.flow_facts WHERE run_id=$1 AND name=$2',[state.runId,'prepared-revision:actual-shared-input'])).rows[0].n}),'hima.test.replayed-revision-counts');assert.deepEqual(counts,{commands:1,ready:1});
 const writers=complete.durable.effects.filter((effect:any)=>effect.identity.taskId==='hima.apply-revision-input');assert.equal(writers.length,1);assert.equal(writers[0].identity.effectId,ready.workspaceApplied.identity.effectId);
 const writes=(await readFile(path.join(home,'revision-source-writes.jsonl'),'utf8')).trim().split('\n').map((line:string)=>JSON.parse(line));assert.equal(writes.length,1,'Actual restarted Host applies shared source with one tee');assert.equal(writes[0].path,state.source);
 const calls=(await readFile(path.join(state.workspace,'shared-calls'),'utf8')).trim().split('\n').map((line:string)=>JSON.parse(line));for(const id of ['a','b'])assert.equal(calls.filter((call:any)=>call.name===id).at(-1).source,20);assert.equal(calls.filter((call:any)=>call.name==='c').length,1);
 const c=complete.durable.tasks.find((task:any)=>task.identity.taskId==='c'&&task.valid);assert.equal(c.identity.effectId,state.cEffectId,'Unchanged C keeps its original effect/result across real Host restart');assert.equal(await readFile(ready.assets[0].beforeVersionPath,'utf8'),state.previousBytes);assert.equal(await readFile(state.source,'utf8'),state.content);
 const errors=await DBOS.listWorkflows({status:'ERROR'});assert.equal(errors.length,0,'Successful projection cannot hide any failed original/replayed workflow');
 const after=await DBOS.listWorkflowSteps(state.workflowId);assert.deepEqual(JSON.parse(JSON.stringify(after?.filter((step:any)=>state.steps.some((before:any)=>before.functionID===step.functionID)))),state.steps,'Original receipted Step names, IDs and outputs retain their exact prefix across replay');const evidence={ok:true,runId:state.runId,workflowId:state.workflowId,applicationVersion:runtime.applicationVersion,counts,workspaceWriters:writers.length,sourceWrites:writes.length,unchangedCEffectId:c.identity.effectId,originalResourceClosed:!!await runtime.store.flowFact(state.runId,'stopped:'+state.originalWriter.effectId),errorWorkflows:errors.length,beforeSteps:state.steps,afterSteps:after};
 await writeFile(path.join(options.repoRoot,'.hima-tmp/dbos-migration/u6-review-fixes/facade-revision-replay-evidence.json'),JSON.stringify(evidence,null,2));
 return {ok:true,runId:state.runId,workflowId:state.workflowId,applicationVersion:runtime.applicationVersion,commandCount:counts.commands,readyCount:counts.ready,sourceWrites:writes.length,workspaceWriters:writers.length,unchangedC:true,errorWorkflows:errors.length};
}
