import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';

// The libinsight-analysis Pack's fixed insight page template. Its one executable script is run here
// with no document: it must only expose its pure functions (score and the action files) and not boot.
const templatePath = new URL('../../../packs/libinsight-analysis/page/insight-page.html', import.meta.url);
const template = readFileSync(templatePath, 'utf8');
const scripts = [...template.matchAll(/<script>([\s\S]*?)<\/script>/gu)];

type File = { name: string; text: string; lines?: number };
type Part = { key: string; name: string; weight: number; share: number; value: number | null; lost: number; rules: { index: number; id: string; points: number }[] };
interface Insight {
  score(rules: unknown[]): { overall: number | null; parts: Part[]; none: { index: number; id: string }[] };
  points(score: unknown): number;
  files: {
    derateSdc(rule: unknown, variant?: string | null): File;
    roadmapGapsCsv(rule: unknown): File;
    dontUseTcl(rule: unknown, marks: Record<string, string[]>): File;
    recharacteriseCsv(rule: unknown): File;
    redesignBrief(rule: unknown, item: unknown): File;
  };
}

const context = vm.createContext({});
vm.runInContext(scripts[0]![1]!, context);
const INSIGHT = (context as { INSIGHT: Insight }).INSIGHT;
const plain = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const near = (actual: number | null, expected: number) => assert.ok(actual !== null && Math.abs(actual - expected) < 1e-9, `${String(actual)} != ${expected}`);
const rule = (id: string, dimension: string, affected: number, checked: number, weight: number) => ({ id, title: id, score: { dimension, affected, checked, weight } });

test('the template holds one data marker and one bare script that runs without a document', () => {
  assert.equal(template.split('/*INSIGHT-DATA*/').length, 2);
  assert.equal(scripts.length, 1);
  assert.ok(template.includes('<script type="application/json" id="insight-data">/*INSIGHT-DATA*/</script>'));
  assert.ok(INSIGHT && typeof INSIGHT.score === 'function');
  for (const banned of ['eval(', 'new Function', 'fetch(', 'XMLHttpRequest', 'onclick="']) assert.ok(!scripts[0]![1]!.includes(banned), banned);
});

test('score: the worked example, 50/30/20 over three scored parts', () => {
  const result = INSIGHT.score([
    rule('spikes', 'quality', 30, 1000, 6), // 3 % of 5 % → 0.6 × 6 = 3.6
    rule('gaps', 'ppa', 10, 400, 4), // 2.5 % → 0.5 × 4 = 2
    rule('vmin', 'robustness', 100, 1000, 6), // 10 % → capped at the full weight 6
  ]);
  const [quality, ppa, robustness] = result.parts;
  near(quality!.value, 96.4); near(ppa!.value, 98); near(robustness!.value, 94);
  near(result.overall, 0.5 * 96.4 + 0.3 * 98 + 0.2 * 94);
  near(result.overall, 96.4);
  assert.deepEqual(plain(quality!.rules.map(r => [r.id, Math.round(r.points * 10) / 10])), [['spikes', 3.6]]);
  near(INSIGHT.points({ dimension: 'ppa', affected: 0, checked: 0, weight: 6 }), 0);
});

test('score: dimension none never counts and a part without rules is not scored', () => {
  const withNone = INSIGHT.score([rule('spikes', 'quality', 30, 1000, 6), rule('gaps', 'ppa', 10, 400, 4), rule('path', 'none', 100, 100, 30)]);
  assert.deepEqual(plain(withNone.none.map(r => [r.index, r.id])), [[2, 'path']]);
  const robustness = withNone.parts.find(p => p.key === 'robustness')!;
  assert.equal(robustness.value, null, 'not scored');
  assert.equal(robustness.rules.length, 0);
  // renormalised over Quality and PPA: (0.5 × 96.4 + 0.3 × 98) / 0.8
  near(withNone.overall, (0.5 * 96.4 + 0.3 * 98) / 0.8);
  near(withNone.overall, 97);
  near(withNone.parts[0]!.share, 0.625);
  const onlyNone = INSIGHT.score([rule('path', 'none', 5, 10, 6)]);
  assert.equal(onlyNone.overall, null);
  assert.ok(onlyNone.parts.every(p => p.value === null));
});

test('score: a part floors at 0 and checked = 0 costs nothing', () => {
  const result = INSIGHT.score([1, 2, 3, 4, 5].map(i => rule(`q${i}`, 'quality', 50, 100, 30)).concat([rule('zero', 'ppa', 0, 0, 30)]));
  assert.equal(result.parts[0]!.value, 0);
  assert.equal(result.parts[1]!.value, 100);
  near(result.overall, (0.5 * 0 + 0.3 * 100) / 0.8);
});

const vmin = {
  id: 'vmin_bottleneck', hi: 0.8,
  items: [{ name: 'NOR3X1_6T_HVT', label: 'NOR3X1 HVT', v: '6T-HVT', x: 16 }, { name: 'INVX1_8T_SVT', label: 'INVX1 SVT', v: '8T-SVT', x: 5.04 }],
};

test('vmin derate .sdc: one late derate per flagged cell, 1 + x/100 at 2 decimals, variant filter applies', () => {
  assert.deepEqual(plain(INSIGHT.files.derateSdc(vmin, null)), { name: 'derate_low_voltage.sdc', text: [
    '# derate_low_voltage.sdc - generated by vmin_bottleneck',
    '# use for runs below 0.8 V; one late derate per flagged cell',
    'set_timing_derate -late 1.16 [get_lib_cells */NOR3X1_6T_HVT]',
    'set_timing_derate -late 1.05 [get_lib_cells */INVX1_8T_SVT]', ''].join('\n') });
  assert.equal(INSIGHT.files.derateSdc(vmin, '8T-SVT').text, [
    '# derate_low_voltage.sdc - generated by vmin_bottleneck',
    '# use for runs below 0.8 V; one late derate per flagged cell in 8T-SVT',
    'set_timing_derate -late 1.05 [get_lib_cells */INVX1_8T_SVT]', ''].join('\n'));
});

test('gaps roadmap_gaps.csv: the fixed header, one row per gap, quoted when a field holds a comma', () => {
  const gaps = { id: 'size_coverage_gaps', items: [
    { cls: 'NAND2', v: '6T-SVT', lo: { name: 'NAND2X1_6T_SVT' }, hi: { name: 'NAND2X4_6T_SVT' }, ratio: 2.5, miss: { drive: 2, area: 1.234 } },
    { cls: 'AO,I21', v: '8T-HVT', lo: { name: 'AOI21X1' }, hi: { name: 'AOI21X3' }, ratio: 2.111, miss: { drive: 1.7, area: 0.9 } },
  ] };
  assert.deepEqual(plain(INSIGHT.files.roadmapGapsCsv(gaps)), { name: 'roadmap_gaps.csv', text: [
    'function,variant,below,above,jump,suggested_drive,suggested_area',
    'NAND2,6T-SVT,NAND2X1_6T_SVT,NAND2X4_6T_SVT,2.50,2.00,1.23',
    '"AO,I21",8T-HVT,AOI21X1,AOI21X3,2.11,1.70,0.90', ''].join('\n') });
});

test('spike recharacterise.csv: the fixed header and one row per flagged table point', () => {
  const spike = { id: 'table_spikes_kinks', items: [
    { v: '8T-HVT', corner: 'slow 0.70 V', name: 'DFFRX1_8T_HVT', arc: 'CDN→Q', when: '!SE', kind: 'fall_transition', label_pos: 'slew 500 ps × load 14 fF' },
    { v: '6T-SVT', corner: 'slow 0.70 V', name: 'MUXX1_6T_SVT', arc: 'S→Z', when: '', kind: 'rise_transition', label_pos: 'slew 80 ps × load 2 fF' },
  ] };
  assert.deepEqual(plain(INSIGHT.files.recharacteriseCsv(spike)), { name: 'recharacterise.csv', text: [
    'variant,corner,cell,arc,when,table,point',
    '8T-HVT,slow 0.70 V,DFFRX1_8T_HVT,CDN→Q,!SE,fall_transition,slew 500 ps × load 14 fF',
    '6T-SVT,slow 0.70 V,MUXX1_6T_SVT,S→Z,,rise_transition,slew 80 ps × load 2 fF', ''].join('\n') });
});

test('path dont_use_critical.tcl: built from the ticks, grouped by class, regenerated as they change', () => {
  const path = { id: 'critical_path_faster_cells', design: { name: 'demo_top' }, paths: [{ rows: [
    { cell: 'NAND2X1_SVT', cls: 'NAND2' }, { cell: 'INVX2_SVT', cls: 'INV' }, { cell: 'NAND2X2_SVT', cls: 'NAND2' },
  ] }] };
  const head = ['# dont_use_critical.tcl - generated by critical_path_faster_cells for design demo_top', '# scope: the setup-repair step only, then reset_dont_use'];
  assert.deepEqual(plain(INSIGHT.files.dontUseTcl(path, {})), { name: 'dont_use_critical.tcl', lines: 0,
    text: [...head, '# no cells marked yet: mark slower cells on the page to add them here', ''].join('\n') });
  const marks: Record<string, string[]> = { '0:0': ['NAND2X2_HVT', 'NAND2X1_HVT'], '0:2': ['NAND2X1_HVT', 'NAND2X1_SVT'], '0:1': [] };
  const first = INSIGHT.files.dontUseTcl(path, marks);
  assert.equal(first.lines, 2);
  assert.equal(first.text, [...head,
    '# NAND2: keep NAND2X1_SVT, NAND2X2_SVT and faster; drop 2 slower',
    'set_dont_use [get_lib_cells */NAND2X1_HVT]',
    'set_dont_use [get_lib_cells */NAND2X2_HVT]', ''].join('\n'), 'a cell in use in its class is never dropped');
  marks['0:1'] = ['INVX2_HVT'];
  marks['0:0'] = ['NAND2X2_HVT'];
  marks['0:2'] = [];
  assert.equal(INSIGHT.files.dontUseTcl(path, marks).text, [...head,
    '# INV: keep INVX2_SVT and faster; drop 1 slower',
    'set_dont_use [get_lib_cells */INVX2_HVT]',
    '# NAND2: keep NAND2X1_SVT and faster; drop 1 slower',
    'set_dont_use [get_lib_cells */NAND2X2_HVT]', ''].join('\n'));
});

const brief = {
  cell: 'NOR3X1_6T_HVT', arc: 'A2→ZN fall', symptom: 'The falling output slows more than the inverter.',
  now: 16, target: 5, unit: '% extra slowdown', compare: 'the reference inverter',
  where: 'Pull-down stack MN1–MN3; A2 drives MN2.',
  levers: [{ change: 'Widen MN1–MN3 by 30 %', effect: 'about −7 % extra slowdown' }, { change: 'Move A2 next to VSS', effect: 'qualitative' }],
  cost: [['Area', '+6 %'], ['Input capacitance on A2', 0.125]],
  check: 'Re-characterise A2→ZN fall at 0.7 V; re-run the rule; pass below +5 %.',
};

test('vmin redesign brief: five parts in order, with the netlist location', () => {
  const item = { name: 'NOR3X1_6T_HVT', label: 'NOR3X1 HVT', v: '6T-HVT', brief };
  assert.deepEqual(plain(INSIGHT.files.redesignBrief(vmin, item)), { name: 'redesign_NOR3X1_6T_HVT.md', text: [
    '# Redesign brief: NOR3X1_6T_HVT, A2→ZN fall', '',
    'For the cell designer. Generated by vmin_bottleneck from NOR3X1 HVT (6T-HVT).', '',
    '## What is wrong', '', 'The falling output slows more than the inverter.', '',
    '- Now: 16 % extra slowdown', '- Target: 5 % extra slowdown', '- Compared with: the reference inverter', '',
    '## Where in the circuit', '', 'Pull-down stack MN1–MN3; A2 drives MN2.', '',
    '## What to change', '', '1. Widen MN1–MN3 by 30 % - expected effect: about −7 % extra slowdown', '2. Move A2 next to VSS - expected effect: qualitative', '',
    '## What it costs', '', '- Area: +6 %', '- Input capacitance on A2: 0.13', '',
    '## How to check it', '', 'Re-characterise A2→ZN fall at 0.7 V; re-run the rule; pass below +5 %.', ''].join('\n') });
});

test('vmin redesign brief without a netlist stays at arc level', () => {
  const item = { name: 'MUX2X2', label: 'MUX2X2 SVT', v: '8T-SVT', brief: { ...brief, cell: 'MUX2X2/8T SVT', where: null, cost: [] } };
  const file = INSIGHT.files.redesignBrief(vmin, item);
  assert.equal(file.name, 'redesign_MUX2X2_8T_SVT.md', 'a file name never carries a path separator');
  const parts = file.text.split('\n').filter(line => line.startsWith('## '));
  assert.deepEqual(plain(parts), ['## What is wrong', '## Where in the circuit', '## What to change', '## What it costs', '## How to check it']);
  assert.ok(file.text.includes('## Where in the circuit\n\nNo transistor netlist was given, so this brief stays at arc level: A2→ZN fall.\n'));
  assert.ok(file.text.includes('## What it costs\n\n- not estimated\n'));
});

test('generated files carry only plain cell names, one-line comments and no spreadsheet formulas', () => {
  const hostile = 'X] ; file delete -force ~ ; #';
  const vmin = { id: 'vmin_bottleneck', hi: 0.81, items: [{ name: hostile, v: '6T-HVT\nexec rm', x: 12 }, { name: 'NOR3X1', v: '6T-HVT\nexec rm', x: 12 }] };
  for (const variant of [null, '6T-HVT\nexec rm']) {
    const sdc = INSIGHT.files.derateSdc(vmin, variant);
    assert.ok(!sdc.text.includes(hostile), 'a name that is not a plain identifier never reaches a command line');
    assert.match(sdc.text, /\[get_lib_cells \*\/NOR3X1\]/);
    assert.ok(sdc.text.split('\n').every((line: string) => line === '' || line.startsWith('#') || line.startsWith('set_timing_derate')), 'a variant cannot open a new line');
  }
  const tcl = INSIGHT.files.dontUseTcl({ id: 'critical_path_faster_cells', design: { name: 'demo_top\nexec rm' },
    paths: [{ rows: [{ cell: 'NAND2X1', cls: 'NAND2\nexec rm' }] }] }, { '0:0': [hostile, 'NAND2X2'] });
  assert.ok(!tcl.text.includes(hostile));
  assert.ok(tcl.text.split('\n').every((line: string) => line === '' || line.startsWith('#') || line.startsWith('set_dont_use [get_lib_cells */')));
  assert.equal(tcl.lines, 1);
  const csv = INSIGHT.files.roadmapGapsCsv({ items: [{ cls: '=HYPERLINK("x")', v: '+1', lo: { name: 'A' }, hi: { name: 'B' }, ratio: 2, miss: { drive: 1.5, area: 1 } }] });
  assert.ok(csv.text.includes(`'=HYPERLINK`) && csv.text.includes(`'+1`), 'a text cell never starts a formula');
});
