// @hima-seam webserver wrapped
// @hima-seam client-connection wrapped
// The Hima remote interface: one namespace, `/hima/api/`, on the host's web server. It is what
// HimaGuide reads a Run's result through, and the only way the browser reaches HimaLedger.
//
// dsh's own Host↔Client Remote API is generated by the dsh repository's build (`DSH_BUILD_FACE
// host`) and has no documented out-of-tree path, so HimaHarness owns this interface end to end
// instead: this file is the host side, `src/client/api.ts` the browser side, and the JSON below is
// the whole contract between them. Both dsh seams it stands on are wrapped here and nowhere else —
// `ctx.webServer.register` carries the routes, and `ctx.connection.requestRejection` applies the
// web app's own Host/Origin fence and session cookie to every one of them, so a Hima route is
// exactly as guarded as `/api` is.
//
// The whole namespace, twelve operations and no more:
//   GET  /hima/api/runs/<runId>           the Run: where it stands, its observations, its refusals,
//                                         its verdicts with every citation resolved to the record it
//                                         was read from, its nodes, its Jobs, and its decision
//   GET  /hima/api/runs/<runId>/records   the Run's ledger records, `?type=` narrowing to one kind
//   GET  /hima/api/records/<recordId>     one ledger record by id, exactly as the ledger holds it
//   POST /hima/api/observe                the observe operation, body `{ site, path, reader?, run?, judge?, params? }`,
//                                         answering with the Run it created or appended to — the same
//                                         view as the read above. `params` binds a value for any
//                                         parameter a rule in `judge` declares, e.g. `{ target_period_ns: 2.3 }`.
//   POST /hima/api/runs                   start a Campaign and execute its graph, body
//                                         `{ pack, site, goal, strategy?, timeBox?, retries?, generations? }`, answering
//                                         with the Run when it stops — the same view as the read above.
//   POST /hima/api/runs/start             the same body and the same operation, answering as soon as
//                                         the Run exists while HimaFabric goes on driving it in the
//                                         host — what the workbench's start form posts, because a
//                                         Campaign outlives any one request (#26).
//   POST /hima/api/runs/<runId>/resume    clear a waiting Run and carry it on, no body, answering
//                                         with the Run when it stops again — the same view. Recorded
//                                         as a person's action, by `workbench`.
//   GET  /hima/api/audit                  every command HimaChannel has asked a Site to run in this
//                                         host process since the last drain, oldest first, with
//                                         `windowFilled` saying whether the rolling window has been
//                                         full — whether a command may already have been lost
//   POST /hima/api/audit/drain            the same answer, and the audit cleared: what a caller
//                                         watching a long Campaign asks so a window's worth of
//                                         polling cannot evict the launch line it is watching for
//   POST /hima/api/runs/<runId>/cancel    stop that Run: kill the Job it has open, wait for the stop
//                                         to be observed, end the Run cancelled, and answer with it —
//                                         again the same view. A Run that already ended answers with
//                                         its own status and nothing is written.
//   GET  /hima/api/runs/<runId>/experience
//                                         the Campaign's technical report (#30): the `experience`
//                                         record plus both files read back off the Site through the
//                                         channel's read-only verbs, each held against the hash the
//                                         record carries — a file that has changed answers
//                                         `409 hima/experience-changed` naming both hashes. The one
//                                         pair of routes in this namespace that reaches a Site to
//                                         answer a read
//   GET  /hima/api/runs/<runId>/experience.md
//                                         the same report's Markdown alone, as `text/markdown`: what
//                                         the card's link opens
// The three reads are #3's three ledger reads — by run, by type, and by ID — and every one of them
// goes through the host: nothing in the browser reaches a storage domain.
//
// One document lives beside the namespace, behind the same fence: `GET /hima/` is the workbench
// page (`workbench.ts`), the Runs listed and, with `?run=<id>`, one Run's card — what the desktop
// shell's driver opens and reads (D42, ADR-0004). It is served here because it answers off the same
// run view the JSON does, and a page rendered from a second reading of the ledger would be a page
// that could disagree with the route beside it.
import type { IncomingMessage, ServerResponse } from 'node:http';
import type { Context } from '@deepseek-ai/cordis';
// Type-only: these load the `ctx.webServer` and `ctx.connection` declaration merges onto Context.
// Nothing is imported at runtime, so a host composed without a browser surface never loads them.
import type {} from '@deepseek-ai/dsh-host-webserver';
import type {} from '@deepseek-ai/dsh-client-connection';
import type {
  BlockerRecord,
  CancelRecord,
  DecisionChoice,
  DecisionRecord,
  ExperienceRecord,
  JobIdentity,
  JobRecord,
  Ledger,
  LedgerRecord,
  NodeKind,
  NodeRecord,
  NodeState,
  ObservationRecord,
  ReaderRef,
  RefusalRecord,
  RunBudget,
  RunLoop,
  RunFork,
  RunMeters,
  RunRecord,
  RunStatus,
  RunStrategy,
  VerdictRecord,
  WorkspaceRecord,
} from './ledger.js';
import type { GenerationView } from './generations.js';
import { generationsOf } from './generations.js';
// Type-only, like every other shape here: this module is bundled into the browser half as well, and
// `channel.ts` reaches for ssh and the filesystem. What the audit routes answer comes through
// `RemoteOperations`, from the host that has the audit.
import type { RemoteCommand } from './channel.js';
// The three record-to-view mappings a branch row reads too, so both folds are one description
// (`record-views.ts`). Re-exported below, because a face reading a Run reads them from here.
import { jobView, nodeView, observationView } from './record-views.js';
import type { JobView, NodeView, ObservationView } from './record-views.js';
export type { ObservationView, NodeView, JobView } from './record-views.js';
import type { SemanticValue } from './semantics.js';
import type { ObserveRequest, ObserveResult } from './observe.js';
import type { ExperienceJson } from './experience-report.js';
import type { ReadExperienceResult } from './experience.js';
import type { ResumeResult, StartRunRequest, StartRunResult } from './fabric.js';
import type { CancelResult } from './recovery.js';
import { allowsRunArgument, badRunArgument, notWaitingToResume, unresumableReason, type RunArgumentName, type StrategyDeclaration, type StrategyValue } from './run-arguments.js';
import { SiteNotFoundError, RuleReferenceError, RunFaultError, RunReferenceError, RunStartError, PackNotFoundError, SiteUnreadableError } from './errors.js';
import { messagePage, runPage, runsPage, type StartChoices } from './workbench.js';
import { HIMA_API_PREFIX, HIMA_WORKBENCH_PATH } from './paths.js';

// The one namespace and the one document, both from the leaf every face reads them from
// (`paths.ts`): every Hima operation lives under `HIMA_API_PREFIX`, and the one thing Hima serves
// outside it is the workbench page at `HIMA_WORKBENCH_PATH`, which is a document and not an
// operation. Re-exported here because this module is the wire contract a caller reads.
export { HIMA_API_PREFIX, HIMA_WORKBENCH_PATH } from './paths.js';

/**
 * What a failed Hima request answers with. The code is the contract, the status its HTTP shape:
 * `hima/run-not-found` (404) — no such run in the ledger;
 * `hima/record-not-found` (404) — no such record in the ledger;
 * `hima/bad-request` (400 malformed, 404 unknown route, 405 wrong method) — the caller's request
 * is not one this namespace answers;
 * `hima/run-not-in-state` (409) — the Run is there and the request is well formed, but where the Run
 * stands is not a state that request can be made of: a resume of a Run that is not waiting, a cancel
 * of a Run HimaFabric never started. Its own code and its own status because it is neither the
 * caller's spelling nor our fault but a fact about the Run at this instant, and one that another face
 * may have caused a moment ago — a workbench that read a waiting Run and posted a resume the instant
 * a command line resumed it has not sent a malformed request, and 409 is the answer that tells it to
 * re-read the Run rather than to fix its body. Nothing is written on either;
 * `hima/run-not-stopped` (409) — a cancel killed the Run's Job and the Site did not report the stop
 * inside the bounded wait. Nothing the caller sent is wrong and nothing here failed: the Job is a
 * fact about the Site, and the Site still has it. Its own code, because it is the one conflict a
 * caller cannot resolve by re-reading the Run — the session is named in the message and on the Run's
 * own blocked node, and what to do about it is on the Site. Not 500: nothing internal broke;
 * `hima/experience-changed` (409) — the Campaign's technical report on the Site is not the one the
 * `experience` record hashed. Its own code, because it is the one answer this namespace gives about
 * evidence: the file was written once and never again (D44), so a file that no longer matches its
 * hash is not a report this harness will serve as one, and the message names the recorded hash and
 * what was found instead. Not a 500 — nothing here failed — and not a 404: the report is on record,
 * and what changed is a file on somebody's Site. A report the Site would not *give up* — a `cat`
 * that failed, a Permit that refused the read — is a different fact and is answered below;
 * `hima/not-authorized` (401, 403) — the web app's fence refused the request before it was read;
 * `hima/site-unreadable` (503) — the Site would not answer a question about a Job (#18), or would
 * not give up a file the ledger says it holds (#30), so nobody knows the answer and nothing was
 * written. Its own code and its own status because it is neither the caller's mistake nor a fault
 * inside this harness: a machine somewhere else stopped answering, the Run and its Job are exactly
 * as they were, and the right thing for a caller to do is ask again once the Site is back — which is what 503 means and what no other code here says. Its message carries
 * the Site's name and the Site's own words, because unlike a `RunFaultError` there is nothing written
 * for the caller to fetch instead, and the Site's words are what an operator acts on;
 * `hima/internal` (500) — the operation failed for a reason the caller did not cause. Its message is
 * deliberately generic — a 500 body reaches whoever made the request, and a raw error text can carry
 * host paths and errno detail that belong in the host's log, not on the wire — with one exception: a
 * `RunFaultError` (a fault mid-drive) carries its own message, because that same text is already on
 * the Run's blocked node, and the same fenced caller can fetch it there through this very namespace;
 * nothing reaches the wire here that was not already reachable. That text may be raw errno text
 * (`startRunOperation` in this file states which).
 * A failure is never an empty answer: the client renders the code.
 */
export type HimaErrorCode = 'hima/run-not-found' | 'hima/record-not-found' | 'hima/bad-request' | 'hima/run-not-in-state' | 'hima/run-not-stopped' | 'hima/experience-changed' | 'hima/not-authorized' | 'hima/site-unreadable' | 'hima/internal';
export interface HimaErrorBody { readonly error: { readonly code: HimaErrorCode; readonly message: string } }

/** One refusal as HimaGuide shows it: a Run that read nothing still says why. */
export interface RefusalView {
  readonly recordId: string;
  readonly at: string;
  readonly path: string;
  readonly reason: string;
  readonly writer: string;
}

/**
 * One record a verdict cited, resolved here rather than in the browser. `observation` is null only
 * when the cited record is not an observation this run holds — an unresolvable citation is shown,
 * never dropped.
 */
export interface Citation { readonly recordId: string; readonly observation: ObservationView | null }

/** One verdict as HimaGuide shows it: the outcome, the rule identity and version, its citations. */
export interface VerdictView {
  readonly recordId: string;
  readonly at: string;
  readonly outcome: VerdictRecord['outcome'];
  readonly ruleId: string;
  readonly ruleVersion: string;
  readonly reason?: string;
  /** The value bound to each parameter the rule declared, when it declared one. */
  readonly boundParameters?: Readonly<Record<string, number>>;
  readonly valuesAsRead: readonly SemanticValue[];
  readonly cites: readonly Citation[];
}

/**
 * One Hard blocker as HimaGuide shows it: the node that gave up, how many attempts it made, what its
 * last Job exited with, and the tail of that Job's log — everything a person needs to decide whether
 * to clear it, without leaving the workbench for the Site.
 */
export interface BlockerView {
  readonly recordId: string;
  readonly at: string;
  readonly nodeId: string;
  readonly attempts: number;
  readonly lastExitCode?: number;
  readonly logTail?: string;
  readonly reason: string;
}

/**
 * The Run's decision as HimaGuide shows it. `cites` stays a list of record ids rather than resolved
 * citations, because a decision cites verdicts as well as an observation, and a `Citation` resolves
 * observations alone: showing a verdict id as an unresolvable citation would say the wrong thing.
 */
export interface DecisionView {
  readonly recordId: string;
  readonly at: string;
  readonly nodeId: string;
  readonly chooser: string;
  readonly chosen: DecisionChoice;
  readonly rationale: Readonly<Record<string, number>>;
  readonly cites: readonly string[];
}

/** One cancel request as HimaGuide shows it: that a person asked this Run to stop, and what it stood
 *  at when they did. What actually stopped is in `jobs` and `nodes` — the request and the observed
 *  stop are two records, and this view keeps them two. */
export interface CancelView {
  readonly recordId: string;
  readonly at: string;
  readonly nodeId?: string;
  /**
   * Every Job the request found open, in the order it stopped them — the record's own list (#29). A
   * Run inside a fork holds one Job per branch and one `cancel` record is written for all of them,
   * so a face that named one of two would say a licence was free while the other branch still held
   * it. Absent on a request that found nothing open, exactly as the record is.
   */
  readonly jobSessions?: readonly string[];
  /** The head of `jobSessions`, kept because every face names one Job (`/hima cancel` says which
   *  session it stopped, and `CancelResult.stopped` is that one). A spelling of the list's head and
   *  never a fact of its own: a view carrying one carries the other. */
  readonly jobSession?: string;
}

/**
 * What one of a Run's numbers is called and what it is measured in, as the pack that owns it
 * declares (#42): `{ label: 'clock period at most', unit: 'ns' }` for `target_period_ns`.
 *
 * Declared here rather than beside the schema that parses it (`packs.ts`) because the browser
 * bundle reads this file and cannot read that one — `packs.ts` opens directories — and because this
 * is the shape that travels: a face renders these two strings and asks the pack nothing.
 */
export interface RunWord {
  readonly label: string;
  /**
   * What it is measured in — absent on the one thing a Run is stated in that is not a number: a
   * Strategy knob the pack declared as a choice out of a list (#58), whose value is one of the
   * pack's own words. A face renders `<label> <value> <unit>` where there is one and
   * `<label> <value>` where there is not.
   */
  readonly unit?: string;
}

/**
 * The knobs a pack declares its Strategy to be made of, as a face reads them off a run view or off
 * the start form: re-exported from the leaf module the three faces validate a value against, so the
 * browser bundle renders a field from the very shape the harness holds a value to.
 */
export type { StrategyDeclaration, StrategyKnob, StrategyValue } from './run-arguments.js';

/**
 * The pack's words for the numbers a Run is stated in, resolved for the Run's own pack and split by
 * where each number comes from: the Goal a Campaign was started with, and the Strategy it is set to.
 *
 * Split rather than one flat map because the two are two questions — what a Campaign is *for* and
 * what it is *trying right now* (CONTEXT.md, Goal and Strategy) — and a pack may one day call one
 * number two things depending on which of them it is being read as. Every name a face looks up here
 * is a name it already holds off `run.goal` or `run.strategy`, so a lookup that misses is a number
 * shown under its own name and never a blank.
 */
export interface RunWords {
  readonly goal: Readonly<Record<string, RunWord>>;
  readonly strategy: Readonly<Record<string, RunWord>>;
}

/** The Run row itself: its identity, and the fabric state a Run HimaFabric started also carries. */
export interface RunHeadView {
  readonly id: string;
  readonly campaignId: string;
  readonly siteId: string;
  readonly createdAt: string;
  readonly status?: RunStatus;
  /** The pack this Run runs. Absent on a Probe-campaign Run, which runs none. */
  readonly packId?: string;
  /**
   * The version of that pack, as the workspace this Campaign was prepared in recorded it.
   *
   * Read off the `workspace` record rather than off the row, because that is where it is: a Run's
   * row says which pack it runs and the preparation is what pinned the version it ran. Absent until
   * a workspace has been prepared, and on every Run that never got one.
   *
   * On the view at all because the Campaign's technical report names the pack *and its version* —
   * which method these facts came from is half of what makes an experience worth keeping (D16, user
   * story 12) — and both mounts of the card compose that report from this view alone (#30).
   */
  readonly packVersion?: string;
  readonly goal?: Readonly<Record<string, number>>;
  /**
   * What this Run's pack calls the numbers above, resolved from the pack when the view is composed
   * (#42) — never written to the ledger and never on the wire in place of a name: `goal` and
   * `strategy` keep the names whatever a pack declares, so a caller that reads numbers reads exactly
   * what it read before this field existed.
   *
   * On the run head so that every face renders from one source: the workbench page, the chat's card
   * and `/hima status` all read the words table off this and could not come to say a Goal two ways.
   *
   * Absent on a Run whose pack declares none, on a Probe-campaign Run that runs no pack at all, and
   * on a Run whose pack this host can no longer read — a pack uninstalled, or edited into something
   * that does not hang together, since the day it ran. A card that would not render because a pack
   * has moved would be a worse answer than the names, which is what the ledger itself holds.
   */
  readonly words?: RunWords;
  readonly budget?: RunBudget;
  readonly currentNode?: string;
  readonly strategy?: RunStrategy;
  /** Which Generation of its Loop this Run is in, as the row says. Absent on a Probe-campaign Run. */
  readonly generation?: number;
  /** The drill-down Loop it is standing inside, while it is standing inside one (#28); absent when
   *  it is not, which is every Run of a pack that drills nowhere. */
  readonly loop?: RunLoop;
  /** The fork it is standing inside, while it is standing inside one (#29): which node branched,
   *  which judge node the branches converge into, and where each branch stands. Absent when it is
   *  not, which is every Run of a pack that does not fork. */
  readonly fork?: RunFork;
  readonly meters?: RunMeters;
}

/** A whole Run as HimaGuide shows it. Every operation that answers with a Run answers with this. */
export interface RunView {
  readonly run: RunHeadView;
  readonly observations: readonly ObservationView[];
  readonly refusals: readonly RefusalView[];
  readonly verdicts: readonly VerdictView[];
  readonly nodes: readonly NodeView[];
  /**
   * One row per Generation of the Run's Loop, oldest first: what a Campaign has done, as against
   * `nodes`, which is where it stands. Empty on a Run HimaFabric never started, which has opened
   * none. Folded by `generations.ts`.
   */
  readonly generations: readonly GenerationView[];
  readonly jobs: readonly JobView[];
  /** Every Hard blocker this Run has hit, in the order it hit them; a resumed one stays on the list. */
  readonly blockers: readonly BlockerView[];
  /** Every request to stop this Run, in the order they were made. Empty for a Run nobody cancelled. */
  readonly cancels: readonly CancelView[];
  /** The Run's latest decision, or null when it has made none. */
  readonly decision: DecisionView | null;
  /**
   * The Campaign's technical report, once it has been written: where both files are on the Site,
   * what each hashes to, and when it was written (#30).
   *
   * The record and **not** the files. This view is composed from the ledger alone, synchronously,
   * and is re-composed every time the window's page refreshes itself — a second, on an open card —
   * so reading two files off a Site to answer it would put an ssh round trip on every render. What
   * a face shows is composed from this same view (`experience-report.ts`), which is what the file
   * holds; the files themselves are read back, and held against these hashes, by the two experience
   * routes.
   *
   * Absent on every Run that has not ended, and on an ended Run whose report is still owed.
   */
  readonly experience?: ExperienceView;
}

/** One file of the report as HimaGuide shows it: where it is on the Site, and what it hashes to. */
export interface ExperienceFileView {
  readonly path: string;
  readonly sha256: string;
  readonly bytes: number;
}

/** The Campaign's technical report as HimaGuide shows it: the `experience` record, and nothing the
 *  ledger does not hold. */
export interface ExperienceView {
  readonly recordId: string;
  /** The instant both files state as their own, which is what a face composing the report uses. */
  readonly writtenAt: string;
  readonly markdown: ExperienceFileView;
  readonly json: ExperienceFileView;
}

/**
 * What `GET /hima/api/runs/<id>/experience` answers: the record, and both files read back off the
 * Site with their hashes verified.
 *
 * The files are here and not on the run view for the reason the run view says: this route pays for
 * the Site round trip and the verification, and a caller asking for it is asking for the artefact
 * rather than for the Run.
 */
export interface ExperienceAnswer {
  readonly experience: ExperienceView;
  /** The Markdown as the file on the Site holds it. */
  readonly markdown: string;
  /** The JSON as the file on the Site holds it, parsed. */
  readonly report: ExperienceJson;
}

/** The records of one run, exactly as the ledger holds them. */
export interface RecordsView { readonly records: readonly LedgerRecord[] }

/** One ledger record by id, exactly as the ledger holds it. */
export interface RecordView { readonly record: LedgerRecord }

/**
 * What this host process has asked Sites to run: HimaChannel's own audit, as the audit routes answer
 * it.
 *
 * `commands` is every command since the last drain, oldest first — Hima's own verbs and the Job
 * command lines alike, each with the argv it was decided on and the string the wire received.
 * `windowFilled` says whether the rolling window (`remoteCommandWindow` entries) has been full since
 * that drain: `true` and the list is no longer everything, so a caller claiming "every command" must
 * either drain more often or stop claiming it. The two travel together because neither is worth
 * reading without the other.
 */
export interface AuditView {
  readonly commands: readonly RemoteCommand[];
  readonly windowFilled: boolean;
}

/** What `POST /hima/api/observe` accepts: the observe operation, as the command and the tool take it. */
export interface ObserveBody extends ObserveRequest {
  readonly judge?: readonly string[];
  /** Named values for any parameter a rule in `judge` declares; a declared parameter with no matching entry leaves that rule UNDETERMINED. */
  readonly params?: Readonly<Record<string, number>>;
}

/**
 * What `POST /hima/api/runs` accepts: the same arguments `/hima run` and `hima_run` take, spelled
 * the way the flags are. `timeBox` is in minutes, as the flag is.
 */
export interface StartRunBody {
  readonly pack: string;
  readonly site: string;
  readonly goal: Readonly<Record<string, number>>;
  /**
   * What to set the pack's own Strategy knobs to, by name (#58): `{ "<knob>": <value> }`. A knob left
   * out takes the default the pack's contract declares; a knob no pack declares, or a value outside
   * what it declares, is refused and no Run is started.
   */
  readonly strategy?: Readonly<Record<string, StrategyValue>>;
  readonly timeBox?: number;
  readonly retries?: number;
  /** How many Generations this Campaign's Loop may open. Absent, the pack's own, then the default. */
  readonly generations?: number;
}

/** What this namespace needs from the Hima service. Nothing here reaches for the plugin itself. */
export interface RemoteOperations {
  readonly ledger: Ledger;
  observe(request: ObserveRequest): Promise<ObserveResult>;
  /** Ask HimaJudge to rule; the verdicts it wrote are read back from the ledger, not from here. */
  judge(runId: string, ruleIds: readonly string[], params?: Readonly<Record<string, number>>): Promise<VerdictRecord[]>;
  /** Start a Campaign and execute its graph; the Run it left behind is read back from the ledger. */
  startRun(request: StartRunRequest): Promise<StartRunResult>;
  /** Clear a waiting Run and carry it on, as the person `who` names. */
  resumeRun(runId: string, who: string): Promise<ResumeResult>;
  /** Stop a Run: kill the Job it has open, wait for the stop to be observed, and end the Run. */
  cancelRun(runId: string): Promise<CancelResult>;
  /** Read a Campaign's technical report back off its Site, holding both files against the hashes the
   *  `experience` record keeps. Here rather than done in this module, for the reason `installed` is:
   *  this namespace reaches no Site and opens no file of its own. */
  readExperience(runId: string): Promise<ReadExperienceResult>;
  /** HimaChannel's audit of what this host process has asked Sites to run since the last drain, and
   *  whether its rolling window has been full. Here rather than read from `channel.ts` for the same
   *  reason `readExperience` is: that module reaches ssh and this one is bundled into the browser
   *  too. The host that implements this is the process whose audit it is — a caller could hand this
   *  namespace some other list, and a list of remote commands nobody can place is not evidence. */
  remoteCommandAudit(): AuditView;
  /** The same answer, and the audit cleared, in one step: what a watcher takes so that a window's
   *  worth of Job polling cannot evict the launch line it is watching for. Its own verb rather than
   *  a flag on the read above, because a read that emptied what it read would take the evidence away
   *  from whoever was only looking. */
  drainRemoteCommandAudit(): AuditView;
  /** The packs installed on this host, by id, and the Sites by name: what the workbench page's start
   *  form offers, so nobody has to know an id by heart to start a Campaign. Read here rather than
   *  from a directory this module opens itself, because where they are installed is the host's
   *  configuration and this namespace touches no filesystem of its own. */
  installed(): { readonly packs: readonly string[]; readonly sites: readonly string[] };
  /**
   * What a pack calls its Goal's parameters and its Strategy's knobs (#42), or nothing for a pack
   * that declares no words, for a Run that names no pack, or for a pack this host can no longer
   * read. Here for the reason `installed` is: a pack is a directory, and this namespace opens none.
   *
   * Asked once per answer rather than cached, so a pack whose words were corrected while a window
   * was open says the correction on the next render — the same call `installed` makes, and against
   * two small files.
   */
  packWords(packId: string | undefined): RunWords | undefined;
  /**
   * The knobs a pack declares its Strategy to be made of (#58), or nothing for a pack this host
   * cannot read. Here for the reason `packWords` is: a pack is a directory, and this namespace opens
   * none. Asked when the start form is rendered, so a pack whose declaration was corrected while a
   * window was open offers the corrected fields on the next look.
   */
  packStrategy(packId: string): StrategyDeclaration | undefined;
}

/** A request the caller got wrong: it reaches them as `hima/bad-request`, with its own message. */
class BadRequest extends Error {}

/**
 * A request this Run's status cannot take: it reaches the caller as `hima/run-not-in-state` (409),
 * with its own message and with nothing written. Separate from `BadRequest` because the caller has
 * nothing to fix in what they sent — the Run moved, or was never HimaFabric's — and the two answers
 * ask for different things: re-read the Run, rather than re-write the request.
 */
class NotInState extends Error {}

function refusalView(record: RefusalRecord): RefusalView {
  return { recordId: record.id, at: record.at, path: record.path, reason: record.reason, writer: record.writer };
}

function verdictView(record: VerdictRecord, observations: ReadonlyMap<string, ObservationView>): VerdictView {
  const head = {
    recordId: record.id,
    at: record.at,
    outcome: record.outcome,
    ruleId: record.ruleId,
    ruleVersion: record.ruleVersion,
    valuesAsRead: record.valuesAsRead,
    cites: record.cites.map((recordId) => ({ recordId, observation: observations.get(recordId) ?? null })),
  };
  // An absent key, never an undefined one: a verdict with no reason, or no bound parameter, says so by omission.
  const withReason = record.reason === undefined ? head : { ...head, reason: record.reason };
  return record.boundParameters === undefined ? withReason : { ...withReason, boundParameters: record.boundParameters };
}

function blockerView(record: BlockerRecord): BlockerView {
  const head = { recordId: record.id, at: record.at, nodeId: record.nodeId, attempts: record.attempts, reason: record.reason };
  // An absent key, never an undefined one: a failure with no exit status and no log says so by omission.
  const withExit = record.lastExitCode === undefined ? head : { ...head, lastExitCode: record.lastExitCode };
  return record.logTail === undefined ? withExit : { ...withExit, logTail: record.logTail };
}

/**
 * A cancel request as the view carries it. An absent key, never an undefined one: a Run asked to
 * stop while it stood at no node, or held no Job, says so by omission exactly as its record does.
 *
 * The record's own two spellings of what it stopped, copied and not folded here (#29): every session
 * in `jobSessions`, and the head of that list again in `jobSession` because every face names one
 * Job. Reading them as one list is `cancelSessions` (`record-views.ts`), which every face that has
 * to ask goes through — this module is in the browser bundle through `client/api.ts`, and that leaf
 * is where a fold both sides need can live without pulling the ledger's own module into the client.
 */
function cancelView(record: CancelRecord): CancelView {
  const head = { recordId: record.id, at: record.at };
  const withNode = record.nodeId === undefined ? head : { ...head, nodeId: record.nodeId };
  const withSessions = record.jobSessions === undefined ? withNode : { ...withNode, jobSessions: record.jobSessions };
  return record.jobSession === undefined ? withSessions : { ...withSessions, jobSession: record.jobSession };
}

function decisionView(record: DecisionRecord): DecisionView {
  return {
    recordId: record.id,
    at: record.at,
    nodeId: record.nodeId,
    chooser: record.chooser,
    chosen: record.chosen,
    rationale: record.rationale,
    cites: record.cites,
  };
}

/** The run row as the view carries it, with the fabric fields a Run HimaFabric started also has. */
function runHeadView(run: RunRecord, packVersion?: string, words?: RunWords): RunHeadView {
  const head: RunHeadView = { id: run.id, campaignId: run.campaignId, siteId: run.siteId, createdAt: run.createdAt };
  // Each optional field is added only when the Run has one, so a Probe-campaign Run's view carries
  // no empty fabric state and the client can tell "not started" from "started and at zero".
  const withStatus = run.status === undefined ? head : { ...head, status: run.status };
  const withPack = run.packId === undefined ? withStatus : { ...withStatus, packId: run.packId };
  const withVersion = packVersion === undefined ? withPack : { ...withPack, packVersion };
  const withWords = words === undefined ? withVersion : { ...withVersion, words };
  const withGoal = run.goal === undefined ? withWords : { ...withWords, goal: run.goal };
  const withBudget = run.budget === undefined ? withGoal : { ...withGoal, budget: run.budget };
  const withNode = run.currentNode === undefined ? withBudget : { ...withBudget, currentNode: run.currentNode };
  const withStrategy = run.strategy === undefined ? withNode : { ...withNode, strategy: run.strategy };
  const withGeneration = run.generation === undefined ? withStrategy : { ...withStrategy, generation: run.generation };
  const withLoop = run.loop === undefined ? withGeneration : { ...withGeneration, loop: run.loop };
  const withFork = run.fork === undefined ? withLoop : { ...withLoop, fork: run.fork };
  return run.meters === undefined ? withFork : { ...withFork, meters: run.meters };
}

/**
 * Compose the run view from the ledger: the run row, what it observed or refused, its verdicts, the
 * state each of its nodes is in, one row per Generation of its Loop, its Jobs, and its decision.
 *
 * `nodes` is one entry per node, carrying the latest transition of it, in the order the Run first
 * reached them — a Map keeps the position of a key it already holds, so a later transition updates
 * a node's entry without moving it. The whole path, every transition in sequence, is the `node`
 * records, which the records route answers.
 */
/** One file of the report, as the record holds it. */
const experienceFileView = (file: ExperienceRecord['markdown']): ExperienceFileView =>
  ({ path: file.path, sha256: file.sha256, bytes: file.bytes });

/** The report's record as HimaGuide shows it. */
export const experienceView = (record: ExperienceRecord): ExperienceView => ({
  recordId: record.id,
  writtenAt: record.writtenAt,
  markdown: experienceFileView(record.markdown),
  json: experienceFileView(record.json),
});

/**
 * @param ledger - the ledger, which is where every fact below is.
 * @param run - the run row.
 * @param words - what this Run's pack calls its Goal's parameters and its Strategy's knobs (#42),
 *                or nothing for a Run whose pack declares none or whose pack cannot be read. Handed
 *                in rather than resolved here because a pack is a directory on disk and this module
 *                opens none: `RemoteOperations.packWords` is what reads it, once per answer.
 */
export function runView(ledger: Ledger, run: RunRecord, words?: RunWords): RunView {
  const records = ledger.records({ runId: run.id });
  const observations = records.filter((r): r is ObservationRecord => r.type === 'observation').map(observationView);
  const byId = new Map(observations.map((o) => [o.recordId, o]));
  const nodes = new Map<string, NodeView>();
  // Whether a node ever waited for a slot is read over the whole path, not off the latest
  // transition: a node that waited and then ran says `done` by the time the Run is over.
  const waitedForSlot = new Set<string>();
  for (const record of records) {
    if (record.type !== 'node') continue;
    if (record.state === 'waiting-for-slot') waitedForSlot.add(record.nodeId);
    nodes.set(record.nodeId, nodeView(record));
  }
  const decision = records.findLast((r): r is DecisionRecord => r.type === 'decision');
  // The version of the pack this Campaign ran, as its preparation pinned it, and the report the
  // ending wrote — both read off this Run's own records, which is where each of them is.
  const prepared = records.findLast((r): r is WorkspaceRecord => r.type === 'workspace');
  const experience = records.findLast((r): r is ExperienceRecord => r.type === 'experience');
  return {
    run: runHeadView(run, prepared?.packVersion, words),
    observations,
    refusals: records.filter((r): r is RefusalRecord => r.type === 'refusal').map(refusalView),
    verdicts: records.filter((r): r is VerdictRecord => r.type === 'verdict').map((v) => verdictView(v, byId)),
    // An absent key, never an undefined one: a node that never waited says so by omission.
    nodes: [...nodes.values()].map((n) => (waitedForSlot.has(n.nodeId) ? { ...n, waitedForSlot: true as const } : n)),
    // The generations, each row saying what its Strategy asked for and what its decision chose in
    // the pack's own words (#58), which is why the words go in here rather than being resolved twice.
    generations: generationsOf(run, records, words),
    jobs: records.filter((r): r is JobRecord => r.type === 'job').map(jobView),
    blockers: records.filter((r): r is BlockerRecord => r.type === 'blocker').map(blockerView),
    cancels: records.filter((r): r is CancelRecord => r.type === 'cancel').map(cancelView),
    decision: decision ? decisionView(decision) : null,
    // An absent key, never an undefined one: a Run whose report is not written says so by omission.
    ...(experience === undefined ? {} : { experience: experienceView(experience) }),
  };
}

/**
 * The Run as every operation of this namespace answers with it: the view off the ledger, with the
 * words that Run's pack declares for its numbers resolved through the host (#42).
 *
 * One function and not eight call sites, because eight is how many places answer with a Run — the
 * observe, the two starts, the resume, the cancel, the read and the page — and a Run that arrived
 * through one of them without its words would be a card that said the same Campaign two ways
 * depending on which button a person had pressed last.
 */
const runAnswer = (ops: RemoteOperations, run: RunRecord): RunView => runView(ops.ledger, run, ops.packWords(run.packId));

const RECORD_TYPES = new Set<LedgerRecord['type']>(['observation', 'refusal', 'verdict', 'job', 'workspace', 'node', 'blocker', 'resumed', 'decision', 'cancel', 'loop', 'experience']);

function recordType(raw: string | null): LedgerRecord['type'] | undefined {
  if (raw === null) return undefined;
  if (!RECORD_TYPES.has(raw as LedgerRecord['type'])) {
    throw new BadRequest(`unknown record type "${raw}"; expected one of ${[...RECORD_TYPES].join(', ')}`);
  }
  return raw as LedgerRecord['type'];
}

/** Read a JSON request body, capped: a body this namespace cannot hold is the caller's mistake. */
async function readJsonBody(req: IncomingMessage): Promise<Record<string, unknown>> {
  const maxBytes = 64 * 1024;
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const chunk of req) {
    const buf = chunk as Buffer;
    size += buf.byteLength;
    if (size > maxBytes) throw new BadRequest(`request body exceeds ${String(maxBytes)} bytes`);
    chunks.push(buf);
  }
  const text = Buffer.concat(chunks).toString('utf8');
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new BadRequest('request body is not JSON');
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) throw new BadRequest('request body must be a JSON object');
  return parsed as Record<string, unknown>;
}

function requiredString(body: Record<string, unknown>, key: string): string {
  const value = body[key];
  if (typeof value !== 'string' || value === '') throw new BadRequest(`"${key}" is required and must be a non-empty string`);
  return value;
}

function optionalString(body: Record<string, unknown>, key: string): string | undefined {
  const value = body[key];
  if (value === undefined) return undefined;
  if (typeof value !== 'string' || value === '') throw new BadRequest(`"${key}" must be a non-empty string when given`);
  return value;
}

function optionalStrings(body: Record<string, unknown>, key: string): string[] | undefined {
  const value = body[key];
  if (value === undefined) return undefined;
  if (!Array.isArray(value) || value.some((v) => typeof v !== 'string' || v === '')) {
    throw new BadRequest(`"${key}" must be an array of non-empty strings when given`);
  }
  return value as string[];
}

/** One numeric argument of a Run in a request body, validated against the one table all three faces
 *  read, and refused in the words the other two use. */
function runNumber(body: Record<string, unknown>, key: RunArgumentName): number | undefined {
  const value = body[key];
  if (value === undefined) return undefined;
  if (typeof value !== 'number' || !allowsRunArgument(key, value)) throw new BadRequest(badRunArgument(key, key, value));
  return value;
}

function requiredNumberRecord(body: Record<string, unknown>, key: string): Record<string, number> {
  const value = optionalNumberRecord(body, key);
  if (value === undefined || Object.keys(value).length === 0) {
    throw new BadRequest(`"${key}" is required and must be a non-empty object of finite numbers, e.g. { "target_period_ns": 2.3 }`);
  }
  return value;
}

function optionalNumberRecord(body: Record<string, unknown>, key: string): Record<string, number> | undefined {
  const value = body[key];
  if (value === undefined) return undefined;
  if (typeof value !== 'object' || value === null || Array.isArray(value) || Object.values(value).some((v) => typeof v !== 'number' || !Number.isFinite(v))) {
    throw new BadRequest(`"${key}" must be an object of finite numbers when given`);
  }
  return value as Record<string, number>;
}

/**
 * The `strategy` of a start request: a knob's value is a finite number or a non-empty word, because
 * those are the two kinds a pack can declare a knob to be. Which knob takes which — and whether the
 * value is one this pack allows at all — is `startRun`'s to say against the pack's own declaration,
 * so this refuses only what no declaration could ever accept.
 */
function strategyRecord(body: Record<string, unknown>, key: string): Record<string, StrategyValue> | undefined {
  const value = body[key];
  if (value === undefined) return undefined;
  const bad = typeof value !== 'object' || value === null || Array.isArray(value)
    || Object.values(value).some((v) => !(typeof v === 'number' ? Number.isFinite(v) : typeof v === 'string' && v !== ''));
  if (bad) throw new BadRequest(`"${key}" must be an object of finite numbers and non-empty strings when given, e.g. { "<knob>": <value> }`);
  return value as Record<string, StrategyValue>;
}

/**
 * One percent-encoded path segment as the caller meant it. `%` followed by non-hex, or a lone
 * surrogate, is not an id anyone could have meant, and never a fault of ours — the caller's mistake,
 * not the 500 an uncaught URIError would give.
 */
function decoded(segment: string, what: string): string {
  try {
    return decodeURIComponent(segment);
  } catch {
    throw new BadRequest(`"${segment}" is not a validly percent-encoded ${what}`);
  }
}

interface Answer {
  readonly status: number;
  readonly body: unknown;
  /**
   * What this answer is sent as. Absent — which is every route but one — it is JSON, as the whole
   * namespace is. The one exception is the Campaign's report as Markdown: a file a person saves and
   * hands to a colleague (user story 11), which is the document itself and not a document inside a
   * JSON string. A failure on that route is still JSON, like every other failure here: an error is
   * the namespace's own answer and not the artefact.
   */
  readonly media?: 'text/markdown';
}

const ok = (body: unknown): Answer => ({ status: 200, body });
const failure = (status: number, code: HimaErrorCode, message: string): Answer => ({ status, body: { error: { code, message } } satisfies HimaErrorBody });

/** `POST /hima/api/observe`: read a file on a Site into the ledger and, when asked, judge the run. */
async function observeOperation(ops: RemoteOperations, req: IncomingMessage): Promise<Answer> {
  const body = await readJsonBody(req);
  const request: ObserveBody = {
    site: requiredString(body, 'site'),
    path: requiredString(body, 'path'),
    reader: optionalString(body, 'reader'),
    run: optionalString(body, 'run'),
    judge: optionalStrings(body, 'judge'),
    params: optionalNumberRecord(body, 'params'),
  };
  let result: ObserveResult;
  try {
    result = await ops.observe(request);
  } catch (err) {
    // Only a fault the caller demonstrably caused — a site name with no site file, a `run` naming a
    // run this ledger does not hold or one of another site — is their mistake. Everything else the
    // operation can throw (a broken site or permit config, a ledger write that failed, any other
    // storage-domain fault) is ours and propagates to the internal-error path below; it must never be
    // relabelled as a bad request just because it surfaced while handling one.
    if (err instanceof SiteNotFoundError || err instanceof RunReferenceError) {
      throw new BadRequest(`cannot observe ${request.path} on site ${request.site}: ${err.message}`);
    }
    throw err;
  }
  const ruleIds = request.judge;
  if (result.kind === 'observed' && ruleIds && ruleIds.length > 0) {
    try {
      await ops.judge(result.run.id, ruleIds, request.params);
    } catch (err) {
      // Likewise: only a rule reference the caller could not have gotten right (unknown id, wrong
      // version, malformed shape) is a bad request; a broken rule file or a ledger fault is ours.
      if (err instanceof RuleReferenceError) throw new BadRequest(`cannot judge ${result.run.id}: ${err.message}`);
      throw err;
    }
  }
  return ok(runAnswer(ops, result.run));
}

/**
 * What a caller asked a Campaign to be started as, read once for both start routes: whichever answer
 * a caller wants, they are asking for the same operation with the same arguments, and a field added
 * to the shared table in `run-arguments.ts` must land on both without anyone remembering to.
 */
async function readStartBody(req: IncomingMessage): Promise<StartRunBody> {
  const body = await readJsonBody(req);
  return {
    pack: requiredString(body, 'pack'),
    site: requiredString(body, 'site'),
    goal: requiredNumberRecord(body, 'goal'),
    strategy: strategyRecord(body, 'strategy'),
    timeBox: runNumber(body, 'timeBox'),
    retries: runNumber(body, 'retries'),
    generations: runNumber(body, 'generations'),
  };
}

/** That request as HimaFabric takes it: the flags' spelling turned into the operation's, with the
 *  time box converted from the minutes every face spells it in to the milliseconds it is stored in. */
const startRequestOf = (request: StartRunBody): StartRunRequest => ({
  pack: request.pack,
  site: request.site,
  goal: request.goal,
  strategy: request.strategy,
  timeBoxMs: request.timeBox === undefined ? undefined : Math.round(request.timeBox * 60_000),
  retryAllowance: request.retries,
  generationLimit: request.generations,
});

/**
 * `POST /hima/api/runs`: start a Campaign and let HimaFabric execute its graph, answering with the
 * Run when it stops. The whole Campaign happens inside this request, as it does inside the command
 * face — every generation of the Loop, one after another — and the Budget's time box and generation
 * limit are what bound how long that is.
 */
async function startRunOperation(ops: RemoteOperations, req: IncomingMessage): Promise<Answer> {
  const request = await readStartBody(req);
  let result: StartRunResult;
  try {
    result = await ops.startRun(startRequestOf(request));
  } catch (err) {
    return startThrew(request, err);
  }
  if (result.kind !== 'ran') return startedNothing(request, result);
  return ok(runAnswer(ops, result.run));
}

/**
 * What a start that threw answers with, for both start routes: a caller who chose the other answer
 * is refused the same things for the same reasons, in the same words.
 *
 * Only a fault the caller demonstrably caused — a pack or site with no file, a request with no goal
 * or no first strategy — is their mistake. A broken pack or site file, a ledger write that failed,
 * and every other fault are ours and go to the internal-error path.
 *
 * A fault mid-drive is ours, so it is a 500 like any other. `RunFaultError`'s own message is on the
 * wire, unlike the generic one, for one reason: it is already written to this Run's own blocked
 * node, which the caller can read back through this very namespace. Withholding it here would hide
 * from the caller only what they can already fetch. The message itself is not always one this
 * harness composed — it may be the underlying fault's raw text (an errno, e.g. `EISDIR: ...`,
 * carrying whatever path the fault touched), same as the node record it matches.
 */
function startThrew(request: StartRunBody, err: unknown): Answer {
  if (err instanceof SiteNotFoundError || err instanceof PackNotFoundError || err instanceof RunStartError || err instanceof RunReferenceError) {
    throw new BadRequest(`cannot start a run of pack ${request.pack} on site ${request.site}: ${err.message}`);
  }
  if (err instanceof RunFaultError) return failure(500, 'hima/internal', err.message);
  throw err;
}

/**
 * The two ways a start ends with no Run for HimaFabric to drive. Both are facts about what the
 * caller asked for that they must act on — a Site that cannot host the pack, a workspace that is not
 * this Campaign's — so both reach them as their request's fault rather than as a 500 that says
 * nothing, and in the words `/hima run` uses for them.
 */
function startedNothing(request: StartRunBody, result: Exclude<StartRunResult, { kind: 'ran' }>): never {
  if (result.kind === 'unfit') {
    throw new BadRequest(`site ${request.site} cannot host pack ${request.pack}: ${result.check.errors.join('; ')}`);
  }
  throw new BadRequest(`campaign ${result.run.campaignId} has no workspace to run in: ${unpreparedReason(result.prepared)}`);
}

/**
 * How often the start route looks at the row its own start opened, waiting for HimaFabric to move it
 * to `running`.
 *
 * One row by its id — `ledger.run(id)` — and never the whole list: the start says which Run it
 * opened (`StartRunRequest.onOpened`), so there is nothing to search for and nothing to guess at.
 * That is also why this look has no time limit any more. It used to have one because it was a sort
 * of every Run in the ledger 40 times a second against a guess, which could not be left running for
 * ever; a single lookup of a known row costs nothing, and a preparation still going is a request
 * still being answered rather than a request nobody will answer.
 */
const RUN_OPENS_POLL_MS = 25;

/**
 * `POST /hima/api/runs/start`: the same operation the route above performs, answered as soon as the
 * Run exists rather than when it stops — the run id and where it stands — while HimaFabric goes on
 * driving the Campaign in the host.
 *
 * Two answers to one operation because there are two callers with two needs, and neither can be
 * given the other's. A test and a script want the ending, and the route above is the one request
 * that waits for it. A *window* cannot wait: a Campaign is generations of synthesis long, and a form
 * whose request hung until the Campaign ended could not be watched, could not be cancelled, and
 * would be cut off by anything between the browser and the host that times a request out. So the
 * window posts here, and reads the rest off the card, which is what the card is for.
 *
 * The drive is started and deliberately not awaited. Whatever it does after this answer is recorded
 * against the Run itself, exactly as it is for the route above — a fault mid-drive lands on the Run's
 * blocked node, which the same fenced caller reads back through this namespace — so the promise is
 * watched only for what it says about a start that never got as far as a Run.
 *
 * That is also how this route knows what to answer with: `startRun` says which row it opened, the
 * moment it opens it (`StartRunRequest.onOpened`), and this route watches that row and no other
 * until HimaFabric has moved it to `running`. Waiting for `running` and not merely for the row is
 * what keeps this answer honest, because the two refusals that happen *after* a row exists — a
 * Campaign with no workspace, and a preparation that faulted — both leave the row `waiting` and are
 * answered as refusals here, the way they are answered everywhere else, rather than raced into a 200.
 */
async function startCampaignOperation(ops: RemoteOperations, req: IncomingMessage): Promise<Answer> {
  const request = await readStartBody(req);
  /** The row this start opened, as the start itself named it. Undefined until it has one. */
  let opened: RunRecord | undefined;
  let settled: { readonly ran: StartRunResult } | { readonly threw: unknown } | undefined;
  let driving: Promise<StartRunResult>;
  try {
    driving = ops.startRun({ ...startRequestOf(request), onOpened: (run) => { opened = run; } });
  } catch (err) {
    // A start that threw before it was even a promise is classified exactly as one that rejected.
    return startThrew(request, err);
  }
  void driving.then(
    (ran) => { settled = { ran }; },
    (threw: unknown) => { settled = { threw }; },
  );
  for (;;) {
    // The row as it stands now, and not the one handed over: what was handed over is an identity,
    // and where the Run stands is what this answer waits for.
    const row = opened === undefined ? undefined : ops.ledger.run(opened.id);
    if (row?.status === 'running') return ok(runAnswer(ops, row));
    const done = settled;
    if (done !== undefined) {
      if ('threw' in done) return startThrew(request, done.threw);
      // A Run that reached `running` and then ended inside one poll: the drive's own answer is the
      // Run, and it is a better one than the row would have been — it is where the Run finished.
      return done.ran.kind === 'ran' ? ok(runAnswer(ops, done.ran.run)) : startedNothing(request, done.ran);
    }
    await new Promise((resolve) => setTimeout(resolve, RUN_OPENS_POLL_MS));
  }
}

/**
 * `POST /hima/api/runs/<runId>/cancel`: stop the Run and answer with it, in the same view every other
 * operation here answers with — the caller reads the status, the killed Job and the cancelled node out
 * of it, rather than out of a shape invented for this one route.
 */
async function cancelOperation(ops: RemoteOperations, runId: string): Promise<Answer> {
  let result: CancelResult;
  try {
    result = await ops.cancelRun(runId);
  } catch (err) {
    // A Run this ledger does not hold is the same 404 the read route gives for it; every other fault
    // is ours and goes to the internal-error path.
    if (err instanceof RunReferenceError) return failure(404, 'hima/run-not-found', `no run ${runId} in the HimaLedger`);
    throw err;
  }
  // A Run HimaFabric never started is not a Run this route can stop, and there is nothing in the
  // request to correct: the fact is about where the Run stands, so it is the conflict code and the
  // words the command and tool faces use for it.
  if (result.kind === 'not-started') {
    throw new NotInState(`run ${runId} has no fabric state: HimaFabric never started it, so there is nothing to cancel`);
  }
  // A kill that did not take is nobody's request and not a Run view: the Run is not cancelled, and
  // answering 200 with it would say a Job stopped that is still running. It is not a 500 either —
  // nothing inside HimaHarness failed; the Site was asked to stop a Job and still has it, which is a
  // fact about the Site with a code of its own. Its message names the session and is also on the
  // Run's own blocked node, which this same fenced caller can fetch through this namespace.
  if (result.kind === 'not-stopped') {
    return failure(409, 'hima/run-not-stopped', `run ${runId} was not cancelled: its job was ${result.reason}`);
  }
  return ok(runAnswer(ops, result.run));
}

/**
 * `POST /hima/api/runs/<runId>/resume`: clear a waiting Run and let HimaFabric carry it on, answering
 * with the Run when it stops again. The whole continuation happens inside this request, exactly as
 * starting one does.
 *
 * No body is read at all: what to resume is in the path and who is resuming it is this face's own
 * answer — `workbench`, because a request that arrived through the web app's session fence is a
 * person at the workbench and nothing else. A body naming someone else would be a caller writing
 * whatever name it liked into the ledger's record of a person's action.
 *
 * A Run that is not waiting is answered `hima/run-not-in-state` (409) with the reason: nothing in the
 * request is wrong, the Run is simply not blocked — perhaps because another face cleared it a moment
 * ago — and re-reading it is what the caller should do next. One that is waiting and still cannot be
 * re-entered is `hima/bad-request`, because re-reading it would tell them nothing. Nothing is written
 * on either.
 */
async function resumeRunOperation(ops: RemoteOperations, runId: string): Promise<Answer> {
  let result: ResumeResult;
  try {
    result = await ops.resumeRun(runId, 'workbench');
  } catch (err) {
    if (err instanceof SiteNotFoundError || err instanceof PackNotFoundError || err instanceof RunReferenceError) {
      throw new BadRequest(`cannot resume run ${runId}: ${err.message}`);
    }
    // A fault mid-drive is ours, and carries its own message for the same reason starting a Run does:
    // it is already on this Run's blocked node, which the same caller can fetch through this namespace.
    if (err instanceof RunFaultError) return failure(500, 'hima/internal', err.message);
    throw err;
  }
  if (result.kind === 'not-waiting') {
    throw new NotInState(`cannot resume run ${runId}: ${notWaitingToResume(result.run.status)}`);
  }
  // Not the conflict code: a Run that is waiting and still cannot be re-entered is not in the wrong
  // state for a resume — it is a Run this machine cannot rebuild, because its workspace record, its
  // node or its pack is missing. Re-reading the Run would tell the caller nothing new, which is what
  // separates the two answers.
  if (result.kind === 'unresumable') throw new BadRequest(`cannot resume run ${runId}: ${unresumableReason(result.reason)}`);
  return ok(runAnswer(ops, result.run));
}

/**
 * `GET /hima/api/runs/<runId>/experience` and `…/experience.md`: the Campaign's technical report,
 * read back off the Site and held against the hashes the `experience` record keeps (#30).
 *
 * Both routes are one operation because they answer one thing in two media: the JSON answer carries
 * the record and both files, and the `.md` one carries the document a person saves. The verification
 * is the point of either — a report nobody checked is a file on a machine — so a file that no longer
 * hashes to what the Campaign wrote is refused with both hashes named rather than served.
 *
 * The Run is looked up here first so a Run this ledger does not hold is the same 404 every other
 * read route gives for it, and only then is the Site asked anything at all.
 */
async function experienceOperation(ops: RemoteOperations, runId: string, asMarkdown: boolean): Promise<Answer> {
  if (!ops.ledger.run(runId)) return failure(404, 'hima/run-not-found', `no run ${runId} in the HimaLedger`);
  const read = await ops.readExperience(runId);
  if (read.kind === 'none') {
    return failure(404, 'hima/record-not-found', `run ${runId} has no experience record: a campaign's technical report is written when its run ends`);
  }
  if (read.kind === 'changed') {
    return failure(
      409,
      'hima/experience-changed',
      `the ${read.file} of run ${runId}'s experience is not the file this ledger recorded: ${read.path} now hashes to sha256 ${read.found}, and the record has sha256 ${read.recorded}`,
    );
  }
  // A Site that would not give the file up is not a file that changed: nobody has read it, so
  // nobody knows whether it still hashes to what the Campaign wrote. A permission the Permit
  // refuses, an ssh that did not connect and a Site that is down are all the same fact — ask again
  // when the Site is back — which is what every other Site fault in this namespace answers with.
  if (read.kind === 'unreadable') {
    return failure(
      503,
      'hima/site-unreadable',
      `the ${read.file} of run ${runId}'s experience could not be read back from ${read.path}: ${read.why}; the record has sha256 ${read.recorded}`,
    );
  }
  if (asMarkdown) return { status: 200, body: read.markdown, media: 'text/markdown' };
  return ok({ experience: experienceView(read.record), markdown: read.markdown, report: read.json } satisfies ExperienceAnswer);
}

/**
 * `GET /hima/api/audit` and `POST /hima/api/audit/drain`: what this host has asked Sites to run.
 *
 * Why this is a route at all. HimaChannel's audit is the evidence behind the channel's promise —
 * every command sent to a Site, as the wire received it — and it is *per process*: the array lives
 * in this host's memory and nothing outside this process can see it. A Campaign is driven here, in
 * the host, while whoever wants to check what it sent (an acceptance run, an operator) is somewhere
 * else. Without this route the claim "every command this harness sent" can only be made from inside
 * the host itself, which is the one place with nobody to make it to.
 *
 * Why a drain and not only a read. The window is `remoteCommandWindow` entries and a Job that is
 * waited on costs two commands a look, so a long Campaign overruns it: the `tmux new-session` line
 * that is the whole point of keeping an audit would be evicted by the polling that followed it. A
 * caller therefore drains as the Campaign runs, and what it took is exact — the window carries no
 * sequence numbers, so two overlapping *reads* of a repeating poll could not be aligned with
 * certainty, while two drains simply do not overlap. The host reads and clears in one synchronous
 * step, with nothing awaited between them, so no command can slip in unrecorded between the two.
 *
 * Reading it is not privileged beyond the fence every other route sits behind: it says what this
 * host asked a Site to do, which is what the Permit already governs and what the Run's own records
 * already name, and one caller draining it takes it from the next — which `windowFilled` cannot warn
 * about, so a host is drained by one watcher at a time.
 */
function auditOperation(ops: RemoteOperations, drain: boolean): Answer {
  return ok(drain ? ops.drainRemoteCommandAudit() : ops.remoteCommandAudit());
}

/** Why a Campaign got no workspace. `unfit` is answered before a Run exists, so it cannot arrive here. */
function unpreparedReason(prepared: Extract<StartRunResult, { kind: 'unprepared' }>['prepared']): string {
  if (prepared.kind === 'occupied') return prepared.reason;
  if (prepared.kind === 'refused') return prepared.record.reason;
  return 'the pack does not fit this site';
}

/** Route one request inside the namespace. The path is already known to start with the prefix. */
async function route(ops: RemoteOperations, req: IncomingMessage, url: URL): Promise<Answer> {
  const rest = url.pathname.slice(HIMA_API_PREFIX.length);
  const method = req.method ?? 'GET';

  if (rest === '/observe') {
    if (method !== 'POST') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers POST`);
    return observeOperation(ops, req);
  }

  if (rest === '/runs') {
    if (method !== 'POST') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers POST`);
    return startRunOperation(ops, req);
  }

  // The audit of what this host has asked Sites to run. Two paths rather than one verb-switched
  // route, because reading and draining are not the same request: a `GET` that emptied what it read
  // would be a read with a side effect, and a caller who only wants to look would take the evidence
  // away from the one who is watching.
  if (rest === '/audit') {
    if (method !== 'GET') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers GET`);
    return auditOperation(ops, false);
  }

  if (rest === '/audit/drain') {
    if (method !== 'POST') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers POST`);
    return auditOperation(ops, true);
  }

  // Before the run read below, which would otherwise claim `/runs/start` as a run id — a Run's id is
  // `run-<uuid>`, so `start` can never be one, but the read is matched by shape and would answer 405
  // for a POST to this path rather than starting anything.
  if (rest === '/runs/start') {
    if (method !== 'POST') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers POST`);
    return startCampaignOperation(ops, req);
  }

  // Both matched before the two reads below, which claim `/runs/<id>` and `/runs/<id>/records` alone.
  const resume = /^\/runs\/([^/]+)\/resume$/.exec(rest);
  if (resume) {
    if (method !== 'POST') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers POST`);
    return resumeRunOperation(ops, decoded(resume[1]!, 'run id'));
  }

  const cancel = /^\/runs\/([^/]+)\/cancel$/.exec(rest);
  if (cancel) {
    if (method !== 'POST') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers POST`);
    return cancelOperation(ops, decoded(cancel[1]!, 'run id'));
  }

  // Before the run read below, which claims `/runs/<id>` and `/runs/<id>/records` alone: this pair is
  // the one place in the namespace that reaches a Site to answer a read.
  const experience = /^\/runs\/([^/]+)\/experience(\.md)?$/.exec(rest);
  if (experience) {
    if (method !== 'GET') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers GET`);
    return experienceOperation(ops, decoded(experience[1]!, 'run id'), experience[2] !== undefined);
  }

  const run = /^\/runs\/([^/]+)(\/records)?$/.exec(rest);
  if (run) {
    if (method !== 'GET') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers GET`);
    const runId = decoded(run[1]!, 'run id');
    const wantsRecords = run[2] !== undefined;
    // The caller's own request is checked before anything is looked up, so a malformed query is
    // reported as malformed whether or not the run it names exists.
    const type = wantsRecords ? recordType(url.searchParams.get('type')) : undefined;
    const record = ops.ledger.run(runId);
    if (!record) return failure(404, 'hima/run-not-found', `no run ${runId} in the HimaLedger`);
    if (!wantsRecords) return ok(runAnswer(ops, record));
    return ok({ records: ops.ledger.records(type === undefined ? { runId } : { runId, type }) } satisfies RecordsView);
  }

  const byId = /^\/records\/([^/]+)$/.exec(rest);
  if (byId) {
    if (method !== 'GET') return failure(405, 'hima/bad-request', `${method} ${url.pathname}; this route answers GET`);
    // A record id holds a `#`, so it always arrives percent-encoded; decoding it is the same
    // caller-fault case as a run id's.
    const recordId = decoded(byId[1]!, 'record id');
    const record = ops.ledger.record(recordId);
    if (!record) return failure(404, 'hima/record-not-found', `no record ${recordId} in the HimaLedger`);
    return ok({ record } satisfies RecordView);
  }

  return failure(404, 'hima/bad-request', `no Hima route at ${url.pathname}`);
}

function send(res: ServerResponse, answer: Answer): void {
  const markdown = answer.media === 'text/markdown';
  const body = markdown ? String(answer.body) : JSON.stringify(answer.body);
  res.writeHead(answer.status, {
    'content-type': markdown ? 'text/markdown; charset=utf-8' : 'application/json; charset=utf-8',
    'cache-control': 'no-store',
  });
  res.end(body);
}

function sendPage(res: ServerResponse, status: number, html: string): void {
  res.writeHead(status, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' });
  res.end(html);
}

/**
 * What the start form is rendered from: what this home has installed, and the Strategy the pack it
 * is showing declares (#58).
 *
 * The pack a form is for is the one asked for by `?pack=`, else the first installed — which is what
 * the `<select>` shows selected either way, so the fields under it always belong to the pack a
 * person is looking at. A name that is not installed is ignored rather than refused: the page is
 * still the workbench, and the form falls back to the first pack exactly as it does on a first load.
 *
 * @param ops - the host, which is what reads a pack off the disk.
 * @param asked - the `?pack=` of the request, or null.
 */
function startChoices(ops: RemoteOperations, asked: string | null): StartChoices {
  const installed = ops.installed();
  const pack = asked !== null && installed.packs.includes(asked) ? asked : installed.packs[0];
  if (pack === undefined) return installed;
  const strategy = ops.packStrategy(pack);
  const words = ops.packWords(pack);
  return { ...installed, pack, ...(strategy === undefined ? {} : { strategy }), ...(words === undefined ? {} : { words }) };
}

/**
 * `GET /hima/`: the workbench page. The start form and the run list under it, newest first, or with
 * `?run=<id>` that Run's card rendered from the very run view `GET /hima/api/runs/<id>` answers
 * with. `?pack=<id>` renders the same page with that pack's own knob fields on the form, which is
 * what the page itself asks for when a person changes the selection (#58). A Run the ledger does not
 * hold is a 404 page saying so; a method other than GET a 405 page.
 */
function workbenchPage(ops: RemoteOperations, req: IncomingMessage, url: URL): { readonly status: number; readonly html: string } {
  const method = req.method ?? 'GET';
  if (method !== 'GET') return { status: 405, html: messagePage(`${method} ${url.pathname}; this page answers GET`) };
  const runId = url.searchParams.get('run');
  if (runId === null) return { status: 200, html: runsPage(ops.ledger.runs().reverse().map((r) => runHeadView(r)), startChoices(ops, url.searchParams.get('pack'))) };
  const record = ops.ledger.run(runId);
  if (!record) return { status: 404, html: messagePage(`no run ${runId} in the HimaLedger`) };
  return { status: 200, html: runPage(runAnswer(ops, record)) };
}

/**
 * Mount the Hima namespace on the host web server, behind the web app's own request fence.
 * Registered as one prefix route so `/hima/api/...` is claimed whole: a path inside the namespace
 * that no operation answers is a Hima error, not the web app's index. The workbench page is a
 * second, exact route beside it, behind the same fence, answered as HTML.
 *
 * @param ctx - a context where both `webServer` and `connection` are present.
 * @param ops - the ledger and the operations this namespace exposes.
 * @returns the disposer removing both routes.
 */
export function registerHimaRoutes(ctx: Context, ops: RemoteOperations): () => void {
  const page = ctx.webServer.register({
    kind: 'exact',
    path: HIMA_WORKBENCH_PATH,
    handler: (req, res) => {
      const rejection = ctx.connection.requestRejection(req);
      if (rejection !== undefined) {
        sendPage(res, rejection, messagePage(rejection === 401 ? 'no browser session; open the workbench URL first' : 'this origin may not reach the Hima workbench'));
        return;
      }
      const url = new URL(req.url ?? '/', 'http://hima.invalid');
      try {
        const answer = workbenchPage(ops, req, url);
        sendPage(res, answer.status, answer.html);
      } catch (err) {
        ctx.logger.error(err);
        sendPage(res, 500, messagePage(`${url.pathname} failed inside HimaHarness; the reason is in the host log`));
      }
    },
  });
  const api = ctx.webServer.register({
    kind: 'prefix',
    path: HIMA_API_PREFIX,
    handler: async (req, res) => {
      const rejection = ctx.connection.requestRejection(req);
      if (rejection !== undefined) {
        send(res, failure(rejection, 'hima/not-authorized', rejection === 401 ? 'no browser session; open the workbench URL first' : 'this origin may not reach the Hima namespace'));
        return;
      }
      const url = new URL(req.url ?? '/', 'http://hima.invalid');
      try {
        send(res, await route(ops, req, url));
      } catch (err) {
        if (err instanceof BadRequest) { send(res, failure(400, 'hima/bad-request', err.message)); return; }
        if (err instanceof NotInState) { send(res, failure(409, 'hima/run-not-in-state', err.message)); return; }
        // Ticket #18: a Site that could not be asked, classified here for every route at once because
        // every one of them can reach a Site. Nothing was written, so there is nothing for the caller
        // to read back and the message itself is the answer; it is logged as well, because the
        // operator who has to go and look at that Site is reading the host log and not the response.
        if (err instanceof SiteUnreadableError) {
          ctx.logger.error(err);
          send(res, failure(503, 'hima/site-unreadable', err.message));
          return;
        }
        // The detail stays in the host's log, where an operator can read it; the body says only that
        // the fault was ours and which route it was on. A raw message here would put host paths and
        // errno text on the wire, to whoever asked.
        ctx.logger.error(err);
        send(res, failure(500, 'hima/internal', `${url.pathname} failed inside HimaHarness; the reason is in the host log`));
      }
    },
  });
  return () => { api(); page(); };
}
