"""critical_path_faster_cells: for each cell on a failing path, the faster drop-in cells at that instance's own
operating point, and the slower ones to don't-use.

The worst paths of a timing report (gzip or plain text, `report_timing` table format) are split into stages (an
instance's input pin row and output pin row). Each stage is read at its own operating point: the input slew and the
output load from the report's own columns when it has them; otherwise the load is the sum of the input
capacitances the output net drives in the gate-level netlist and the slew is carried along the path from the
previous stage's output transition. Without either, the stage falls back to fanout-of-4 (4x the cell's own input
capacitance at the reference inverter's fanout-of-4 slew) and says so (`from: fo4`). Equivalent cells share the
function (functional signature, so flops by their state function, not their name) and the track, at any VT.

Usage (from flow/):
  python3 -m libinsight_analysis.rules.critical_path_faster_cells --report top_reg2reg.tarpt.gz \
      --facts 9T-SVT=/corpus/svt_tt.json.gz --facts 9T-LVT=/corpus/lvt_tt.json.gz \
      --facts 9T-HVT=/corpus/hvt_tt.json.gz \
      [--netlist top.v] --naming dnum --out critical_path_faster_cells.json
"""
import argparse
import gzip
import os
import re
import sys
import time

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from libinsight_analysis.rules import facts as F  # noqa: E402
from libinsight_analysis.rules import netlists  # noqa: E402

RULE_ID = "critical_path_faster_cells"
MAX_PATHS = 12
MAX_EQ = 40
FASTER = 0.98                    # an equivalent is faster when below 98 % of the cell in use
TIME_UNITS = {"ns": 1000.0, "ps": 1.0}
CAP_UNITS = {"pf": 1000.0, "ff": 1.0}


# ---------------------------------------------------------------- the report

def _column(name):
    n = " ".join(name.lower().split())
    for key, words in (("pin", ("pin", "instance arc", "pin name")), ("edge", ("edge",)), ("net", ("net",)),
                       ("cell", ("cell", "ref name", "reference")), ("delay", ("delay", "incr")),
                       ("arrival", ("arrival time", "arrival")), ("required", ("required time", "required")),
                       ("slew", ("slew", "trans", "transition")), ("load", ("load", "cap", "capacitance")),
                       ("fanout", ("fanout",))):
        if n in words:
            return key
    return n


def _cells(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def read_report(path, time_unit="ns", cap_unit="pf"):
    """{design, tool, view, paths: [{slack, start, end, group, view, rows}]} with times in ps and loads in fF.
    Rows: {pin, edge, net, cell, delay, arrival, slew?, load?}."""
    opener = gzip.open if path.endswith(".gz") else open
    ts, cs = TIME_UNITS[time_unit.lower()], CAP_UNITS[cap_unit.lower()]
    out = {"design": None, "tool": None, "view": None, "paths": []}
    path_rec, state, header, cols = None, None, [], None
    with opener(path, "rt") as stream:
        for raw in stream:
            line = raw.rstrip("\n")
            s = line.strip()
            m = re.match(r"^#\s*Design:\s*(\S+)", s)
            if m:
                out["design"] = m.group(1)
            m = re.match(r"^#\s*Generated by:\s*(.+)$", s)
            if m:
                out["tool"] = " ".join(m.group(1).split()[:2])
            m = re.match(r"^Path\s+\d+:\s*(\w+)", s)
            if m:
                path_rec = {"status": m.group(1), "slack": None, "start": None, "end": None, "group": None,
                            "view": None, "rows": []}
                out["paths"].append(path_rec)
                state = None
                continue
            if path_rec is None:
                continue
            m = re.match(r"^Endpoint:\s*(\S+)", s)
            if m:
                path_rec["end"] = m.group(1)
            m = re.match(r"^Beginpoint:\s*(\S+)", s)
            if m:
                path_rec["start"] = m.group(1)
            m = re.match(r"^Path Groups?:\s*\{?\s*([^}]*)\}?", s)
            if m:
                path_rec["group"] = m.group(1).strip()
            m = re.match(r"^Analysis View:\s*(\S+)", s)
            if m:
                path_rec["view"] = m.group(1)
                out["view"] = out["view"] or m.group(1)
            m = re.match(r"^=\s*Slack Time\s+(\S+)", s)
            if m:
                path_rec["slack"] = F.num(m.group(1)) * ts if F.num(m.group(1)) is not None else None
            if s.startswith("Timing Path"):
                state, header, cols = "head", [], None
                continue
            if s.startswith("Other End Path") or s.startswith("Clock Path"):
                state = None
                continue
            if state == "head":
                if s.startswith("|-") or s.startswith("|="):
                    width = max(len(h) for h in header)
                    merged = [" ".join(h[k] for h in header if k < len(h)).strip() for k in range(width)]
                    cols = [_column(c) for c in merged]
                    state = "rows"
                elif s.startswith("|"):
                    header.append(_cells(s))
                continue
            if state == "rows":
                if not s.startswith("|"):
                    state = None if s.startswith("+") or not s else state
                    continue
                vals = dict(zip(cols, _cells(s)))
                row = {"pin": vals.get("pin", ""), "edge": vals.get("edge", ""), "net": vals.get("net", ""),
                       "cell": vals.get("cell", "")}
                for key, scale in (("delay", ts), ("arrival", ts), ("slew", ts), ("load", cs)):
                    v = F.num(vals.get(key))
                    row[key] = None if v is None else v * scale
                path_rec["rows"].append(row)
    return out


def stages(rows):
    """Stages (one instance's input row and output row): {inst, cell, src, dst, edge, d, slew, load, net}."""
    out = []
    for a, b in zip(rows, rows[1:]):
        if not a["cell"] or a["cell"] != b["cell"] or "/" not in a["pin"] or "/" not in b["pin"]:
            continue
        ia, pa = a["pin"].rsplit("/", 1)
        ib, pb = b["pin"].rsplit("/", 1)
        if ia != ib or pa == pb:
            continue
        edge = "fall" if b["edge"] in ("v", "f", "F", "fall") else "rise"
        out.append({"inst": ia, "cell": a["cell"], "src": pa, "dst": pb, "edge": edge, "d": b["delay"],
                    "slew": a.get("slew"), "load": b.get("load"), "net": b["net"], "out_pin": b["pin"]})
    return out


# ---------------------------------------------------------------- the library side

def _arcs_for(rec, src, dst):
    arcs = [a for a in rec["arcs"] or [] if a["from"] == src and a["to"] == dst]
    plain = [a for a in arcs if not a["when"]]
    return plain or arcs


def delay_at(rec, src, dst, edge, slew, load):
    """(delay ps, output transition ps) of the src->dst arc on the output edge at (slew, load); the worst arc when
    only conditional ones exist. None when the cell has no such arc."""
    best = None
    for a in _arcs_for(rec, src, dst):
        d = F.arc_delay(a, slew, load, (edge,))[0]
        if d is None:
            continue
        if best is None or d > best[0]:
            best = (d, F.arc_transition(a, slew, load, edge))
    return best


def run(inputs, report, netlist=None, top=None, naming="generic", max_paths=MAX_PATHS, design=None, library=None,
        time_unit="ns", cap_unit="pf"):
    """inputs: [(variant label, facts path)] at the report's corner, one per VT of the design's track."""
    namer = naming if isinstance(naming, F.Naming) else F.Naming(naming)
    rep = read_report(report, time_unit, cap_unit)
    all_paths = [p for p in rep["paths"] if p["slack"] is not None and p["rows"]]
    if not all_paths:
        raise F.RuleError("the timing report %s holds no path table this rule can read" % report)
    all_paths.sort(key=lambda p: p["slack"])
    chosen = all_paths[:max_paths]
    row_cells = set(r["cell"] for p in chosen for r in p["rows"] if r["cell"])

    # pass 1: every file's cell index (signature, track, caps), and its fanout-of-4 point
    index, fo4, corners, libnames = {}, {}, set(), []
    for k, (label, path) in enumerate(inputs):
        lib = F.load_facts(path)
        corners.add(F.corner_words(F.corner(lib)))
        libnames.append(lib.get("name") or label)
        cells = F.read_cells(lib, namer, label, keep=F.is_inverter)
        del lib
        inv = F.reference_inverter(cells)
        fo4[k] = F.fo4_point(cells, inv) if inv else None
        for name, rec in cells.items():
            if name not in index:
                rec["arcs"] = None
                rec["file"] = k
                index[name] = rec
        del cells
    stage_cells = set()
    for p in chosen:
        st = stages(p["rows"])
        begin = next((i for i, s in enumerate(st) if s["out_pin"] == p["start"]), 0)
        stage_cells |= set(s["cell"] for s in st[begin:])
    keys = set((index[c]["sig"], index[c]["track"]) for c in stage_cells if c in index and index[c]["sig"])
    wanted = set(n for n, r in index.items() if r["sig"] and (r["sig"], r["track"]) in keys) | (row_cells & set(index))

    # pass 2: delay arcs of the cells on the paths and their equivalents only
    recs = {}
    for k, (label, path) in enumerate(inputs):
        if not any(index[n]["file"] == k for n in wanted):
            continue
        lib = F.load_facts(path)
        cells = F.read_cells(lib, namer, label, keep=lambda r: r["name"] in wanted and index[r["name"]]["file"] == k)
        del lib
        for n in wanted:
            if index[n]["file"] == k:
                recs[n] = cells[n]
        del cells

    design_nl = netlists.Design(netlist, top) if netlist else None
    eq_of = {}
    for n, r in recs.items():
        if r["sig"]:
            eq_of.setdefault((r["sig"], r["track"]), []).append(n)

    def sink_load(net):
        if design_nl is None or not net:
            return None
        pins = design_nl.pins_on(net)
        if not pins:
            return None
        total = 0.0
        for inst, cell, pin in pins:
            rec = index.get(cell)
            if rec is None or pin not in rec["pins"]:
                return None
            p = rec["pins"][pin]
            if p["dir"] in ("input", "inout"):
                if p["cap"] is None:
                    return None
                total += p["cap"]
        return total

    paths_out, judged, faster_stages, from_counts, used = [], 0, 0, {"report": 0, "fo4": 0}, set()
    for p in chosen:
        st = stages(p["rows"])
        begin = next((i for i, s in enumerate(st) if s["out_pin"] == p["start"]), 0)
        carried = None
        rows = []
        for i, s in enumerate(st):
            rec = recs.get(s["cell"])
            ref = fo4.get(index[s["cell"]]["file"] if s["cell"] in index else 0)
            slew, slew_from = s["slew"], "report"
            if slew is None:
                slew, slew_from = carried, "carried"
            load, load_from = s["load"], "report"
            if load is None:
                load, load_from = sink_load(s["net"]), "netlist"
            op_from = "report"
            if rec is None:
                carried = None
                if i >= begin:
                    rows.append({"inst": s["inst"], "cell": s["cell"], "s": namer.parse(s["cell"])["label"],
                                 "arc": F.arc_words(s["src"], s["dst"], s["edge"]), "d": F.rnd(s["d"], 2),
                                 "cls": "not in the facts given", "op": {"slew": None, "load": None, "from": "fo4"},
                                 "nfast": 0, "best": None, "eq": [],
                                 "focus": F.clip("%s is not in the facts files given, so its equivalents are not "
                                                 "judged." % s["cell"], 400)})
                continue
            arcs = _arcs_for(rec, s["src"], s["dst"])
            basis = F.load_basis(rec["pins"], arcs[0]) if arcs else None
            if slew is None:
                slew, slew_from = (ref["slew"] if ref else None), "fo4"
            if load is None:
                load, load_from = (4.0 * basis if basis else None), "fo4"
            if slew_from == "fo4" or load_from == "fo4":
                op_from = "fo4"
            mine = None
            if slew is not None and load is not None:
                mine = delay_at(rec, s["src"], s["dst"], s["edge"], slew, load)
            carried = mine[1] if mine else None
            if i < begin:
                continue
            judged += 1
            from_counts[op_from] += 1
            used.add(s["cell"])
            eq = []
            for n in eq_of.get((rec["sig"], rec["track"]), [s["cell"]]):
                e = recs[n]
                got = delay_at(e, s["src"], s["dst"], s["edge"], slew, load) if mine else None
                if got is None:
                    continue
                eq.append({"name": n, "s": e["label"], "vt": e["vt"], "d": F.rnd(got[0], 2), "a": F.rnd(e["area"], 4),
                           "l": F.rnd(e["leak"], 4)})
            eq.sort(key=lambda e: (e["d"], e["a"] or 0, e["name"]))
            if mine and not any(e["name"] == s["cell"] for e in eq[:MAX_EQ]):
                eq = [e for e in eq if e["name"] != s["cell"]][:MAX_EQ - 1] + [e for e in eq if e["name"] == s["cell"]]
            eq = eq[:MAX_EQ]
            d_mine = mine[0] if mine else None
            faster = [e for e in eq if d_mine is not None and e["name"] != s["cell"] and e["d"] < FASTER * d_mine]
            best = min(e["d"] for e in eq) if eq else None
            if faster:
                faster_stages += 1
            src_words = {"report": "from the report", "netlist": "from the netlist pins", "carried":
                         "carried from the previous stage", "fo4": "fanout-of-4 fallback"}
            op_words = "no operating point"
            if slew is not None and load is not None:
                op_words = "slew %.3g ps (%s), load %.3g fF (%s)" % (slew, src_words[slew_from], load, src_words[load_from])
            if faster:
                tip = "%d equivalent%s faster; the fastest, %s, takes %.3g ps" % (
                    len(faster), " is" if len(faster) == 1 else "s are", faster[0]["s"], faster[0]["d"])
            else:
                tip = "no equivalent is faster"
            rows.append({
                "inst": s["inst"], "cell": s["cell"], "s": rec["label"],
                "arc": F.arc_words(s["src"], s["dst"], s["edge"]), "d": F.rnd(s["d"], 2), "cls": rec["cls"],
                "op": {"slew": F.rnd(slew, 3), "load": F.rnd(load, 4), "from": op_from},
                "nfast": len(faster), "best": F.rnd(best, 2), "eq": eq,
                "focus": F.clip("%s (%s) %s takes %s ps in the report and %s ps from its tables at %s; %s." % (
                    s["inst"], rec["label"], F.arc_words(s["src"], s["dst"], s["edge"]),
                    "?" if s["d"] is None else "%.3g" % s["d"], "?" if d_mine is None else "%.3g" % d_mine, op_words,
                    tip), 400),
                "_mine": d_mine})
        gain = sum(max(0.0, r["_mine"] - r["best"]) for r in rows
                   if r.get("_mine") is not None and r["best"] is not None)
        for r in rows:
            r.pop("_mine", None)
        paths_out.append({"slack": F.rnd(p["slack"], 2), "start": p["start"], "end": p["end"],
                          "total": F.rnd(sum(r["d"] for r in rows if r["d"] is not None), 2), "gain": F.rnd(gain, 2),
                          "rows": rows})
    fail = sum(1 for p in all_paths if p["slack"] < 0 or (p["status"] or "").upper() == "VIOLATED")
    wns = all_paths[0]["slack"]
    name = design or rep["design"] or "design"
    corner_words = ", ".join(sorted(corners))
    top_gain = max([p["gain"] or 0 for p in paths_out] or [0])
    rule = {
        "id": RULE_ID, "kind": "path", "title": "Critical-path cell choice",
        "summary": "For each cell on a failing path: the faster drop-in cells, and the slower ones to don't-use.",
        "result": F.clip("%s · %s · up to %.0f ps faster" % (F.count_words(len(paths_out), "worst path"),
                                                             F.count_words(len(used), "cell"), top_gain), 120),
        "rule": F.clip("Equivalent = same function, same track, any VT. Faster = lower delay at the instance's own "
                       "input slew and output load (from the report, the netlist, or fanout-of-4 when neither has "
                       "them) at the report's corner. Slower equivalents become don't-use candidates.", 400),
        "library": F.clip("%s · %d variants · %d corner%s · %s cells" % (
            library or " / ".join(libnames[:3]), len(inputs), len(corners), "" if len(corners) == 1 else "s",
            "{:,}".format(len(index))), 160),
        "facts": [["Design", name], ["Failing paths in the report", fail], ["Worst slack", "%.0f ps" % wns],
                  ["Paths shown", len(paths_out)], ["Distinct cells on these paths", len(used)],
                  ["Stages with a faster equivalent", "%d of %d" % (faster_stages, judged)],
                  ["Stages at their own slew and load", from_counts["report"]],
                  ["Stages on the fanout-of-4 fallback", from_counts["fo4"]],
                  ["Library corner", F.clip(corner_words, 80)]],
        "score": {"dimension": "none", "affected": faster_stages, "checked": judged, "weight": 0},
        "impact": [
            ["Timing", F.clip("Up to %.0f ps on one path if every stage took its fastest equivalent; the worst "
                              "slack is %.0f ps." % (top_gain, wns), 300)],
            ["Leakage", "Faster equivalents are often lower VT or larger: check the leakage and area columns before "
                        "you swap."],
            ["Repair", "A don't-use list on the slower equivalents steers the setup repair towards the faster ones."]],
        "todo": [
            {"who": "chip_designer", "text": "Tick the slower equivalents to build the don't-use file; load it for "
                                             "the setup-repair step only, then reset it."},
            {"who": "chip_designer", "text": "Re-run setup repair and re-time; keep the swaps that close the paths."},
            {"who": "note", "text": "Delays are read at each stage's own slew and load; stages marked fanout-of-4 "
                                    "had neither in the report or the netlist."}],
        "hint": "The worst paths of the report, worst slack first.",
        "design": {"name": name, "lib": library or " / ".join(sorted(set(libnames)))[:120],
                   "flow": "%s timing report%s" % (rep["tool"] or "Static", ", group %s" % chosen[0]["group"]
                                                   if chosen[0]["group"] else ""),
                   "corner": "%s · facts at %s" % (rep["view"] or "report corner", corner_words),
                   "fail": fail, "wns": F.rnd(wns, 2)},
        "paths": paths_out,
        "items": [dict(r, label=F.clip("%s · %s" % (r["inst"], r["s"]), 60), path=k)
                  for k, p in enumerate(paths_out) for r in p["rows"] if r["nfast"]][:400]}
    return rule


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--report", required=True, help="timing report (report_timing table format, .gz or text)")
    ap.add_argument("--facts", action="append", required=True, help="VARIANT=PATH at the report's corner (repeat)")
    ap.add_argument("--netlist", help="gate-level Verilog netlist of the design, for the instance loads")
    ap.add_argument("--top", help="top module of the netlist (default: the one nothing instantiates)")
    ap.add_argument("--naming", default="generic", help="naming profile: generic, dnum, or a JSON file")
    ap.add_argument("--max-paths", type=int, default=MAX_PATHS)
    ap.add_argument("--design", help="design name for the page (default: the report's)")
    ap.add_argument("--library", help="library name for the page header")
    ap.add_argument("--time-unit", default="ns", choices=sorted(TIME_UNITS), help="the report's time unit")
    ap.add_argument("--cap-unit", default="pf", choices=sorted(CAP_UNITS), help="the report's load unit")
    ap.add_argument("--out", default="-")
    args = ap.parse_args(argv)
    start = time.time()
    try:
        rule = run(F.parse_inputs(args.facts), args.report, args.netlist, args.top, args.naming,
                   min(args.max_paths, 12), args.design, args.library, args.time_unit, args.cap_unit)
    except F.RuleError as exc:
        sys.stderr.write("%s: %s\n" % (RULE_ID, exc))
        return 2
    F.write_rule(rule, args.out)
    sys.stderr.write("%s: %s in %.1f s\n" % (RULE_ID, rule["result"], time.time() - start))
    return 0


if __name__ == "__main__":
    sys.exit(main())
