"""PrimeTime (PT) report parsers.

Grammar ported and adapted (read-only reference, not imported) from
``packs/xtop-timing-closure/flow/closure.py``'s ``parse_global`` and
``parse_endpoints``, and cross-checked against the synthesized fixtures at
``packs/xtop-timing-closure/flow/tests/test_closure.py:26-58``
(``global_report``, ``path_report``). This module never imports from the old
Pack; it re-implements the same report grammar under the new fail-closed
Measure contract (`atcs.core.known`/`unknown`) required for this Pack.

Three report kinds are parsed:

- ``global_timing.rpt`` — via `parse_global_timing`. Two blocks
  (``Setup violations`` / ``Hold violations``), each either a
  ``No <mode> violations found.`` line (explicit zero) or a
  ``WNS``/``TNS``/``NUM`` table. Returns
  ``{"setup": {"wns": Measure, "tns": Measure, "violations": Measure},
  "hold": {...}}``. A block that is neither an explicit-zero line nor a
  parseable table (e.g. the ``Hold violations`` section is entirely absent
  from the text) yields `unknown` Measures for all three fields of that
  mode, never a silently-assumed zero. A field whose text is non-finite
  (``inf``/``nan``, in any case) also yields `unknown` rather than a
  numeric value — Python's ``float()`` happily parses those strings, so
  this is checked explicitly.

- ``setup.rpt`` / ``hold.rpt`` (worst-path reports) — via
  `parse_path_report`. Splits the text on ``Startpoint:`` markers (each
  block then holds one path's ``Startpoint``, ``Endpoint``, ``Path Group``,
  ``Path Type`` and ``slack (VIOLATED...) <value>`` lines). Returns
  ``{"paths": [{"endpoint", "startpoint", "pathGroup", "slack" (Measure),
  "violated" (bool, always `True`)}, ...], "complete": bool}``.

  The slack line's parenthetical is matched as ``VIOLATED`` plus *any*
  trailing annotation PT appends (confirmed against the real Foundation/
  B_lazy corpus: ``slack (VIOLATED: increase significant digits)``, which
  PT emits whenever a violation's magnitude rounds to a displayed ``-0.00``
  — a real, common occurrence near timing closure, and one this Pack's own
  `pt-scenario.tcl` will genuinely produce, even after it raised
  `-significant_digits` to 4 — see `knowledge/observation-strategy.md`).
  PT's own classification (this row was ``VIOLATED``, never ``MET``) is
  recorded as the boolean fact `violated` on every row this function
  returns — always `True` here, since a `slack (MET)` row never reaches
  this point (see below) — *independently* of whether the row's own
  displayed slack number is trustworthy. When the annotation is present
  (the "increase significant digits" case), the row's own slack `Measure`
  is `unknown("precision-limited: re-query with more significant digits")`
  rather than the displayed number: `float("-0.00") < 0` is `False` in
  Python, so a consumer that inferred violation from the numeric sign alone
  would silently treat a violation PT itself confirmed as clean. `violated`
  and `slack` are two different facts (verdict vs. magnitude) and must
  never be collapsed into one; `atcs.state.compare_checks` reads `violated`
  first, precisely so a precision-limited row is still counted as
  violating even though its own slack Measure is `unknown` (confirmed
  empirically: every one of the real Foundation/B_lazy corpus's 73
  annotated rows displays exactly ``-0.00``, and zero *unannotated*
  ``(VIOLATED)`` rows anywhere in that corpus display ``-0.00``/``0.00`` —
  PT itself never leaves this ambiguity unannotated).

  A block whose slack line reads ``slack (MET)`` instead (a *non*-violating
  path) is not a violated-path row at all and is treated as missing its
  required slack field — this Pack's own `report_timing` invocation always
  requests ``-slack_lesser_than 0.0``, so a real `setup.rpt`/`hold.rpt`
  this Pack generates never contains a ``(MET)`` row in the first place
  (confirmed against the real B_lazy corpus, generated with that same
  flag: zero ``(MET)`` rows). Only the *historical* Foundation corpus —
  generated by the old, frozen flow's own script with a more permissive
  ``-slack_lesser_than 1000.00`` — legitimately mixes ``(MET)`` rows in,
  and correctly still refuses there
  (``docs/assessment/2026-09-26/atcs-qualification/corpus-preflight.md``
  records this as an intentional, documented outcome for that historical
  reference material, not a defect in this Pack's own report contract).

  ``complete`` is `False` when either:
  (a) the report's own *raw* path count (every `Startpoint:` block, before
      the same-endpoint collapsing described below) reaches `max_paths`
      (the tool's own cap was hit, so more paths may exist beyond what was
      reported) — this is checked against the raw block count, not the
      deduplicated `paths` list, since `-max_paths` bounds how many paths
      PT itself emits, not how many distinct endpoints they land on, or
  (b) the report's last block is missing required fields (the report file
      was truncated mid-path, e.g. the tool was killed while writing).
  A non-trailing block missing required fields is not a truncation — it is
  a malformed report — and raises `AtcsError("malformed-report", ...)`.

  This Pack's check key (`atcs.core.check_key`) is
  ``"<scenario>|<mode>|<endpoint>"`` and deliberately does **not** include
  the path group. This Pack's own default query breadth
  (`atcs.adapters.DEFAULT_NWORST = 20`) means a real `setup.rpt`/`hold.rpt`
  routinely reports several of an endpoint's worst-`N` paths, all sharing
  one path group — confirmed against the real Foundation/B_lazy corpus
  (``docs/assessment/2026-09-26/atcs-qualification/corpus-preflight.md``:
  every duplicated endpoint's repeats shared exactly one path group, zero
  exceptions across four scenarios). Refusing every such report as this
  Pack's own default configuration is guaranteed to produce would leave M1
  observation permanently non-functional, so `parse_path_report` instead
  keeps the *worst* (most negative) slack among same-endpoint/same-path-
  group repeats — this Pack's check key only ever needs the one slack that
  can matter for a Goal/violation count, and the worst is it. A repeated
  endpoint whose rows disagree on path *group*, though, is the genuinely
  ambiguous case the original design meant to catch (which group's slack
  is "the" check's value is not decidable from the report alone) and still
  refuses the whole report as `AtcsError("duplicate-check", <endpoint>)`.
  `mode` must be `"setup"` or `"hold"`; a row's `Path Type` (`max` for
  setup, `min` for hold) is cross-checked against `mode` and a mismatch
  raises `AtcsError("identity-mismatch", ...)` — a real PT report never
  mixes these, so a mismatch means the wrong file was fed to the wrong
  `mode`.

- ``check_timing.rpt`` — via `parse_check_timing`, looking for
  ``There are <N> endpoints which are not constrained`` with `N` a
  non-negative integer literal (no leading `-`; a negative count is not a
  real PT output and is treated the same as no line at all). Returns
  ``{"unconstrainedEndpoints": Measure}``. Per the fail-closed rule, `0` is
  only produced when the report explicitly states a count of 0 for that
  line; a report with no such line at all (never generated, or a different
  tool output entirely) yields `unknown`, unlike the old Pack's parser
  (`packs/xtop-timing-closure/flow/closure.py:unconstrained`) which
  defaulted a missing line to `0`.
"""
from __future__ import annotations

import math
import re

from . import core


_ZERO_VIOLATIONS_RE = {
    "setup": re.compile(r"(?mi)^\s*No setup violations found\.\s*$"),
    "hold": re.compile(r"(?mi)^\s*No hold violations found\.\s*$"),
}

_GLOBAL_BLOCK_RE = {
    "setup": re.compile(r"Setup violations\s*\n-+\n.*?\n-+\n(.*?)\n-+", re.S),
    "hold": re.compile(r"Hold violations\s*\n-+\n.*?\n-+\n(.*?)\n-+", re.S),
}

_STARTPOINT_SPLIT_RE = re.compile(r"(?m)^\s*Startpoint:\s*")
_STARTPOINT_VALUE_RE = re.compile(r"^\s*(\S+)")
_ENDPOINT_RE = re.compile(r"(?m)^\s*Endpoint:\s*(\S+)")
_PATH_GROUP_RE = re.compile(r"(?m)^\s*Path Group:\s*(\S+)")
_PATH_TYPE_RE = re.compile(r"(?m)^\s*Path Type:\s*(\S+)")
_SLACK_RE = re.compile(r"(?m)^\s*slack\s*\(VIOLATED(?P<annotation>[^)]*)\)\s+(?P<value>-?[0-9.eE+]+)")
_UNCONSTRAINED_RE = re.compile(r"There are\s+(\d+)\s+endpoints which are not constrained")

_EXPECTED_PATH_TYPE = {"setup": "max", "hold": "min"}


def _finite_float_measure(raw):
    try:
        value = float(raw)
    except (TypeError, ValueError):
        return core.unknown(f"unparsable-value: {raw!r}")
    if math.isnan(value) or math.isinf(value):
        return core.unknown(f"non-finite-value: {raw!r}")
    return core.known(value)


def _finite_int_measure(raw):
    try:
        value = int(raw)
    except (TypeError, ValueError):
        return core.unknown(f"unparsable-value: {raw!r}")
    return core.known(value)


def parse_global_timing(text):
    """Parse a ``global_timing.rpt`` into `{"setup": {...}, "hold": {...}}` Measures."""
    result = {}
    for mode in ("setup", "hold"):
        if _ZERO_VIOLATIONS_RE[mode].search(text):
            result[mode] = {
                "wns": core.known(0.0),
                "tns": core.known(0.0),
                "violations": core.known(0),
            }
            continue
        block_match = _GLOBAL_BLOCK_RE[mode].search(text)
        if not block_match:
            reason = f"missing-{mode}-section"
            result[mode] = {
                "wns": core.unknown(reason),
                "tns": core.unknown(reason),
                "violations": core.unknown(reason),
            }
            continue
        body = block_match.group(1)
        wns_match = re.search(r"(?m)^WNS\s+(\S+)", body)
        tns_match = re.search(r"(?m)^TNS\s+(\S+)", body)
        num_match = re.search(r"(?m)^NUM\s+(\S+)", body)
        result[mode] = {
            "wns": _finite_float_measure(wns_match.group(1)) if wns_match else core.unknown("missing-wns-row"),
            "tns": _finite_float_measure(tns_match.group(1)) if tns_match else core.unknown("missing-tns-row"),
            "violations": _finite_int_measure(num_match.group(1)) if num_match else core.unknown("missing-num-row"),
        }
    return result


def parse_path_report(text, mode, max_paths):
    """Parse a worst-path report (``setup.rpt``/``hold.rpt``) into path rows + completeness."""
    if mode not in _EXPECTED_PATH_TYPE:
        raise core.AtcsError("invalid-mode", mode)
    if max_paths < 1:
        raise core.AtcsError("invalid-max-paths", str(max_paths))

    blocks = _STARTPOINT_SPLIT_RE.split(text)[1:]
    total_blocks = len(blocks)
    truncated = False
    order = []
    kept = {}
    kept_groups = {}

    for index, block in enumerate(blocks):
        is_last = index == total_blocks - 1
        startpoint_match = _STARTPOINT_VALUE_RE.search(block)
        endpoint_match = _ENDPOINT_RE.search(block)
        slack_match = _SLACK_RE.search(block)
        if not (startpoint_match and endpoint_match and slack_match):
            if is_last:
                truncated = True
                continue
            raise core.AtcsError("malformed-report", f"incomplete path block at index {index}")

        type_match = _PATH_TYPE_RE.search(block)
        if type_match and type_match.group(1) != _EXPECTED_PATH_TYPE[mode]:
            raise core.AtcsError(
                "identity-mismatch",
                f"path type {type_match.group(1)!r} does not match mode {mode!r}",
            )

        endpoint = endpoint_match.group(1)
        try:
            raw_slack = float(slack_match.group("value"))
        except ValueError:
            raise core.AtcsError("malformed-report", f"unparsable slack {slack_match.group('value')!r}")
        if math.isnan(raw_slack) or math.isinf(raw_slack):
            raise core.AtcsError("malformed-report", f"non-finite slack {slack_match.group('value')!r}")
        precision_limited = bool(slack_match.group("annotation"))

        group_match = _PATH_GROUP_RE.search(block)
        path_group = group_match.group(1) if group_match else "unknown"

        if endpoint in kept:
            if path_group != kept_groups[endpoint]:
                raise core.AtcsError("duplicate-check", endpoint)
            if raw_slack >= kept[endpoint]["_rawSlack"]:
                # a less-critical repeat from the tool's own -nworst>1
                # listing of this endpoint's worst paths -- the one already
                # kept is at least as bad, so this row contributes nothing.
                continue
        else:
            order.append(endpoint)

        # `violated` is PT's own classification fact for this row (every row
        # here is one PT itself labeled VIOLATED -- a `slack (MET)` row never
        # reaches this point, see the module docstring) and is always
        # recorded even when the displayed number itself is precision-
        # limited: a real violation that happens to round to a displayed
        # "-0.00" is still `slack (VIOLATED: increase significant digits)`
        # by PT's own verdict, and `float("-0.00") < 0` is `False` in Python
        # -- a consumer that trusted the numeric sign alone would silently
        # treat a confirmed violation as clean. The slack Measure for such a
        # row is `unknown` (the *value* is not trustworthy at this display
        # precision) while `violated` stays a known `True` (the *verdict*
        # is) -- these are never the same fact and must never be collapsed
        # into one.
        slack_measure = (
            core.unknown("precision-limited: re-query with more significant digits")
            if precision_limited else core.known(raw_slack)
        )
        kept[endpoint] = {
            "endpoint": endpoint,
            "startpoint": startpoint_match.group(1),
            "pathGroup": path_group,
            "slack": slack_measure,
            "violated": True,
            "_rawSlack": raw_slack,
        }
        kept_groups[endpoint] = path_group

    paths = [{k: v for k, v in kept[endpoint].items() if k != "_rawSlack"} for endpoint in order]
    complete = (not truncated) and total_blocks < max_paths
    return {"paths": paths, "complete": complete}


def parse_check_timing(text):
    """Parse a ``check_timing.rpt`` into ``{"unconstrainedEndpoints": Measure}``."""
    match = _UNCONSTRAINED_RE.search(text)
    if not match:
        return {"unconstrainedEndpoints": core.unknown("missing-unconstrained-line")}
    return {"unconstrainedEndpoints": _finite_int_measure(match.group(1))}
