// @hima-seam tools direct
// Seal the exact full-method bytes exercised by a retained local Host test. No model or EDA rerun.
import assert from 'node:assert/strict';
import { isDeepStrictEqual } from 'node:util';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { packDigestOf, packStage } from '@hima/harness';
import { bootInProcess, resumeTestAgent } from '../test/contract/support/boot-inprocess.ts';
import type { HimaHome } from '../test/contract/support/dsh-home.ts';
import { sha256 } from './live-check-workshop.ts';

const [from, out] = process.argv.slice(2);
assert.ok(from && out && !existsSync(out), 'retained full-graph evidence and a fresh output directory required');
const originalBytes = readFileSync(from);
const raw = JSON.parse(originalBytes.toString());
assert.equal(raw.status, 'passed');
assert.equal(raw.scope, 'L2 complete graph with explicit synthetic external boundaries');
assert.equal(raw.run.packId, 'aes-tsmc28-dtco');
assert.equal(raw.run.purpose, 'test');
assert.equal(raw.run.status, 'ended-goal-met');
assert.equal(raw.modelRequests, 0);
assert.equal(raw.realEdaJobs, 0);
const folder = raw.packFolder as string;
assert.equal(packDigestOf(folder), raw.run.packDigest);
assert.equal(packDigestOf(path.resolve('packs/aes-tsmc28-dtco')), raw.run.packDigest, 'release only current tested source');
assert.equal(packStage(folder).stage, 'compiled');
assert.ok(!existsSync(path.join(folder, 'TEST.md')) && !existsSync(path.join(folder, 'VERSION.yml')));
delete process.env.DEEPSEEK_API_KEY;
process.env.HIMA_TEST_SILENT_AGENT = '1';
const home: HimaHome = { home: raw.home, profileDir: path.join(raw.home, 'profiles/hima'), workspace: path.join(raw.home, 'workspace'),
  env: { ...process.env, DSH_HOME: raw.home, DSH_AGENTS_HOME: path.join(raw.home, 'agents'), DSH_TELEMETRY_DISABLED: '1' }, dispose: async () => undefined };
mkdirSync(out, { recursive: true });
const host = await bootInProcess(home);
let requests = 0;
host.ctx.on('agent/request', () => { requests++; throw new Error('mechanical release forbids model requests'); });
const handle = await resumeTestAgent(host.ctx, raw.owner, raw.agentOptions);
try {
  const run = host.ctx.hima.ledger.run(raw.run.id)!;
  const records = host.ctx.hima.ledger.records({ runId: run.id });
  assert.ok(isDeepStrictEqual(run, raw.run));
  assert.ok(isDeepStrictEqual(records, raw.records));
  assert.equal(String(handle.agent.id), run.control!.owner);
  const codes = records.filter(r => r.type === 'code');
  assert.equal(codes.length, 6);
  const refusals = records.filter(r => r.type === 'refusal');
  const workspace = records.find(r => r.type === 'workspace' && r.event === 'prepared');
  assert.ok(workspace?.type === 'workspace');
  for (const code of codes) assert.equal(sha256(readFileSync(code.path)), code.sha256);
  const test = `## Site\n\nSite: local. Fixture: ${raw.fixture}. Workspace: ${workspace.workspace}.\nThis is the real Host, Pack, owner/Job/reader/Ledger path with explicitly synthetic external tools,\nmining sample and timing/geometry outputs. Zero real EDA/model requests. No foundry, PPA or research\nconclusion is inferred from this test. Bounded real tool/model evidence is separate in\ndocs/validation/pls-frontier/mining-handoff.md; full research acceptance belongs to PLS-18.\n\n## Run\n\nrun: ${run.id}\n\nMethod digest: ${run.packDigest}. Goal: ${JSON.stringify(run.goal)}.\nInitial strategy: ${JSON.stringify(run.firstStrategy)}. Budget: ${JSON.stringify(run.budget)}.\nPurpose: test. The same native owner explicitly requested every business node.\n\n## Ending\n\nstatus: ${run.status}\n\nThe fixture's final independent reading passed both full-evidence-valid and clock-period-at-most,\nthen next-research requested goalMet. This ending applies only to synthetic fixture conditions.\n\n## Generations\n\nOne outer generation and its nested probe flow completed. Six branches each mined, selected and\nread candidates, followed by merge, cell generation/layout/predicted characterization, library gate,\npaired synthesis/P&R, verification and comparison. Synthetic tool outputs exercise the complete\ncontract; they do not validate actual tool behavior. Owner code was supplied by the test harness,\nnot generated by a live model. Actual live model research is separately identified in the handoff.\n\n## Code\n\n${codes.map(c => `- ${c.sha256} — ${c.path} — node ${c.nodeId}, attempt ${c.attempt}, generation ${c.generation}; ${c.id}`).join('\n')}\n\n## Refusals\n\n${refusals.length ? refusals.map(r => `- ${r.id}: ${JSON.stringify(r)}`).join('\n') : 'none'}\n\n## Disagreements\n\nNo discrepancy was observed between this declared local fixture and its recorded ending.\nThe local fixture intentionally substitutes the external EDA/characterization boundaries.\nThis engineering-authored TEST is derived from original records; no Run record is modified.\n`;
  writeFileSync(path.join(folder, 'TEST.md'), test);
  assert.equal(packDigestOf(folder), run.packDigest);
  const result = await host.ctx.tools.execute({ name: 'hima_pack_release', arguments: { pack: 'aes-tsmc28-dtco' },
    agent: handle.agent, callId: 'full-method-native-release' as never, signal: AbortSignal.timeout(30_000) });
  assert.equal(result.isError, false, JSON.stringify(result));
  assert.equal(packStage(folder).stage, 'released');
  assert.ok(isDeepStrictEqual(run, host.ctx.hima.ledger.run(run.id)));
  assert.ok(isDeepStrictEqual(records, host.ctx.hima.ledger.records({ runId: run.id })));
  assert.equal(requests, 0);
  assert.deepEqual(readFileSync(from), originalBytes);
  for (const name of ['TEST.md', 'VERSION.yml']) writeFileSync(path.join(out, name), readFileSync(path.join(folder, name)));
  writeFileSync(path.join(out, 'evidence.json'), JSON.stringify({ status: 'passed', scope: raw.scope,
    from: { path: path.resolve(from), sha256: sha256(originalBytes) }, runId: run.id, methodDigest: run.packDigest,
    owner: raw.owner, packFolder: folder, hosts: 1, modelRequests: requests, newResearchJobs: 0, realEdaJobs: 0,
    release: result, testSha256: sha256(test), versionSha256: sha256(readFileSync(path.join(folder, 'VERSION.yml'))) }, null, 2) + '\n');
  process.stdout.write('full-method native release PASS; zero model/EDA requests; synthetic local acceptance only\n');
} finally { await handle.dispose(); await host.dispose(); }
