// Real frozen Pack/domain adaptation is verified by a private PG/DBOS child process.
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dbosHome, cleanDbosHome } from './support/dbos-process.ts';
test('legacy declarations use frozen Reader/Judge/chooser and deliver sourced negative output through DBOS', { timeout: 90000 }, async () => {
  const home = await dbosHome();
  const child = spawn(process.execPath, [fileURLToPath(new URL('./support/durable-task-adapters-worker.ts', import.meta.url)), home], { env: process.env, stdio: ['ignore', 'pipe', 'pipe', 'ipc'] });
  let stderr = ''; child.stderr!.on('data', value => stderr += value);
  try {
    const answer = await new Promise<any>((resolve, reject) => { child.once('message', resolve); child.once('close', code => reject(new Error(`Bridge worker exited ${code}: ${stderr}`))); });
    assert.equal(answer.ok, true);
    assert.equal(answer.goalMet, false);
    assert.equal(answer.originalJobCalls, 2);
    assert.equal(answer.readerCalls, 2);
  } finally {
    if (child.exitCode === null) { child.send({ action: 'close' }); await new Promise(resolve => child.once('close', resolve)); }
    await cleanDbosHome(home);
  }
});


test('Workshop explicit observe supplies the current Reader fact to the actual Team Operator', {timeout:45000}, async()=>{
 const fs=await import('node:fs/promises'),path=(await import('node:path')).default,{pathToFileURL}=await import('node:url'),{stringify}=await import('yaml');
 const {createHimaHome,repoRoot}=await import('./support/dsh-home.ts'),{bootInProcess,createPresetRootAgent}=await import('./support/boot-inprocess.ts'),{writeMomentFixture,appendReplaySession}=await import('./support/moments.ts'),{writeReplayOverlay,homePatchFile}=await import('../../packages/desktop/src/hima-home.ts');
 const at=(name:string)=>import(pathToFileURL(path.join(process.env.HIMA_DBOS_TEST_LIB??path.join(repoRoot,'packages/harness/lib'),name+'.js')).href),{loadPack}=await at('packs'),{loadSite}=await at('sites'),{jsonDigest}=await at('run-store'),{startFlow}=await at('flow-workflow'),{interactiveCommandsDigest,BUILTIN_TCL_ADAPTER_DIGEST}=await at('interactive-binding');
 const made=await createHimaHome(),h={...made,workspace:await fs.realpath(made.workspace)};let host:any;
 try {
  process.env.HIMA_TEST_SILENT_AGENT='1';process.env.HIMA_TEST_LEGACY_AUTO_DRIVE='0';process.env.HIMA_TEST_INTERACTIVE_BINDING_ID='chain-binding';
  if(process.env.HIMA_DBOS_TEST_PACKAGE){const link=path.join(h.profileDir,'node_modules/@hima/harness');await fs.rm(link,{recursive:true,force:true});await fs.symlink(process.env.HIMA_DBOS_TEST_PACKAGE,link,'dir');}
  const sitesDir=path.join(h.home,'hima/sites'),packsDir=path.join(h.home,'hima/packs'),dir=path.join(packsDir,'reader-chain');await fs.mkdir(sitesDir,{recursive:true});await fs.mkdir(path.join(h.home,'admin'),{recursive:true});await fs.mkdir(path.join(dir,'tools'),{recursive:true});
  const repl=path.join(dir,'tools/repl.tcl');await fs.writeFile(repl,'puts "HIMA:hima-tcl-line-v1:1:READY"\nflush stdout\nwhile {[gets stdin line] >= 0} {if {[catch {uplevel #0 $line} answer]} {puts stderr $answer};flush stdout;flush stderr}\n');
  const member={id:'operator',role:'operator',node:'operate',taskTemplate:'Read the exact Reader source and return chain-result/1 JSON.',inputs:['plan'],allowedTools:['hima_interactive'],scopePolicy:'site-qualified-interactive-only',budgetShare:{maxElapsedMs:30000,maxFollowups:0},dependencyRoles:[],resultSchema:{id:'chain-result/1',required:['schema','done']},recipient:'run-owner',ownerAdoption:'required',identity:'one-child-per-role-per-execution',followup:'forbidden',cancellation:'request-stop-preserve-unknown',terminal:['completed','cancelled','uncertain','refused'],refusalConditions:['missing-evidence'],reviewedAction:{mode:'request-scope',planInput:'plan',scopePath:['scope'],commands:['size'],maxMutations:1,hostPlanHashArgument:'planSha256'}};
  await fs.writeFile(path.join(dir,'contract.yml'),stringify({id:'reader-chain',version:'1',title:'Workshop observe Operator chain',inputs:[{name:'workspaceRoot'}],outputs:[{name:'plan',path:'plan.json',reader:'raw',description:'Actual sourced plan'}],strategy:{mode:{type:'choice',options:['fixture'],default:'fixture'}},environment:{wrappers:['/bin/sh','/usr/bin/tclsh']},workspace:{copy:[]},workshops:[{id:'analysis',purpose:'Write the actual plan',directory:'analysis',entry:'entry.sh',language:'sh',inputs:[],reads:[],knowledge:[],produces:'plan',argv:['/bin/sh','${ENTRY}','${WORKSPACE}'],licences:{}}],tools:[{id:'operate',file:'tools/repl.tcl',inputs:[],argv:['/usr/bin/tclsh',repl],interactive:{mode:'interactive-only',adapter:'hima-tcl-line-v1',commands:{read:['expr'],mutate:['size'],save:[]},arguments:{expr:[{name:'expression',type:'string'}],size:[{name:'instance',type:'string'},{name:'planSha256',type:'string'}]}}}],agentTeams:[{id:'chain-team',version:'1',triggerNode:'operate',members:[member]}]}));
  await fs.writeFile(path.join(dir,'graph.yml'),stringify({id:'reader-chain',version:'1',entry:'analyze',nodes:[{id:'analyze',kind:'act',parameters:{workshop:'analysis'}},{id:'read-plan',kind:'act',parameters:{observes:'plan'}},{id:'operate',kind:'act',parameters:{tool:'operate'}}],edges:[{from:'analyze',to:'read-plan'},{from:'read-plan',to:'operate'}]}));
  await fs.writeFile(path.join(sitesDir,'chain.permit.yml'),stringify({allowedReadRoots:[h.workspace,dir,path.join(h.home,'admin')],allowedWriteRoots:[h.workspace],allowedWrappers:['/bin/sh','/usr/bin/tclsh'],forbidden:['services','licences','network','deletions','downloads']}));await fs.writeFile(path.join(sitesDir,'chain.yml'),stringify({name:'chain',kind:'local',workspaceRoot:h.workspace,permit:'./chain.permit.yml',bindings:{workspaceRoot:h.workspace},capacity:{cores:2,memoryGiB:1,parallelJobs:1,licences:{}}}));
  const pack=loadPack(packsDir,'reader-chain'),site=loadSite(sitesDir,'chain'),environment=path.join(h.home,'admin/environment.txt'),bindingsFile=path.join(h.home,'bindings.json');await fs.writeFile(environment,'Actual local Tcl Operator fixture\n');const {createHash}=await import('node:crypto');await fs.writeFile(bindingsFile,JSON.stringify({schema:'hima-interactive-bindings/1',bindings:[{id:'chain-binding',site:'chain',packDigest:pack.flow.packSha256,toolId:'operate',adapter:'hima-tcl-line-v1',adapterHash:BUILTIN_TCL_ADAPTER_DIGEST,commandsDigest:interactiveCommandsDigest(pack.contract.tools[0]),environment:{id:'chain',file:environment,sha256:createHash('sha256').update(await fs.readFile(environment)).digest('hex')},mutation:'qualified'}]}));
  const say=(text:string)=>({kind:'chunks',chunks:[{type:'block-start',index:0,blockType:'text'},{type:'block-end',index:0,block:{type:'text',text}},{type:'finish',reason:{kind:'stop'}}]});let fixture={...await writeMomentFixture(h,'one-turn'),children:[] as readonly string[]};await fs.writeFile(fixture.override,JSON.stringify([{kind:'chunks',chunks:[{type:'block-start',index:0,blockType:'tool-call'},{type:'block-end',index:0,block:{type:'tool-call',id:'chain-entry',name:'hima_workshop_write',arguments:JSON.stringify({path:'entry.sh',content:'printf \'{"proof":42,"scope":{"commands":["size"],"maxMutations":1}}\\n\' > "$1/plan.json"\n'})}},{type:'finish',reason:{kind:'tool-calls'}}]},say('Actual entry written.')]));fixture=await appendReplaySession(fixture,'chain-operator',[say('{"schema":"chain-result/1","done":true}') as any]);await writeReplayOverlay(h.home,{file:fixture.file,overrideFile:fixture.override,childFiles:fixture.children});
  await fs.appendFile(homePatchFile(h.home),`\n- id: hima\n  config:\n    sitesDir: ${JSON.stringify(sitesDir)}\n    packsDir: ${JSON.stringify(packsDir)}\n    interactiveBindingsFile: ${JSON.stringify(bindingsFile)}\n    knowledgeDir: ${JSON.stringify(path.join(h.home,'hima/knowledge/current'))}\n`);host=await bootInProcess(h,{withWebApp:true});const parent=await createPresetRootAgent(host.ctx,h.workspace,'standard'),runtime=host.ctx.hima.durable;
  const run=await runtime.store.createRun({runId:'workshop-observe-team',inputSha256:jsonDigest({}),applicationVersion:runtime.applicationVersion,owner:String(parent.id),deadlineAt:new Date(Date.now()+30000).toISOString(),data:{budget:{retryAllowance:3,generationLimit:1},product:{campaignId:'chain',siteId:'chain',siteDigest:jsonDigest(site),workspace:h.workspace,bindings:{workspaceRoot:h.workspace},method:{packId:pack.id,packDigest:pack.flow.packSha256,retainedPackDir:dir},parentSessionId:String(parent.id),modelSelection:{provider:parent.options.provider,model:parent.options.model}}}});const registry=host.ctx.get('agents'),originalGet=registry.get.bind(registry);let parentReady=false;registry.get=(id:any)=>String(id)===String(parent.id)&&!parentReady?undefined:originalGet(id);
  const handle=await startFlow(runtime,{runId:run.runId,flow:pack.flow,runInput:{},goal:{},strategy:{mode:'fixture'}});
  let pendingParent:any;for(let n=0;n<400;n++){pendingParent=(await runtime.store.flowProjection(run.runId)).tasks.find((row:any)=>row.identity.taskId==='operate');if(pendingParent?.state?.diagnostic?.code==='native-parent-unavailable')break;await new Promise(resolve=>setTimeout(resolve,10));}
  assert.equal(pendingParent?.state?.diagnostic?.code,'native-parent-unavailable',JSON.stringify(pendingParent));assert.equal(await runtime.store.effect(pendingParent.identity.effectId),undefined,'Missing original parent claims no new Team/native business effect');assert.equal((await runtime.store.flowProjection(run.runId)).tasks.find((row:any)=>row.identity.taskId==='read-plan').state.state,'succeeded','Frozen-model Workshop and physical Reader do not require parent restoration');parentReady=true;registry.get=originalGet;
  let timer:any;const outcome:any=await Promise.race([handle.getResult(),new Promise((_,reject)=>{timer=setTimeout(async()=>reject(new Error('Reader chain did not settle: '+JSON.stringify(await runtime.store.flowProjection(run.runId)))),14000);})]);clearTimeout(timer);assert.equal(outcome.state,'succeeded',JSON.stringify(outcome));
  const observe=outcome.committed['read-plan'].value.observations[0],produced=outcome.committed.analyze.value.observations[0],options=await runtime.store.externalEffectFact(outcome.committed.operate.identity,'member-options:operator');assert.notEqual(observe.id,produced.id);assert.deepEqual(options.contract.inputRefs,[observe.id]);assert.equal(options.operatorGrant?.nodeId,'operate');const {delegationChildSessionId}=await at('delegation'),child=delegationChildSessionId(options.contract.parentSessionId,options.contract.delegationId),events=(await host.ctx.get('sessionQuery').readSession(child)).events;assert.ok(JSON.stringify(events).includes(observe.id),'Actual native Operator receives the explicit observe fact');assert.equal(JSON.stringify(events).includes(produced.id),false,'Producer collection is not supplied as a competing source');assert.equal(outcome.committed.operate.value.members.operator.value.done,true);assert.equal(await fs.readFile(observe.retainedPath,'utf8'),'{"proof":42,"scope":{"commands":["size"],"maxMutations":1}}\n');
 } finally {delete process.env.HIMA_TEST_INTERACTIVE_BINDING_ID;await host?.dispose();await fs.rm(h.home,{recursive:true,force:true});}
});

test('bridge hydrates its frozen method after actual process kill with the current folder unavailable', {timeout:60000},async()=>{
 const {rename}=await import('node:fs/promises'),path=(await import('node:path')).default,home=await dbosHome();
 const launch=(mode:string)=>{const child=spawn(process.execPath,[fileURLToPath(new URL('./support/durable-bridge-recovery-worker.ts',import.meta.url)),home,mode],{env:process.env,stdio:['ignore','pipe','pipe','ipc']});let stderr='';child.stderr!.on('data',value=>stderr+=value);const messages:any[]=[],pending:any[]=[];child.on('message',m=>{if(pending.length)pending.shift().resolve(m);else messages.push(m);});const ended=new Promise<void>(resolve=>child.once('close',()=>{for(const p of pending)p.reject(new Error(stderr));resolve();}));return {child,ended,next:()=>messages.length?Promise.resolve(messages.shift()):new Promise<any>((resolve,reject)=>pending.push({resolve,reject})),stderr:()=>stderr};};
 let first:any,second:any;
 try{first=launch('seed');const seeded=await first.next();assert.equal(seeded.stage,'seeded');assert.ok(seeded.snapshotBytes>0);await rename(path.join(home,'packs/recovery-method'),path.join(home,'packs/unavailable-method'));first.child.kill('SIGKILL');await first.ended;second=launch('recover');const waiting=await second.next();assert.equal(waiting.stage,'waiting');assert.equal(waiting.effectId,seeded.effectId);await rename(path.join(home,'packs/unavailable-method'),path.join(home,'packs/recovery-method'));second.child.send({action:'restored'});const finished=await second.next();assert.equal(finished.stage,'finished');assert.equal(finished.effectId,seeded.effectId);second.child.send({action:'close'});await second.ended;
 }finally{for(const item of [first,second])if(item&&item.child.exitCode===null&&item.child.signalCode===null){item.child.kill('SIGKILL');await item.ended;}await cleanDbosHome(home);}
});

test('Internal native reconciliation checks current method before its original unsent child', {timeout:90000}, async()=>{
 const fs=await import('node:fs/promises'),path=(await import('node:path')).default,{pathToFileURL}=await import('node:url'),{stringify}=await import('yaml');
 const {createHimaHome,repoRoot}=await import('./support/dsh-home.ts'),{bootInProcess,createPresetRootAgent}=await import('./support/boot-inprocess.ts'),{writeMomentFixture,appendReplaySession}=await import('./support/moments.ts'),{writeReplayOverlay,homePatchFile}=await import('../../packages/desktop/src/hima-home.ts');
 const at=(name:string)=>import(pathToFileURL(path.join(process.env.HIMA_DBOS_TEST_LIB??path.join(repoRoot,'packages/harness/lib'),name+'.js')).href),{loadPack}=await at('packs'),{loadSite}=await at('sites'),{jsonDigest}=await at('run-store'),{startFlow}=await at('flow-workflow'),{interactiveCommandsDigest,BUILTIN_TCL_ADAPTER_DIGEST}=await at('interactive-binding');
 const made=await createHimaHome(),h={...made,workspace:await fs.realpath(made.workspace)};let host:any;
 try {
  process.env.HIMA_TEST_SILENT_AGENT='1';process.env.HIMA_TEST_LEGACY_AUTO_DRIVE='0';process.env.HIMA_TEST_INTERACTIVE_BINDING_ID='chain-binding';
  if(process.env.HIMA_DBOS_TEST_PACKAGE){const link=path.join(h.profileDir,'node_modules/@hima/harness');await fs.rm(link,{recursive:true,force:true});await fs.symlink(process.env.HIMA_DBOS_TEST_PACKAGE,link,'dir');}
  const sitesDir=path.join(h.home,'hima/sites'),packsDir=path.join(h.home,'hima/packs'),dir=path.join(packsDir,'reader-chain');await fs.mkdir(sitesDir,{recursive:true});await fs.mkdir(path.join(h.home,'admin'),{recursive:true});await fs.mkdir(path.join(dir,'tools'),{recursive:true});
  const repl=path.join(dir,'tools/repl.tcl');await fs.writeFile(repl,'puts "HIMA:hima-tcl-line-v1:1:READY"\nflush stdout\nwhile {[gets stdin line] >= 0} {if {[catch {uplevel #0 $line} answer]} {puts stderr $answer};flush stdout;flush stderr}\n');
  const member={id:'operator',role:'operator',node:'operate',taskTemplate:'Read the exact Reader source and return chain-result/1 JSON.',inputs:['plan'],allowedTools:['hima_interactive'],scopePolicy:'site-qualified-interactive-only',budgetShare:{maxElapsedMs:60000,maxFollowups:0},dependencyRoles:[],resultSchema:{id:'chain-result/1',required:['schema','done']},recipient:'run-owner',ownerAdoption:'required',identity:'one-child-per-role-per-execution',followup:'forbidden',cancellation:'request-stop-preserve-unknown',terminal:['completed','cancelled','uncertain','refused'],refusalConditions:['missing-evidence'],reviewedAction:{mode:'request-scope',planInput:'plan',scopePath:['scope'],commands:['size'],maxMutations:1,hostPlanHashArgument:'planSha256'}};
  await fs.writeFile(path.join(dir,'contract.yml'),stringify({id:'reader-chain',version:'1',title:'Workshop observe Operator chain',inputs:[{name:'workspaceRoot'}],outputs:[{name:'plan',path:'plan.json',reader:'raw',description:'Actual sourced plan'}],strategy:{mode:{type:'choice',options:['fixture'],default:'fixture'}},environment:{wrappers:['/bin/sh','/usr/bin/tclsh']},workspace:{copy:[]},workshops:[{id:'analysis',purpose:'Write the actual plan',directory:'analysis',entry:'entry.sh',language:'sh',inputs:[],reads:[],knowledge:[],produces:'plan',argv:['/bin/sh','${ENTRY}','${WORKSPACE}'],licences:{}}],tools:[{id:'operate',file:'tools/repl.tcl',inputs:[],argv:['/usr/bin/tclsh',repl],interactive:{mode:'interactive-only',adapter:'hima-tcl-line-v1',commands:{read:['expr'],mutate:['size'],save:[]},arguments:{expr:[{name:'expression',type:'string'}],size:[{name:'instance',type:'string'},{name:'planSha256',type:'string'}]}}}],agentTeams:[{id:'chain-team',version:'1',triggerNode:'operate',members:[member]}]}));
  await fs.writeFile(path.join(dir,'graph.yml'),stringify({id:'reader-chain',version:'1',entry:'analyze',nodes:[{id:'analyze',kind:'act',parameters:{workshop:'analysis'}},{id:'read-plan',kind:'act',parameters:{observes:'plan'}},{id:'operate',kind:'act',parameters:{tool:'operate'}}],edges:[{from:'analyze',to:'read-plan'},{from:'read-plan',to:'operate'}]}));
  await fs.writeFile(path.join(sitesDir,'chain.permit.yml'),stringify({allowedReadRoots:[h.workspace,dir,path.join(h.home,'admin')],allowedWriteRoots:[h.workspace],allowedWrappers:['/bin/sh','/usr/bin/tclsh'],forbidden:['services','licences','network','deletions','downloads']}));await fs.writeFile(path.join(sitesDir,'chain.yml'),stringify({name:'chain',kind:'local',workspaceRoot:h.workspace,permit:'./chain.permit.yml',bindings:{workspaceRoot:h.workspace},capacity:{cores:2,memoryGiB:1,parallelJobs:1,licences:{}}}));
  const pack=loadPack(packsDir,'reader-chain'),site=loadSite(sitesDir,'chain'),environment=path.join(h.home,'admin/environment.txt'),bindingsFile=path.join(h.home,'bindings.json');await fs.writeFile(environment,'Actual local Tcl Operator fixture\n');const {createHash}=await import('node:crypto');await fs.writeFile(bindingsFile,JSON.stringify({schema:'hima-interactive-bindings/1',bindings:[{id:'chain-binding',site:'chain',packDigest:pack.flow.packSha256,toolId:'operate',adapter:'hima-tcl-line-v1',adapterHash:BUILTIN_TCL_ADAPTER_DIGEST,commandsDigest:interactiveCommandsDigest(pack.contract.tools[0]),environment:{id:'chain',file:environment,sha256:createHash('sha256').update(await fs.readFile(environment)).digest('hex')},mutation:'qualified'}]}));
  const say=(text:string)=>({kind:'chunks',chunks:[{type:'block-start',index:0,blockType:'text'},{type:'block-end',index:0,block:{type:'text',text}},{type:'finish',reason:{kind:'stop'}}]});let fixture={...await writeMomentFixture(h,'one-turn'),children:[] as readonly string[]};await fs.writeFile(fixture.override,JSON.stringify([{kind:'chunks',chunks:[{type:'block-start',index:0,blockType:'tool-call'},{type:'block-end',index:0,block:{type:'tool-call',id:'chain-entry',name:'hima_workshop_write',arguments:JSON.stringify({path:'entry.sh',content:'printf \'{"proof":42,"scope":{"commands":["size"],"maxMutations":1}}\\n\' > "$1/plan.json"\n'})}},{type:'finish',reason:{kind:'tool-calls'}}]},say('Actual entry written.')]));fixture=await appendReplaySession(fixture,'chain-operator',[say('{"schema":"chain-result/1","done":true}') as any]);await writeReplayOverlay(h.home,{file:fixture.file,overrideFile:fixture.override,childFiles:fixture.children});
  await fs.appendFile(homePatchFile(h.home),`\n- id: hima\n  config:\n    sitesDir: ${JSON.stringify(sitesDir)}\n    packsDir: ${JSON.stringify(packsDir)}\n    interactiveBindingsFile: ${JSON.stringify(bindingsFile)}\n    knowledgeDir: ${JSON.stringify(path.join(h.home,'hima/knowledge/current'))}\n`);host=await bootInProcess(h,{withWebApp:true});const parent=await createPresetRootAgent(host.ctx,h.workspace,'standard'),runtime=host.ctx.hima.durable;
  const run=await runtime.store.createRun({runId:'workshop-observe-team',inputSha256:jsonDigest({}),applicationVersion:runtime.applicationVersion,owner:String(parent.id),deadlineAt:new Date(Date.now()+120000).toISOString(),data:{budget:{retryAllowance:3,generationLimit:1},product:{campaignId:'chain',siteId:'chain',siteDigest:jsonDigest(site),workspace:h.workspace,bindings:{workspaceRoot:h.workspace},method:{packId:pack.id,packDigest:pack.flow.packSha256,retainedPackDir:dir},parentSessionId:String(parent.id),modelSelection:{provider:parent.options.provider,model:parent.options.model}}}});let gated=false,release=()=>{};const barrier=new Promise<void>(resolve=>release=resolve),rawClaim=runtime.store.claimEffectDispatch.bind(runtime.store);let childIdentity:any;
 runtime.store.claimEffectDispatch=async(...args:any[])=>{const answer=await rawClaim(...args);if(args[0].effectId.endsWith(':member-operator')&&args[2]==='submit'&&answer&&!gated){childIdentity=(await runtime.store.effect(args[0].effectId)).identity;gated=true;await barrier;}return answer;};
 const handle=await startFlow(runtime,{runId:run.runId,flow:pack.flow,runInput:{},goal:{},strategy:{mode:'fixture'}});
 for(let n=0;n<1000&&!gated;n++)await new Promise(resolve=>setTimeout(resolve,10));assert.equal(gated,true,'Original native member overall submit was actually claimed');
 const {controlFlow}=await at('flow-workflow');await (await controlFlow(runtime,{runId:run.runId,commandId:'pause-before-member',action:'pause',owner:run.owner,epoch:0,revision:0})).getResult();release();
 const invocation=(await runtime.store.flowInvocations(run.runId)).find((row:any)=>row.identity.taskId==='operate'),options=await runtime.store.externalEffectFact(invocation.identity,'member-options:operator');
 assert.equal(await runtime.store.effectDispatchExists(childIdentity,'submit'),true);assert.equal(await runtime.store.effectDispatchExists(childIdentity,'native-child:'+options.contract.delegationId),false);
 const {delegationChildSessionId}=await at('delegation'),childId=delegationChildSessionId(options.contract.parentSessionId,options.contract.delegationId);let nativeStarts=0;host.ctx.on('agent/request',async({agent}:any,next:any)=>{if(String(agent.id)===childId)nativeStarts++;return next();});
 const original=await fs.readFile(path.join(dir,'contract.yml'));await fs.appendFile(path.join(dir,'contract.yml'),'\n# unexpected retained method edit\n');
 await (await controlFlow(runtime,{runId:run.runId,commandId:'continue-original-unsent-member',action:'continue',owner:run.owner,epoch:1,revision:0})).getResult();
 let reason='';for(let n=0;n<600;n++){const projection=await runtime.store.flowProjection(run.runId);reason=projection.tasks.find((row:any)=>row.identity.taskId==='operate')?.state?.reason??'';if(/retained method bytes differ/.test(reason)||await runtime.store.effectDispatchExists(childIdentity,'native-child:'+options.contract.delegationId))break;await new Promise(resolve=>setTimeout(resolve,10));}
 const nativeClaimed=await runtime.store.effectDispatchExists(childIdentity,'native-child:'+options.contract.delegationId);if(nativeClaimed)for(let n=0;n<200&&!nativeStarts;n++)await new Promise(resolve=>setTimeout(resolve,10));console.error('Observed original native boundary',JSON.stringify({overallSubmit:await runtime.store.effectDispatchExists(childIdentity,'submit'),nativeChild:nativeClaimed,changedMethod:true,nativeStarts,reason}));assert.equal(nativeClaimed,false,'No native API claim for changed original Pack');assert.match(reason,/retained method bytes differ/,'Fresh method corruption blocks the internal native reconcile send');
 assert.equal(nativeStarts,0,'No native start while original method is changed');assert.equal(host.ctx.get('agents').get(childId),undefined,'Zero new native child was started');
 await fs.writeFile(path.join(dir,'contract.yml'),original);
  let timer:any;const outcome:any=await Promise.race([handle.getResult(),new Promise((_,reject)=>{timer=setTimeout(async()=>reject(new Error('Reader chain did not settle: '+JSON.stringify(await runtime.store.flowProjection(run.runId)))),14000);})]);clearTimeout(timer);assert.equal(outcome.state,'succeeded',JSON.stringify(outcome));
  runtime.store.claimEffectDispatch=rawClaim;const observe=outcome.committed['read-plan'].value.observations[0],produced=outcome.committed.analyze.value.observations[0],heldOptions=await runtime.store.externalEffectFact(outcome.committed.operate.identity,'member-options:operator');assert.equal(await runtime.store.effectDispatchExists(childIdentity,'native-child:'+options.contract.delegationId),true,'Restore admits the original child');assert.notEqual(observe.id,produced.id);assert.deepEqual(options.contract.inputRefs,[observe.id]);assert.equal(options.operatorGrant?.nodeId,'operate');const child=delegationChildSessionId(options.contract.parentSessionId,options.contract.delegationId),events=(await host.ctx.get('sessionQuery').readSession(child)).events;assert.equal(nativeStarts,1,'Restore starts the original native child once');assert.equal(events.filter((event:any)=>event.type==='turn/start').length,1,'One original child start');assert.ok(JSON.stringify(events).includes(observe.id),'Actual native Operator receives the explicit observe fact');assert.equal(JSON.stringify(events).includes(produced.id),false,'Producer collection is not supplied as a competing source');assert.equal(outcome.committed.operate.value.members.operator.value.done,true);assert.equal(await fs.readFile(observe.retainedPath,'utf8'),'{"proof":42,"scope":{"commands":["size"],"maxMutations":1}}\n');
 } finally {delete process.env.HIMA_TEST_INTERACTIVE_BINDING_ID;await host?.dispose();await fs.rm(h.home,{recursive:true,force:true});}
});
